# Generated by Django 2.2.8 on 2019-12-09 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("telegram", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="telegramgroup", name="telegram_id"),
        migrations.AddField(
            model_name="telegramgroup",
            name="telegram_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(editable=False, null=True),
                default=list,
                size=None,
                verbose_name="Identifiants des groupes sur Telegram",
            ),
        ),
    ]
