# Generated by Django 2.2.8 on 2019-12-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("telegram", "0002_auto_20191209_1530")]

    operations = [
        migrations.AddField(
            model_name="telegramgroup",
            name="telegram_users",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                verbose_name="Nombre d'utilisateurices de Telegram dans le segment",
            ),
        )
    ]
