# Generated by Django 2.2.4 on 2019-08-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("municipales", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="communepage",
            options={
                "verbose_name": "Page de commune",
                "verbose_name_plural": "Pages de commune",
            },
        ),
        migrations.AddField(
            model_name="communepage",
            name="twitter",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Identifiant Twitter"
            ),
        ),
    ]
