# Generated by Django 2.2.7 on 2019-12-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("municipales", "0006_search")]

    operations = [
        migrations.AddField(
            model_name="communepage",
            name="adresse_mandataire",
            field=models.TextField(
                blank=True, verbose_name="Adresse complète du mandataire financier"
            ),
        ),
        migrations.AddField(
            model_name="communepage",
            name="nom_mandataire",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom du manadataire financier"
            ),
        ),
        migrations.AddField(
            model_name="communepage",
            name="published",
            field=models.BooleanField(default=False, verbose_name="Publiée"),
        ),
        migrations.AlterField(
            model_name="communepage",
            name="facebook",
            field=models.CharField(
                blank=True,
                help_text="Indiquez l'identifiant ou l'URL de la page Facebook de la campagne",
                max_length=255,
                verbose_name="Identifiant Facebook",
            ),
        ),
        migrations.AlterField(
            model_name="communepage",
            name="twitter",
            field=models.CharField(
                blank=True,
                help_text="Indiquez l'identifiant ou l'URL du compte Twitter de la campagne.",
                max_length=255,
                verbose_name="Identifiant Twitter",
            ),
        ),
    ]
