# Generated by Django 2.2.8 on 2019-12-11 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("municipales", "0007_ajouter_champs")]

    operations = [
        migrations.RenameField(
            model_name="communepage",
            old_name="municipale_list_name",
            new_name="strategy",
        )
    ]
