# Generated by Django 2.2.8 on 2019-12-16 15:18

import agir.lib.model_fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("municipales", "0009_auto_20191211_1713")]

    operations = [
        migrations.AlterField(
            model_name="communepage",
            name="facebook",
            field=agir.lib.model_fields.FacebookPageField(
                blank=True,
                help_text="Indiquez l'identifiant ou l'URL de la page Facebook de la campagne",
                max_length=255,
                verbose_name="Identifiant Facebook",
            ),
        ),
        migrations.AlterField(
            model_name="communepage",
            name="twitter",
            field=agir.lib.model_fields.TwitterProfileField(
                blank=True,
                help_text="Indiquez l'identifiant ou l'URL du compte Twitter de la campagne.",
                max_length=15,
                verbose_name="Identifiant Twitter",
            ),
        ),
    ]
