# Generated by Django 2.2.9 on 2020-01-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("municipales", "0010_auto_20191216_1618")]

    operations = [
        migrations.AddField(
            model_name="communepage",
            name="tete_liste",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="Nom de la tête de liste",
                help_text="Le nom de la tête de liste, tel qu'il s'affichera publiquement",
            ),
        ),
        migrations.AddField(
            model_name="communepage",
            name="contact_email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                verbose_name="Adresse email de contact",
                help_text="Une adresse email publique qui peut être utilisée pour contacter votre campagne",
            ),
        ),
        migrations.RenameField(
            model_name="communepage", old_name="nom_mandataire", new_name="ordre_don"
        ),
        migrations.RenameField(
            model_name="communepage",
            old_name="adresse_mandataire",
            new_name="adresse_don",
        ),
        migrations.AlterField(
            model_name="communepage",
            name="adresse_don",
            field=models.TextField(
                blank=True,
                help_text="Cette adresse sera affichée sur la page pour inciter les visiteurs à envoyer leurs dons par chèque.",
                verbose_name="Adresse complète pour les dons",
            ),
        ),
        migrations.AlterField(
            model_name="communepage",
            name="ordre_don",
            field=models.CharField(
                blank=True,
                help_text="Indiquez l'ordre auquel les chèques de dons doivent être adressés.",
                max_length=255,
                verbose_name="Ordre des chèques",
            ),
        ),
        migrations.AlterField(
            model_name="communepage",
            name="website",
            field=models.URLField(
                blank=True,
                help_text="Indiquez l'URL du site web de la liste en entier (avec le http:// ou le https://)",
                max_length=255,
                verbose_name="Site web",
            ),
        ),
    ]
