# Generated by Django 2.2.10 on 2020-03-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("municipales", "0014_contrainte_liste_soutenue_unique")]

    operations = [
        migrations.AlterModelOptions(name="liste", options={"ordering": ("code",)}),
        migrations.AlterField(
            model_name="liste",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listes",
                related_query_name="liste",
                to="municipales.CommunePage",
            ),
        ),
    ]
