# Generated by Django 2.2.10 on 2020-03-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("municipales", "0015_auto_20200305_1750")]

    operations = [
        migrations.AddField(
            model_name="communepage",
            name="population",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Population municipale"
            ),
        )
    ]
