# Generated by Django 2.2.11 on 2020-03-26 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("municipales", "0016_communepage_population"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="liste",
            name="candidats",
        ),
        migrations.AddField(
            model_name="liste",
            name="candidats_communautaire",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BooleanField(),
                default=list,
                size=None,
                verbose_name="Candidats pour le conseil communautaire",
            ),
        ),
        migrations.AddField(
            model_name="liste",
            name="candidats_noms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                default=list,
                size=None,
                verbose_name="Noms candidats",
            ),
        ),
        migrations.AddField(
            model_name="liste",
            name="candidats_prenoms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                default=list,
                size=None,
                verbose_name="Prénoms candidats",
            ),
        ),
    ]
