# Generated by Django 2.2.13 on 2020-06-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("municipales", "0019_listes_2eme_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communepage",
            name="liste_tour_1",
            field=models.CharField(
                blank=True,
                help_text="Le nom de la liste tel qu'il sera affiché publiquement",
                max_length=255,
                verbose_name="Nom de la liste du 1er tour",
            ),
        ),
        migrations.AlterField(
            model_name="communepage",
            name="liste_tour_2",
            field=models.CharField(
                blank=True,
                help_text="Le nom de la liste tel qu'il sera affiché publiquement",
                max_length=255,
                verbose_name="Nom de la liste du 2e tour",
            ),
        ),
    ]
