# Generated by Django 2.2.6 on 2019-10-25 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social_django", "0008_partial_timestamp"),
        ("authentication", "0003_add_view_hidden_events_to_workers"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgirSocialUser",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": []},
            bases=("social_django.usersocialauth",),
        )
    ]
