# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('email',), 'verbose_name': 'personne', 'verbose_name_plural': 'personnes'},
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text="UUID interne à l'API pour identifier la ressource", primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nb_id',
            field=models.IntegerField(help_text="L'identifiant de la ressource correspondante sur NationBuilder, si importé.", null=True, unique=True, verbose_name='ID sur NationBuilder'),
        ),
    ]
