# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subscribed',
            field=models.BooleanField(default=True, help_text="L'utilisateur souhaite-t-il recevoir les newsletters ?", verbose_name='inscrit à la newsletter'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bounced_date',
            field=models.DateTimeField(blank=True, help_text='Si des mails ont été rejetés, indique la date du dernier rejet', null=True, verbose_name="date de rejet de l'email"),
        ),
        migrations.AlterField(
            model_name='person',
            name='coordinates_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude géographique'),
        ),
        migrations.AlterField(
            model_name='person',
            name='coordinates_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude géographique'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nb_id',
            field=models.IntegerField(blank=True, help_text="L'identifiant de la ressource correspondante sur NationBuilder, si importé.", null=True, unique=True, verbose_name='ID sur NationBuilder'),
        ),
    ]
