# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170509_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ('-created',), 'verbose_name': 'personne', 'verbose_name_plural': 'personnes'},
        ),
    ]
