# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20170728_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='people.Person'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='personemail',
            order_with_respect_to='person',
        ),
    ]
