# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20170731_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personemail',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='people.Person'),
        ),
    ]
