# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-03 13:43
from __future__ import unicode_literals

from django.db import migrations
import phonenumbers


def format_phones(apps, schema):
    Person = apps.get_model('people', 'Person')

    for p in Person.objects.exclude(contact_phone__exact=""):
        try:
            num = phonenumbers.parse(p.contact_phone, "FR")
        except phonenumbers.phonenumberutil.NumberParseException:
            p.contact_phone = ""
            p.save()
            continue

        if phonenumbers.is_valid_number(num):
            p.contact_phone = phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.E164)
            p.save()
        else:
            p.contact_phone = ""
            p.save()


def unformat_phones(apps, schema):
    # nothing to do
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_person_coordinates_type'),
    ]

    operations = [
        migrations.RunPython(format_phones, unformat_phones)
    ]
