# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_person_draw_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location_address',
            field=models.CharField(blank=True, help_text="L'adresse telle qu'elle a éventuellement été copiée depuis NationBuilder. Ne plus utiliser.", max_length=255, verbose_name='adresse complète'),
        ),
    ]
