# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 12:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0026_auto_20180306_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mandates',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='Mandats électoraux'),
        ),
    ]
