# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 15:30
from __future__ import unicode_literals

from django.db import migrations
import people.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0027_person_mandates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mandates',
            field=people.model_fields.MandatesField(blank=True, default=list, verbose_name='Mandats électoraux'),
        ),
    ]
