# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorization',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authorization',
            name='scopes',
            field=models.ManyToManyField(related_name='authorizations', to='clients.Scope'),
        ),
        migrations.AlterUniqueTogether(
            name='authorization',
            unique_together=set([('person', 'client')]),
        ),
    ]
