# Generated by Django 3.1.2 on 2020-11-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={
                "ordering": ("-timestamp",),
                "verbose_name": "Notice d'activité",
                "verbose_name_plural": "Notices d'activité",
            },
        ),
        migrations.RemoveIndex(
            model_name="activity",
            name="notifications_by_recipient",
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["recipient", "timestamp"], name="notifications_by_recipient"
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("U", "Pas encore présentée au destinataire"),
                    ("S", "Présentée au destinataire"),
                    ("I", "Le destinataire a interagi avec"),
                ],
                default="U",
                max_length=1,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="type",
            field=models.CharField(
                choices=[
                    ("waiting-payment", "Paiement en attente"),
                    ("group-invitation", "Invitation à un groupe"),
                    ("new-member", "Nouveau membre"),
                    ("waiting-location-group", "Préciser la localisation du groupe"),
                    (
                        "group-coorganization-invite",
                        "Invitation à coorganiser un groupe reçue",
                    ),
                    (
                        "waiting-location-event",
                        "Préciser la localisation d'un événement",
                    ),
                    (
                        "group-coorganization-accepted",
                        "Invitation à coorganiser un groupe acceptée",
                    ),
                    ("group-info-update", "Mise à jour des informations du groupe"),
                    (
                        "accepted-invitation-member",
                        "Invitation à rejoindre un groupe acceptée",
                    ),
                    ("new-attendee", "Un nouveau participant à votre événement"),
                    ("event-update", "Mise à jour d'un événement"),
                    ("new-event-mygroups", "Votre groupe organise un événement"),
                    ("new-report", "Nouveau compte-rendu d'événement"),
                    ("new-event-aroundme", "Nouvel événement près de chez moi"),
                    ("cancelled-event", "Événement annulé"),
                ],
                max_length=50,
                verbose_name="Type",
            ),
        ),
    ]
