# Generated by Django 3.1.3 on 2020-12-07 15:50

import agir.lib.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dynamic_filenames
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.NUNTIUS_SEGMENT_MODEL),
        ("activity", "0002_auto_20201104_1128"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Ce texte sera utilisé comme titre et texte du lien de l'annonce",
                        max_length=200,
                        verbose_name="Titre de l'annonce",
                    ),
                ),
                ("link", models.URLField(verbose_name="Lien")),
                ("content", agir.lib.models.DescriptionField(verbose_name="Contenu")),
                (
                    "image",
                    stdimage.models.StdImageField(
                        blank=True,
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="activity/announcements/{uuid:2base32}/{uuid:s}{ext}"
                        ),
                        validators=[stdimage.validators.MinSizeValidator(255, 160)],
                        verbose_name="Bannière",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Permet de modifier l'ordre d'affichage des annonces. Les valeurs plus élevées sont affichées avant. Deux annonces de même priorité sont affichées dans l'ordre anti-chronologique (par date de début)",
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Segment des personnes auquel ce message sera montré (laisser vide pour montrer à tout le monde)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        related_query_name="notification",
                        to=settings.NUNTIUS_SEGMENT_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Annonce",
                "ordering": ("start_date", "end_date"),
            },
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["start_date", "end_date"], name="announcement_date_index"
            ),
        ),
    ]
