# Generated by Django 3.1.3 on 2020-12-08 17:07

from django.db import migrations
import dynamic_filenames
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0003_announcements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="announcement",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="activity/announcements/{uuid:.2base32}/{uuid:s}{ext}"
                ),
                validators=[stdimage.validators.MinSizeValidator(255, 160)],
                verbose_name="Bannière",
            ),
        ),
    ]
