# Generated by Django 3.1.3 on 2020-12-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0004_auto_20201208_1807"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="announcement",
            options={
                "ordering": ("-start_date", "end_date"),
                "verbose_name": "Annonce",
            },
        ),
        migrations.RemoveIndex(
            model_name="announcement",
            name="announcement_date_index",
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["-start_date", "end_date"], name="announcement_date_index"
            ),
        ),
    ]
