# Generated by Django 3.1.3 on 2020-12-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0005_announcements_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("U", "Pas encore présentée au destinataire"),
                    ("S", "Présentée au destinataire"),
                    ("I", "Le destinataire a interagi avec"),
                ],
                default="U",
                max_length=1,
                verbose_name="Statut",
            ),
        ),
    ]
