# Generated by Django 3.1.8 on 2021-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0014_auto_20210406_1712"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="pushed",
            field=models.BooleanField(
                default=False, verbose_name="Notification push envoyée"
            ),
        ),
    ]
