# Generated by Django 3.1.11 on 2021-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0017_migrate_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="link_label",
            field=models.CharField(
                default="En savoir plus",
                help_text="Ce texte sera utilisé comme texte du lien de l'annonce",
                max_length=200,
                verbose_name="Libellé du lien",
            ),
        ),
        migrations.AlterField(
            model_name="announcement",
            name="title",
            field=models.CharField(
                help_text="Ce texte sera utilisé comme titre de l'annonce",
                max_length=200,
                verbose_name="Titre de l'annonce",
            ),
        ),
    ]
