# Generated by Django 3.2.12 on 2022-02-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activity", "0028_add-TYPE_REMINDER_UPCOMING_EVENT_START"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together=set(),
        ),
    ]
