# Generated by Django 3.2.18 on 2023-05-03 14:38

import agir.lib.validators
import django.core.validators
from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):
    dependencies = [
        ("activity", "0031_auto_20230427_1736"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pushannouncement",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                help_text="Utiliser une image au format JPEG avec un ratio de 2:1 et de maximum 5 MB.",
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="activity/pushannouncements/image/{uuid:.2base32}/{uuid:s}{ext}"
                ),
                validators=[
                    agir.lib.validators.FileSizeValidator(5242880),
                    django.core.validators.FileExtensionValidator(["jpg", "jpeg"]),
                ],
                variations={},
                verbose_name="Image",
            ),
        ),
    ]
