# Generated by Django 3.2.16 on 2022-11-23 13:27

import agir.lib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagnottes", "0002_auto_20221122_1718"),
    ]

    operations = [
        migrations.AddField(
            model_name="cagnotte",
            name="expediteur_email",
            field=models.CharField(
                blank=True,
                help_text="Adresse d'expédition pour l'email de remerciement",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="cagnotte",
            name="remerciements",
            field=agir.lib.models.DescriptionField(
                blank=True,
                help_text="Message de remerciement notamment utilisé dans le mail de confirmation.",
            ),
        ),
    ]
