# Generated by Django 3.2.16 on 2022-11-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cagnottes", "0003_auto_20221123_1427"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cagnotte",
            name="url_remerciement",
            field=models.URLField(
                help_text="L'URL vers laquelle rediriger après le paiement.",
                verbose_name="URL de remerciement",
            ),
        ),
    ]
