# Generated by Django 3.2.17 on 2023-02-10 15:02

import agir.lib.form_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cagnottes", "0004_alter_cagnotte_url_remerciement"),
    ]

    operations = [
        migrations.AddField(
            model_name="cagnotte",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=agir.lib.form_fields.CustomJSONEncoder,
                verbose_name="Paramètres de la cagnotte",
            ),
        ),
    ]
