# Generated by Django 3.2.18 on 2023-03-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="absolutestatistics",
            name="boucle_departementale_membership_person_count",
            field=models.IntegerField(
                default=0, verbose_name="Membres des boucles départementales"
            ),
        ),
    ]
