# Generated by Django 3.2.19 on 2023-06-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics", "0003_materielstatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="absolutestatistics",
            name="liaison_count",
            field=models.IntegerField(default=0, verbose_name="Relais insoumis"),
        ),
    ]
