# Generated by Django 3.2.20 on 2023-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics", "0005_communestatistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="absolutestatistics",
            name="undelivered_campaign_email_count",
            field=models.IntegerField(default=0, verbose_name="E-mails non remis"),
        ),
    ]
