# Generated by Django 3.2.23 on 2023-11-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("statistics", "0006_absolutestatistics_undelivered_campaign_email_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communestatistics",
            name="population",
            field=models.IntegerField(
                default=None, null=True, verbose_name="Population"
            ),
        ),
    ]
