# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [("clients", "0002_create_basic_scopes")]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="UUID interne à l'API pour identifier la ressource",
                primary_key=True,
                serialize=False,
                verbose_name="UUID",
            ),
        )
    ]
