# Generated by Django 3.1.14 on 2022-02-15 16:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0013_auto_20210324_1338"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="scopes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("view_profile", "Voir votre profil"),
                        ("edit_profile", "Changer votre profil"),
                        ("edit_event", "Éditer vos événements"),
                        (
                            "edit_rsvp",
                            "Voir et éditer vos participations aux événements",
                        ),
                        ("edit_supportgroup", "Éditer vos groupes d'action"),
                        (
                            "edit_membership",
                            "Voir et éditer vos participations aux groupes d'action",
                        ),
                        ("edit_authorization", "Éditer vos autorisations d'accès"),
                        (
                            "toktok",
                            "Accès aux informations nécessaires à l'application TokTok",
                        ),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                help_text="La liste des scopes autorisés pour ce client.",
                size=None,
            ),
        ),
    ]
