# Generated by Django 3.1.14 on 2022-01-11 11:50

import agir.lib.model_fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data_france", "0032_ajouts_csp"),
        ("people", "0015_add_person_created_id_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="VotingProxy",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID interne à l'API pour identifier la ressource",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Les prénoms tels qu'ils apparaissent sur la carte électorale",
                        max_length=255,
                        verbose_name="prénoms",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Le nom de famille tel qu'il apparaît sur la carte électorale",
                        max_length=255,
                        verbose_name="nom de famille",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="adresse email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=30, verbose_name="numéro de téléphone"),
                ),
                (
                    "polling_station_number",
                    models.CharField(
                        max_length=255, verbose_name="numéro du bureau de vote"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(null=True, verbose_name="Date de naissance"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "créé"),
                            ("invited", "invité"),
                            ("available", "disponible"),
                            ("unavailable", "indisponible"),
                        ],
                        default="created",
                        max_length=255,
                        verbose_name="statut",
                    ),
                ),
                (
                    "voting_dates",
                    agir.lib.model_fields.ChoiceArrayField(
                        base_field=models.CharField(
                            choices=[
                                (
                                    "2022-04-10",
                                    "10 avril 2022 — 1er tour de la présidentielle",
                                ),
                                (
                                    "2022-04-24",
                                    "24 avril 2022 — 2nd tour de la présidentielle",
                                ),
                                (
                                    "2022-06-12",
                                    "12 juin 2022 — 1er tour des législatives",
                                ),
                                (
                                    "2022-06-19",
                                    "19 juin 2022 — 2nd tour des législatives",
                                ),
                            ],
                            max_length=255,
                            verbose_name="date du scrutin",
                        ),
                        default=list,
                        size=None,
                        verbose_name="dates de disponibilité",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="remarques"),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_france.commune",
                        verbose_name="Commune",
                    ),
                ),
                (
                    "consulate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_france.circonscriptionconsulaire",
                        verbose_name="Circonscription consulaire",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voting_proxy",
                        to="people.person",
                        verbose_name="Personne",
                    ),
                ),
            ],
            options={
                "verbose_name": "volontaire pour le vote par procuration",
                "verbose_name_plural": "volontaires pour le vote par procuration",
            },
        ),
        migrations.CreateModel(
            name="VotingProxyRequest",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID interne à l'API pour identifier la ressource",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Les prénoms tels qu'ils apparaissent sur la carte électorale",
                        max_length=255,
                        verbose_name="prénoms",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Le nom de famille tel qu'il apparaît sur la carte électorale",
                        max_length=255,
                        verbose_name="nom de famille",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="adresse email"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=30, verbose_name="numéro de téléphone"),
                ),
                (
                    "polling_station_number",
                    models.CharField(
                        max_length=255, verbose_name="numéro du bureau de vote"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "demande créée"),
                            ("accepted", "demande acceptée"),
                            ("confirmed", "procuration confirmée"),
                            ("cancelled", "demande annulée"),
                        ],
                        default="created",
                        max_length=255,
                        verbose_name="statut de la demande",
                    ),
                ),
                (
                    "voting_date",
                    models.DateField(
                        choices=[
                            (
                                datetime.date(2022, 4, 10),
                                "10 avril 2022 — 1er tour de la présidentielle",
                            ),
                            (
                                datetime.date(2022, 4, 24),
                                "24 avril 2022 — 2nd tour de la présidentielle",
                            ),
                            (
                                datetime.date(2022, 6, 12),
                                "12 juin 2022 — 1er tour des législatives",
                            ),
                            (
                                datetime.date(2022, 6, 19),
                                "19 juin 2022 — 2nd tour des législatives",
                            ),
                        ],
                        verbose_name="date du scrutin",
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_france.commune",
                        verbose_name="Commune",
                    ),
                ),
                (
                    "consulate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data_france.circonscriptionconsulaire",
                        verbose_name="Circonscription consulaire",
                    ),
                ),
                (
                    "proxy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voting_proxy_requests",
                        to="voting_proxies.votingproxy",
                        verbose_name="Volontaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "demande de vote par procuration",
                "verbose_name_plural": "demandes de vote par procuration",
            },
        ),
        migrations.AddConstraint(
            model_name="votingproxyrequest",
            constraint=models.UniqueConstraint(
                fields=("email", "voting_date"), name="unique_for_email_and_voting_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="votingproxyrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(proxy__isnull=False),
                fields=("proxy", "voting_date"),
                name="unique_for_proxy_and_voting_date",
            ),
        ),
        migrations.AddConstraint(
            model_name="votingproxy",
            constraint=models.UniqueConstraint(
                fields=("email",), name="unique_for_email"
            ),
        ),
    ]
