# Generated by Django 3.1.14 on 2022-01-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting_proxies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingproxy",
            name="polling_station_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="numéro du bureau de vote"
            ),
        ),
        migrations.AlterField(
            model_name="votingproxyrequest",
            name="polling_station_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="numéro du bureau de vote"
            ),
        ),
    ]
