# Generated by Django 3.2.12 on 2022-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting_proxies", "0003_votingproxy_last_matched"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingproxy",
            name="voter_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="numéro national d'électeur",
            ),
        ),
        migrations.AddField(
            model_name="votingproxyrequest",
            name="voter_id",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="numéro national d'électeur",
            ),
        ),
        migrations.AlterField(
            model_name="votingproxy",
            name="polling_station_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="bureau de vote"
            ),
        ),
        migrations.AlterField(
            model_name="votingproxyrequest",
            name="polling_station_number",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="bureau de vote"
            ),
        ),
    ]
