# Generated by Django 3.2.12 on 2022-05-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voting_proxies", "0004_add_voter_id_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="votingproxyrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "demande créée"),
                    ("accepted", "demande acceptée"),
                    ("confirmed", "procuration confirmée"),
                    ("cancelled", "demande annulée"),
                    ("forwarded", "demande transférée à l'équipe de campagne"),
                ],
                default="created",
                max_length=255,
                verbose_name="statut de la demande",
            ),
        ),
    ]
