# Generated by Django 3.2.14 on 2022-10-16 00:30

import django.core.validators
from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):
    dependencies = [
        ("carte", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staticmapimage",
            name="image",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label}/{model_name}/{uuid:base32}{ext}"
                ),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "png"]
                    )
                ],
                variations={"default": (992, 300, True)},
                verbose_name="image",
            ),
        ),
    ]
