# Generated by Django 3.1.13 on 2021-09-27 13:31

import agir.lib.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0005_add_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LFI", "Lettre d'information de la France insoumise"),
                        ("2022", "Lettre d'information NSP"),
                        ("2022_exceptionnel", "NSP : informations exceptionnelles"),
                        ("2022_en_ligne", "NSP actions en ligne"),
                        ("2022_chez_moi", "NSP agir près de chez moi"),
                        ("2022_programme", "NSP processus programme"),
                        ("2022_liaison", "NSP Correspondant·e d'immeuble ou de rue"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
