# Generated by Django 3.1.13 on 2021-10-13 10:46

import django.core.validators
from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0006_add_newsletter_liaison_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                help_text="Vous pouvez ajouter une image publique de profil",
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label}/{model_name}/{instance.id}/{uuid:s}{ext}"
                ),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "gif", "png"]
                    )
                ],
                verbose_name="image de profil",
            ),
        ),
    ]
