# Generated by Django 3.1.13 on 2021-11-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0008_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personform",
            name="send_confirmation",
            field=models.BooleanField(
                default=False,
                help_text="Envoyer le contenu de la note après complétion par email, en plus de le montrer à l'utilisateur.",
                verbose_name="Envoyer une confirmation par email",
            ),
        ),
    ]
