# Generated by Django 3.1.13 on 2021-11-19 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0009_auto_20211116_1641"),
        ("people", "0009_update_person_trigger_functions"),
    ]

    operations = []
