# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 16:39
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0009_add_profile_fields")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="meta",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="Autres données"
            ),
        )
    ]
