# Generated by Django 3.1.13 on 2021-11-29 16:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0010_merge_20211119_1617"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ("-created",),
                "permissions": [
                    (
                        "select_person",
                        "Peut lister pour sélectionner (dans un Select 2 par exemple)",
                    ),
                    (
                        "export_people",
                        "Peut faire un export des informations des personnes",
                    ),
                ],
                "verbose_name": "personne",
                "verbose_name_plural": "personnes",
            },
        ),
    ]
