# Generated by Django 3.1.13 on 2021-11-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0010_merge_20211119_1617"),
    ]

    operations = [
        migrations.AddField(
            model_name="personform",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Description visible lors du partage sur les réseaux sociaux et lors des envois de rappels par notification",
                max_length=255,
                verbose_name="Description courte",
            ),
        ),
    ]
