# Generated by Django 3.1.13 on 2021-12-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0011_add_export_people_person_permission"),
    ]

    operations = [
        migrations.AddField(
            model_name="personform",
            name="short_description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Description visible lors du partage sur les réseaux sociaux et lors des envois de rappels par notification",
                max_length=255,
                verbose_name="Description courte",
            ),
        ),
    ]
