# Generated by Django 3.1.13 on 2021-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0013_person__email"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["created"], name="created_index"),
        ),
    ]
