# Generated by Django 3.1.14 on 2021-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0014_add_person_created_index"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="person",
            index=models.Index(fields=["created", "id"], name="created_id_index"),
        ),
    ]
