# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0014_switch_to_phone_number_field")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de naissance"
            ),
        )
    ]
