# Generated by Django 3.2.12 on 2022-03-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0015_add_person_created_id_index"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="location_state",
            new_name="location_country_name",
        ),
    ]
