# Generated by Django 3.2.13 on 2022-06-09 13:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0015_add_person_created_id_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Liaison",
            fields=[],
            options={
                "verbose_name": "correspondant·e d'immeuble et de quartier",
                "verbose_name_plural": "correspondant·es d'immeuble et de quartier",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("people.person",),
        ),
        migrations.AlterModelOptions(
            name="personform",
            options={"ordering": ("-created",), "verbose_name": "Formulaire"},
        ),
    ]
