# Generated by Django 3.2.14 on 2022-10-16 00:30

import django.core.validators
from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0016_auto_20220609_1533"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                help_text="Vous pouvez ajouter une image publique de profil",
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label}/{model_name}/{instance.id}/{uuid:s}{ext}"
                ),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "gif", "png"]
                    )
                ],
                variations={
                    "admin_thumbnail": (100, 100, True),
                    "thumbnail": (200, 200, True),
                },
                verbose_name="image de profil",
            ),
        ),
    ]
