# Generated by Django 3.2.16 on 2022-10-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0017_alter_person_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ("-created",),
                "permissions": [
                    (
                        "select_person",
                        "Peut lister pour sélectionner (dans un Select 2 par exemple)",
                    ),
                    (
                        "export_people",
                        "Peut faire un export des informations des personnes",
                    ),
                    (
                        "crp",
                        "Peut voir et modifier les notes du Comité de Respect des Principes",
                    ),
                ],
                "verbose_name": "personne",
                "verbose_name_plural": "personnes",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="crp",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Champ reservé aux notes du Comité de Respect des Principes concernant cette personne",
                verbose_name="Notes CRP",
            ),
        ),
    ]
