# Generated by Django 3.2.17 on 2023-02-13 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0020_person_location_departement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="public_email",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="L'adresse email à afficher publiquement dans l'application pour cette personne. Si vide, l'adresse email principale de la personne sera utilisée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_with_public_email",
                related_query_name="person_with_public_email",
                to="people.personemail",
                verbose_name="Adresse email publique",
            ),
        ),
    ]
