# Generated by Django 3.2.17 on 2023-02-09 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0020_person_location_departement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="personform",
            name="lien_feuille_externe",
            field=models.URLField(
                blank=True,
                help_text="Une feuille de calcul externe (Google Sheet uniquement pour moment) qui sera mise à jour avec les réponses au formulaire. Attention, cette feuille sera écrasée au fur et à mesure.",
                validators=[
                    django.core.validators.RegexValidator(
                        message="Indiquez-ici l'URL complète vers la feuille Google sheet à modifier. La feuille doit être accessible et modifiable pour toute personne avec le lien.",
                        regex="^https://docs.google.com/spreadsheets/d/(?P<sid>[A-Za-z0-9_-]{40,})/.*[?#&]gid=(?P<gid>[0-9]+)",
                    )
                ],
                verbose_name="Lien vers une feuille de calcul externe",
            ),
        ),
    ]
