# Generated by Django 3.2.17 on 2023-02-15 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0021_personform_lien_feuille_externe"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="public_email",
            field=models.OneToOneField(
                blank=True,
                default=None,
                help_text="L'adresse email à afficher publiquement dans l'application pour cette personne. Si vide, l'adresse email principale de la personne sera utilisée.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person_with_public_email",
                related_query_name="person_with_public_email",
                to="people.personemail",
                verbose_name="Adresse email publique",
            ),
        ),
        migrations.AlterField(
            model_name="personform",
            name="lien_feuille_externe",
            field=models.URLField(
                blank=True,
                help_text="Une feuille de calcul externe à mettre à jour avec les réponses au formulaire.",
                verbose_name="Lien vers une feuille de calcul externe",
            ),
        ),
    ]
