# Generated by Django 3.2.18 on 2023-02-21 09:24

import agir.lib.form_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0022_person_public_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=agir.lib.form_fields.CustomJSONEncoder,
                verbose_name="Autres données",
            ),
        ),
    ]
