# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-29 17:24
from __future__ import unicode_literals

from django.db import migrations
from agir.lib import models as lib_models


class Migration(migrations.Migration):

    dependencies = [("people", "0022_persontag_exported")]

    operations = [
        migrations.AlterField(
            model_name="personform",
            name="confirmation_note",
            field=lib_models.DescriptionField(
                help_text="Note montrée à l'utilisateur une fois le formulaire validé.",
                verbose_name="Note après complétion",
            ),
        ),
        migrations.AlterField(
            model_name="personform",
            name="description",
            field=lib_models.DescriptionField(
                help_text="Description visible en haut de la page de remplissage du formulaire",
                verbose_name="Description",
            ),
        ),
    ]
