# Generated by Django 3.2.18 on 2023-02-28 13:44

import django.core.validators
from django.db import migrations
import dynamic_filenames
import stdimage.models
import stdimage.validators


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0023_alter_person_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="personform",
            name="meta_image",
            field=stdimage.models.StdImageField(
                blank=True,
                force_min_size=False,
                help_text="L'image utilisée lors du partage du lien du formulaire sur les réseaux sociaux. La taille d'image recommandée est de 1200 x 630 px (ratio de 1.9:1).",
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label}/{model_name}/{instance.slug}/{uuid:.8base32}{ext}"
                ),
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ("png", "jpeg", "jpg")
                    ),
                    stdimage.validators.MinSizeValidator(400, 209),
                ],
                variations={},
                verbose_name="Miniature du formulaire",
            ),
        ),
    ]
