# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-06 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0025_auto_20180130_1100")]

    operations = [
        migrations.AlterField(
            model_name="personform",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="forms",
                related_query_name="form",
                to="people.PersonTag",
            ),
        )
    ]
