# Generated by Django 3.2.18 on 2023-05-30 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0017_supportgroup_certification_date"),
        ("people", "0026_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="personqualification",
            name="supportgroup",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="person_qualifications",
                related_query_name="person_qualification",
                to="groups.supportgroup",
                verbose_name="groupe d'action",
            ),
        ),
    ]
