# Generated by Django 3.2.19 on 2023-06-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0027_personqualification_supportgroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personform",
            name="main_question",
            field=models.CharField(
                blank=True,
                help_text="Si rempli, ce champ sera utilisé lorsque plusieurs tags auront été sélectionnés pour permettre à la personne de choisir lequel sera appliqué après la validation du formulaire.",
                max_length=200,
                verbose_name="Question principale",
            ),
        ),
        migrations.AlterField(
            model_name="personform",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Un ou plusieurs tags à ajouter à la personne qui remplit le formulaire. Si un seul tag est sélectionné ou si le champ 'Question principale' est vide, le tag seront automatiquement ajoutés après la validation du formulaire.",
                related_name="forms",
                related_query_name="form",
                to="people.PersonTag",
            ),
        ),
    ]
