# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 16:13
from __future__ import unicode_literals

from django.db import migrations
from agir.people import model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0028_auto_20180411_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mandates',
            field=model_fields.MandatesField(blank=True, default=list, verbose_name='Mandats électoraux'),
        ),
    ]
