# Generated by Django 3.2.19 on 2023-06-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0028_auto_20230615_1759"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="is_2022",
            new_name="is_political_support",
        ),
        migrations.AlterField(
            model_name="person",
            name="is_political_support",
            field=models.BooleanField(default=False, verbose_name="Soutien politique"),
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_insoumise",
        ),
    ]
