# Generated by Django 3.2.19 on 2023-06-05 16:03

from django.db import migrations, models

from django.db.models import Func, F, Value, JSONField, BooleanField
from django.db.models.functions import Cast, Coalesce


def save_legacy_political_support_fields_to_meta(apps, schema):
    Person = apps.get_model("people", "Person")
    Person.objects.update(
        meta=Func(
            F("meta"),
            Value(["political_support"]),
            Cast(
                Func(
                    Value("is_2022"),
                    "is_2022",
                    Value("is_insoumise"),
                    "is_insoumise",
                    function="jsonb_build_object",
                ),
                JSONField(),
            ),
            function="jsonb_set",
        ),
    )


def restore_legacy_political_support_fields_from_meta(apps, schema):
    Person = apps.get_model("people", "Person")
    Person.objects.annotate(
        was_2022=Coalesce(
            Cast("meta__political_support__is_2022", BooleanField()),
            Value(False),
        ),
        was_insoumise=Coalesce(
            Cast("meta__political_support__is_insoumise", BooleanField()),
            Value(False),
        ),
    ).update(
        is_2022=F("was_2022"),
        is_insoumise=F("was_insoumise"),
        meta=Func(
            F("meta"),
            Value(["political_support"]),
            Cast(
                Func(
                    Value("is_political_support"),
                    "is_2022",
                    Value("is_2022"),
                    "was_2022",
                    Value("is_insoumise"),
                    "was_insoumise",
                    function="jsonb_build_object",
                ),
                JSONField(),
            ),
            function="jsonb_set",
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0028_auto_20230615_1759"),
    ]

    operations = [
        migrations.RunPython(
            code=save_legacy_political_support_fields_to_meta,
            reverse_code=restore_legacy_political_support_fields_from_meta,
        ),
        migrations.RenameField(
            model_name="person",
            old_name="is_2022",
            new_name="is_political_support",
        ),
        migrations.AlterField(
            model_name="person",
            name="is_political_support",
            field=models.BooleanField(default=False, verbose_name="Soutien politique"),
        ),
        migrations.RemoveField(
            model_name="person",
            name="is_insoumise",
        ),
    ]
