# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0030_auto_20180420_1031")]

    operations = [
        migrations.AlterField(
            model_name="personform",
            name="end_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de fermeture du formulaire"
            ),
        ),
        migrations.AlterField(
            model_name="personform",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date d'ouverture du formulaire"
            ),
        ),
    ]
