# Generated by Django 3.2.25 on 2024-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0033_auto_20240126_1715"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[("RF", "Reçu fiscal"), ("CP", "Contrat de prêt")],
                max_length=5,
                verbose_name="Type de document",
            ),
        ),
    ]
