# Generated by Django 2.0.6 on 2018-09-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0035_auto_20180719_1655")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="contact_phone_status",
            field=models.CharField(
                choices=[
                    ("U", "Non vérifié"),
                    ("V", "Vérifié"),
                    ("P", "Vérification manuelle en cours"),
                ],
                default="U",
                max_length=1,
                verbose_name="Statut du numéro de téléphone",
            ),
        )
    ]
