# Generated by Django 2.0.6 on 2018-09-06 21:46

import agir.people.models
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [("people", "0036_person_contact_phone_status")]

    operations = [
        migrations.CreateModel(
            name="PersonValidationSMS",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        editable=False, max_length=128, verbose_name="Numéro de mobile"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=agir.people.models.generate_code,
                        editable=False,
                        max_length=8,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS de validation",
                "verbose_name_plural": "SMS de validation",
            },
        )
    ]
