# Generated by Django 2.0.9 on 2018-10-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0041_django2-1'),
        ('people', '0039_person_is_insoumise'),
    ]

    operations = [
    ]
