# Generated by Django 2.1.2 on 2018-10-29 17:23

from django.db import migrations


ADD_INDEX_SQL = """
CREATE UNIQUE INDEX uppercase_email ON people_personemail (upper(address));
"""

REMOVE_INDEX_SQL = """
DROP INDEX uppercase_email;
"""


class Migration(migrations.Migration):

    dependencies = [("people", "0042_merge_20181024_1733")]

    operations = [migrations.RunSQL(sql=ADD_INDEX_SQL, reverse_sql=REMOVE_INDEX_SQL)]
