# Generated by Django 2.1.2 on 2018-11-06 14:04

import agir.people.models
import agir.people.person_forms.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0044_remove_previous_address")]

    operations = [
        migrations.AlterField(
            model_name="personform",
            name="custom_fields",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=agir.people.person_forms.models.default_custom_forms,
                verbose_name="Champs",
            ),
        )
    ]
