# Generated by Django 2.1.7 on 2019-03-12 16:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0050_auto_20190128_1550")]

    operations = [
        migrations.AddField(
            model_name="personform",
            name="config",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name="Configuration"
            ),
        )
    ]
