# Generated by Django 2.1.7 on 2019-04-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0052_auto_20190313_1842")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="contact_phone_status",
            field=models.CharField(
                choices=[
                    ("U", "Non vérifié"),
                    ("V", "Vérifié"),
                    ("P", "En attente de validation manuelle"),
                ],
                default="U",
                help_text="Pour les numéros hors France métropolitaine, merci de les indiquer sous la forme internationale, en les préfixant par '+' et le code du pays.",
                max_length=1,
                verbose_name="Statut du numéro de téléphone",
            ),
        )
    ]
