# Generated by Django 2.2.3 on 2019-07-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0057_auto_20190704_1203")]

    operations = [
        migrations.AlterField(
            model_name="personform",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        )
    ]
