# Generated by Django 2.2.4 on 2019-09-02 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0058_auto_20190709_1500")]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "ordering": ("-created",),
                "permissions": [
                    (
                        "select_person",
                        "Peut lister pour sélectionner (dans un Select 2 par exemple)",
                    )
                ],
                "verbose_name": "personne",
                "verbose_name_plural": "personnes",
            },
        )
    ]
