# Generated by Django 2.2.11 on 2020-03-30 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0061_personform_campaign_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
