# Generated by Django 2.2.14 on 2020-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0064_person_membre_reseau_elus"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="commentaires",
            field=models.TextField(
                blank=True,
                help_text="ATTENTION : en cas de demande d'accès à ses données par la personne concernée par cette fiche, le contenu de ce champ lui sera communiqué. N'indiquez ici que des éléments factuels.",
                verbose_name="Commentaires",
            ),
        ),
    ]
