# Generated by Django 2.2.14 on 2020-07-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0065_person_commentaires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="membre_reseau_elus",
            field=models.CharField(
                choices=[
                    ("I", "Inconnu / Non pertinent"),
                    ("S", "Souhaite faire partie du réseau des élus"),
                    ("O", "Fait partie du réseau des élus"),
                    ("N", "Ne souhaite pas faire partie du réseau des élus"),
                    ("E", "Exclus du réseau"),
                ],
                default="I",
                help_text="Pertinent uniquement si la personne a un ou plusieurs mandats électoraux.",
                max_length=1,
                verbose_name="Membre du réseau des élus",
            ),
        ),
    ]
