# Generated by Django 3.1.2 on 2020-10-21 13:25

import agir.lib.form_fields
import agir.people.person_forms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0067_fix_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="meta",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Autres données"
            ),
        ),
        migrations.AlterField(
            model_name="personform",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Configuration"
            ),
        ),
        migrations.AlterField(
            model_name="personform",
            name="custom_fields",
            field=models.JSONField(
                default=agir.people.person_forms.models.default_custom_forms,
                verbose_name="Champs",
            ),
        ),
        migrations.AlterField(
            model_name="personformsubmission",
            name="data",
            field=models.JSONField(
                default=dict,
                encoder=agir.lib.form_fields.CustomJSONEncoder,
                verbose_name="Données",
            ),
        ),
    ]
