# Generated by Django 3.1.2 on 2020-11-04 16:26

import agir.lib.model_fields
from agir.people.models import Person as CurrentPersonModel
from django.db import migrations, models


def copy_legacyfield(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    for p in Person.objects.filter(subscribed=True).all():
        p.newsletters = [CurrentPersonModel.NEWSLETTER_LFI]
        p.save(update_fields=["newsletters"])


def restore_legacyfield(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    for p in Person.objects.all():
        p.subscribed = CurrentPersonModel.NEWSLETTER_LFI in p.newsletters
        p.save(update_fields=["newsletters"])


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0068_auto_20201021_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_2022",
            field=models.BooleanField(default=False, verbose_name="Soutien 2022"),
        ),
        migrations.AddField(
            model_name="person",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LFI", "Lettre d'information de la France insoumise"),
                        ("2022", "Lettre d'information de"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.RunPython(copy_legacyfield, restore_legacyfield),
    ]
