# Generated by Django 3.1.2 on 2020-11-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0069_newsletter_field"),
    ]

    operations = [
        migrations.RemoveField(model_name="person", name="subscribed",),
    ]
