# Generated by Django 3.1.2 on 2020-11-06 18:08

import agir.lib.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0070_remove_person_subscribed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="is_insoumise",
            field=models.BooleanField(default=False, verbose_name="Insoumis⋅e"),
        ),
        migrations.AlterField(
            model_name="person",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LFI", "Lettre d'information de la France insoumise"),
                        ("2022", "Lettre d'information de"),
                        ("NSP_en_ligne", "NSP en ligne"),
                        ("NSP_chez_moi", "NSP près de chez moi"),
                        ("NSP_programme", "NSP programme"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
