# Generated by Django 3.1.4 on 2020-12-09 15:42

import agir.people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0073_auto_20201126_1519"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="referrer_id",
            field=models.CharField(
                default=agir.people.models.generate_referrer_id,
                max_length=13,
                unique=True,
                verbose_name="Identifiant d'invitation",
            ),
        ),
    ]
