# Generated by Django 3.1.3 on 2021-01-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0074_person_referrer_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="person", name="location_address",),
        migrations.RemoveField(model_name="person", name="nb_id",),
    ]
