# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-09 13:46
from __future__ import unicode_literals

from django.contrib.gis.db.models.fields import PointField
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [("people", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nb_id",
                    models.IntegerField(
                        blank=True,
                        help_text="L'identifiant de la ressource correspondante sur NationBuilder, si importé.",
                        null=True,
                        unique=True,
                        verbose_name="ID sur NationBuilder",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={"verbose_name": "agenda"},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="UUID interne à l'API pour identifier la ressource",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "nb_id",
                    models.IntegerField(
                        blank=True,
                        help_text="L'identifiant de la ressource correspondante sur NationBuilder, si importé.",
                        null=True,
                        unique=True,
                        verbose_name="ID sur NationBuilder",
                    ),
                ),
                (
                    "coordinates",
                    PointField(
                        blank=True,
                        geography=True,
                        null=True,
                        srid=4326,
                        verbose_name="coordonnées",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nom du lieu"
                    ),
                ),
                (
                    "location_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="adresse complète"
                    ),
                ),
                (
                    "location_address1",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="adresse (1ère ligne)"
                    ),
                ),
                (
                    "location_address2",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="adresse (2ème ligne)"
                    ),
                ),
                (
                    "location_city",
                    models.CharField(blank=True, max_length=100, verbose_name="ville"),
                ),
                (
                    "location_zip",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="code postal"
                    ),
                ),
                (
                    "location_state",
                    models.CharField(blank=True, max_length=40, verbose_name="état"),
                ),
                (
                    "location_country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, verbose_name="pays"
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nom du contact"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="adresse email du contact",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        verbose_name="numéro de téléphone du contact",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Le nom du groupe de l'évènement",
                        max_length=255,
                        verbose_name="nom",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Une description de l'évènement, en MarkDown",
                        verbose_name="description",
                    ),
                ),
                (
                    "nb_path",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="NationBuilder path"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="date et heure de début"),
                ),
                ("end_time", models.DateTimeField(verbose_name="date et heure de fin")),
            ],
            options={
                "verbose_name": "évènement",
                "verbose_name_plural": "évènements",
                "ordering": ("-start_time", "-end_time"),
                "permissions": (("every_event", "Peut éditer tous les évènements"),),
            },
        ),
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=50, unique=True, verbose_name="nom"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={"verbose_name": "tag"},
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "guests",
                    models.PositiveIntegerField(
                        default=0, verbose_name="nombre d'invités supplémentaires"
                    ),
                ),
                ("canceled", models.BooleanField(default=False, verbose_name="Annulé")),
                (
                    "event",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="events.Event",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="people.Person",
                    ),
                ),
            ],
            options={"verbose_name": "RSVP", "verbose_name_plural": "RSVP"},
        ),
        migrations.AddField(
            model_name="event",
            name="attendees",
            field=models.ManyToManyField(
                related_name="events", through="events.RSVP", to="people.Person"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="events.Calendar",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organizers",
            field=models.ManyToManyField(
                related_name="organized_events", to="people.Person"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="events.EventTag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="rsvp", unique_together={("event", "person")}
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_time", "end_time"], name="events_even_start_t_0e446b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["nb_path"], name="events_even_nb_path_2e6795_idx"
            ),
        ),
    ]
