# Generated by Django 3.1.6 on 2021-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_objets_initiaux_et_recherche"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventsubtype",
            options={
                "ordering": ["-has_priority"],
                "verbose_name": "Sous-type d'événement",
                "verbose_name_plural": "Sous-types d'événement",
            },
        ),
        migrations.AddField(
            model_name="eventsubtype",
            name="has_priority",
            field=models.BooleanField(
                default=False,
                help_text="Le sous-type d'événement apparaîtra en premier dans la liste des sous-types disponibles, par exemple lors de la création d'un événement.",
                verbose_name="Le sous-type d'événement est prioritaire",
            ),
        ),
    ]
