# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170615_0849'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['end_time'], name='events_even_end_tim_a200ed_idx'),
        ),
    ]
