# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0004_create_basic_calendars")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                help_text="Le nom de l'évènement", max_length=255, verbose_name="nom"
            ),
        )
    ]
