# Generated by Django 3.1.12 on 2021-06-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_recherche_simple_evenements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="for_users",
            field=models.CharField(
                choices=[
                    ("A", "Tous les utilisateurs"),
                    ("I", "Les insoumis⋅es"),
                    ("2", "Les signataires « Nous Sommes Pour ! »"),
                ],
                default="A",
                max_length=1,
                verbose_name="Utilisateur⋅ices de la plateforme concerné⋅es par l'événement",
            ),
        ),
    ]
