# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0006_auto_20170915_1510")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="L'événement doit-il être visible publiquement.",
                verbose_name="publié",
            ),
        )
    ]
