# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0007_event_published")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="contact_hide_phone",
            field=models.BooleanField(
                default=False, verbose_name="Cacher mon numéro de téléphone"
            ),
        )
    ]
