# Generated by Django 3.1.12 on 2021-07-05 08:50
import pytz
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_for_users_all_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="timezone",
            field=models.CharField(
                choices=((name, name) for name in pytz.all_timezones),
                default=timezone.get_default_timezone().zone,
                max_length=255,
                verbose_name="Fuseau horaire",
            ),
        ),
    ]
