# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0009_add_through_model_organizers")]

    operations = [
        migrations.AddField(
            model_name="organizerconfig",
            name="is_creator",
            field=models.BooleanField(
                default=False, verbose_name="Créateur de l'évènement"
            ),
        ),
        migrations.AddField(
            model_name="organizerconfig",
            name="send_notifications",
            field=models.BooleanField(
                default=True, verbose_name="Recevoir les notifications"
            ),
        ),
        migrations.AlterModelTable(name="organizerconfig", table=None),
    ]
