# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_add_options_organizer_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizerconfig',
            old_name='send_notifications',
            new_name='notifications_enabled',
        ),
        migrations.AddField(
            model_name='rsvp',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Recevoir les notifications'),
        ),
    ]
