# Generated by Django 3.1.13 on 2021-10-14 15:35

from django.db import migrations, models


def related_project_type_null_en_chaine_vide(apps, schema):
    EventSubtype = apps.get_model("events", "EventSubtype")

    EventSubtype.objects.filter(related_project_type__isnull=True).update(
        related_project_type=""
    )


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0010_uuid_in_image_filename"),
    ]

    operations = [
        migrations.RunPython(
            code=related_project_type_null_en_chaine_vide,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="eventsubtype",
            name="related_project_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CON", "Conférence de presse"),
                    ("REU", "Réunion publique et meetings"),
                    ("REU-loc", "Réunion publique organisée localement"),
                    ("REU-ora", "Réunion publique avec un orateur national"),
                    ("REU-can", "Réunion publique avec un candidat"),
                    ("REU-mee", "Meeting"),
                    ("DEB", "Débats et conférences"),
                    ("DEB-aso", "Débat organisé par une association"),
                    ("DEB-con", "Conférence"),
                    ("DEB-caf", "Café-débat"),
                    ("DEB-pro", "Projection et débat"),
                    ("MAN", "Manifestations et événements publics"),
                    ("MAN-loc", "Manifestation ou marche organisée localement"),
                    ("MAN-nat", "Manifestation ou marche nationale"),
                    ("MAN-pic", "Pique-nique ou apéro citoyen"),
                    ("MAN-eco", "Écoute collective"),
                    ("MAN-fet", "Fête (auberge espagnole)"),
                    ("MAN-car", "Caravane"),
                    ("ACT", "Autres actions publiques"),
                    ("EVE", "Événements spécifiques"),
                    ("EVE-AMF", "AMFiS d'été"),
                    ("EVE-CON", "Convention"),
                    ("RH", "Dépenses RH mensuelles"),
                ],
                default="",
                max_length=10,
                verbose_name="Type de projet de gestion associé",
            ),
        ),
    ]
