# Generated by Django 3.1.13 on 2021-09-30 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0005_add_subscriptions"),
        ("groups", "0006_uuid_in_image_filename"),
        ("events", "0010_uuid_in_image_filename"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("accepted", "Acceptée"),
                            ("refused", "Refusée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="events.event",
                        verbose_name="Evenement de l'invitation",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="groups.supportgroup",
                        verbose_name="Groupe invité à l'événement",
                    ),
                ),
                (
                    "person_recipient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitation_response",
                        to="people.person",
                        verbose_name="Personne qui répond à l'invitation",
                    ),
                ),
                (
                    "person_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                        verbose_name="Personne qui émet l'invitation",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="invitation",
            constraint=models.UniqueConstraint(
                fields=("event", "group"), name="unique"
            ),
        ),
    ]
