# Generated by Django 3.1.13 on 2021-11-16 14:46

import agir.lib.form_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0012_auto_20211020_1345"),
    ]

    operations = [
        migrations.RenameField(model_name="event", old_name="legal", new_name="meta"),
        migrations.AlterField(
            model_name="event",
            name="meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=agir.lib.form_fields.CustomJSONEncoder,
                verbose_name="Informations supplémentaires.",
            ),
        ),
    ]
