# Generated by Django 3.1.13 on 2021-11-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0008_contact"),
        ("events", "0012_auto_20211020_1345"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="custom_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="people.personform",
            ),
        ),
    ]
