# Generated by Django 3.1.13 on 2021-11-30 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.NUNTIUS_SEGMENT_MODEL),
        ("events", "0013_rename_legal_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="suggestion_segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment des personnes auquel cet événement sera suggéré.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggested_events",
                related_query_name="suggested_event",
                to=settings.NUNTIUS_SEGMENT_MODEL,
                verbose_name="Segment de suggestion",
            ),
        ),
    ]
