# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("events", "0013_calendar_user_contributed")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_html",
            field=models.BooleanField(
                default=False, verbose_name="autoriser le HTML dans la description"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to="events/banners/",
                verbose_name="bannière de l'évènement",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="calendar",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="events.Calendar",
            ),
        ),
    ]
