# Generated by Django 3.1.13 on 2021-12-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0015_eventsubtype_report_person_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="is_editable",
            field=models.BooleanField(
                default=True,
                help_text="Les événements de ce sous-type pourront être modifiés par les organisateur·ices, et non seulement par les administrateur·ices",
                verbose_name="Les événements de ce sous-types seront modifiables",
            ),
        ),
    ]
