# Generated by Django 3.1.14 on 2021-12-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0016_eventsubtype_is_editable"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_time", "end_time", "id"], name="events_datetime_id_index"
            ),
        ),
    ]
