# Generated by Django 3.1.14 on 2022-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0017_create_event_start_end_id_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="attendant_notice",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Note montrée aux participants à un événements et est envoyé dans l'e-mail de confirmation de participation",
                verbose_name="Note pour les participants",
            ),
        ),
    ]
