# Generated by Django 3.2.12 on 2022-03-14 11:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0018_event_attendant_notice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="payment_parameters",
            field=models.JSONField(
                blank=True,
                help_text="\n<p>Doit être un objet JSON qui peut contenir les clés suivantes\xa0:</p>\n<ul>\n<li><strong>pricing</strong>\xa0: un prix fixe en centimes</li>\n<li><strong>free_pricing</strong>\xa0: l'id d'un champ numérique du formulaire associé à l'événement qui sera utilisé \ncomme prix pour l'événement</li>\n<li><strong>mappings</strong>\xa0: Une liste de mappings entre réponses au formulaire et prix correspondant. Chaque \nmapping est un objet JSON avec un champ <em>fields</em> qui liste les champs à utiliser, et le champ <em>mapping</em>\nlui-même.</li>\n<li><strong>payment_modes</strong>\xa0: indique la liste des modes de paiement admissibles pour cet événement.</li>\n<li><strong>admin_payment_modes</strong>\xa0: Idem, mais à utiliser pour les modes de paiement côté admin.</li>\n<li><strong>allow_checks_upto</strong>\xa0: arrête d'accepter les chèques N jours avant l'événement (7 par défaut).</li>\n</ul>\n",
                null=True,
                verbose_name="Paramètres de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="eventsubtype",
            name="required_documents",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("ATT-GRA", "Attestation de gratuité"),
                        ("ATT-CON", "Attestation de concours en nature"),
                        ("ATT-REG", "Attestation de règlement des consommations"),
                        (
                            "ATT-ESP",
                            "Demande d'autorisation d'occupation de l'espace public",
                        ),
                    ],
                    max_length=10,
                ),
                default=list,
                size=None,
                verbose_name="Attestations requises",
            ),
        ),
    ]
