# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 16:10
from __future__ import unicode_literals

import dynamic_filenames
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [("events", "0019_harmonize_image_fields")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                help_text="L'image à utiliser pour l'affichage sur la page, comme miniature dans les listes, et pour le partage sur les réseaux sociaux. Elle doit faire au minimum 1200 pixels de large, et 630 de haut. Préférer un rapport largeur/hauteur de 2 (deux fois plus large que haut)?",
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label}/{model_name}/{instance.id}/banner{ext}"
                ),
                verbose_name="image",
            ),
        )
    ]
