# Generated by Django 3.2.12 on 2022-03-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_auto_20220314_1245"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="location_state",
            new_name="location_country_name",
        ),
    ]
