# Generated by Django 3.2.12 on 2022-03-24 11:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0020_group_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupattendee",
            options={
                "verbose_name": "Groupe participant",
                "verbose_name_plural": "Groupes participants",
            },
        ),
        migrations.AlterModelTable(
            name="groupattendee",
            table="group_attendee",
        ),
    ]
