# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from agir.lib import models as lib_models
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [("events", "0024_auto_20171204_1217")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="image",
            field=stdimage.models.StdImageField(
                blank=True,
                help_text="Vous pouvez ajouter une image de bannière : elle apparaîtra sur la page, et sur les réseaux sociaux en cas de partage. Préférez une image à peu près deux fois plus large que haute. Elle doit faire au minimum 1200 pixels de large et 630 de haut pour une qualité optimale.",
                upload_to=stdimage.utils.UploadToAutoSlugClassNameDir(
                    "name", path="banners"
                ),
                verbose_name="image",
            ),
        )
    ]
