# Generated by Django 3.2.18 on 2023-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0025_eventsubtype_is_acceptable_for_group_certification"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="for_organizer_group_members_only",
            field=models.BooleanField(
                default=False,
                help_text="Seulement les membres des groupes organisateurs pourront rejoindre les événements de ce type",
                verbose_name="Réservé aux membres des groupes organisateurs",
            ),
        ),
    ]
