# Generated by Django 3.2.18 on 2023-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0026_eventsubtype_for_organizer_group_members_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="for_supportgroup_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "Groupe local"),
                    ("B", "Groupe thématique"),
                    ("F", "Groupe fonctionnel"),
                    ("D", "Boucle départementale"),
                ],
                default=None,
                help_text="Seulement les gestionnaires et animateur·ices des groupes du type sélectionné pourront créer des événements de ce type.",
                max_length=1,
                null=True,
                verbose_name="Organisation réservé au type de groupe",
            ),
        ),
    ]
