# Generated by Django 3.2.18 on 2023-04-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0027_eventsubtype_for_supportgroup_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="unauthorized_message",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Cette note sera affichée sur la page de l'événement aux personnes qui n'ont pas le droit de participer à un événement de ce type",
                verbose_name="Note pour les personnes non autorisées",
            ),
        ),
    ]
