# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("events", "0029_auto_20171213_1134")]

    operations = [
        migrations.AlterField(
            model_name="eventimage",
            name="author",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_images",
                to="people.Person",
            ),
        )
    ]
