# Generated by Django 3.2.18 on 2023-04-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0030_auto_20230419_1804"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="is_coorganizable",
            field=models.BooleanField(
                default=True,
                help_text="Les organisateur·ices pourront inviter d'autres groupes d'action à co-organiser les événements de ce type.",
                verbose_name="Co-organisation avec d'autres groupes d'action autorisée",
            ),
        ),
    ]
