# Generated by Django 3.2.19 on 2023-05-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0031_eventsubtype_is_coorganizable"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="lien_feuille_externe",
            field=models.URLField(
                blank=True,
                help_text="Une feuille de calcul externe à mettre à jour avec les participants à l'événement.",
                verbose_name="Lien vers une feuille de calcul externe",
            ),
        ),
    ]
