# Generated by Django 3.2.19 on 2023-06-26 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0028_auto_20230615_1759"),
        ("events", "0032_event_lien_feuille_externe"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="volunteer_application_form",
            field=models.OneToOneField(
                blank=True,
                help_text="Si un formulaire existe, son lien sera affiché sur la page de l'événement et dans les e-mails de confirmation de participation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="volunteer_application_form_event",
                related_query_name="volunteer_application_form_event",
                to="people.personform",
                verbose_name="Formulaire d'appel à volontaires",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="subscription_form",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subscription_form_event",
                related_query_name="subscription_form_event",
                to="people.personform",
                verbose_name="Formulaire d'inscription",
            ),
        ),
    ]
