# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-13 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20180209_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubtype',
            name='icon_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="Nom de l'icône Font Awesome"),
        ),
    ]
