# Generated by Django 3.2.19 on 2023-06-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0018_membership_has_finance_managing_privilege"),
        ("events", "0033_auto_20230626_1129"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="for_supportgroups",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                help_text="Seulement les gestionnaires et animateur·ices des groupes sélectionnés pourront créer des événements de ce type.",
                limit_choices_to={"published": True},
                to="groups.SupportGroup",
                verbose_name="Organisations réservé à certains groupes",
            ),
        ),
    ]
