# Generated by Django 3.2.23 on 2023-11-30 16:48

import agir.lib.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0034_eventsubtype_for_supportgroups"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="emoji",
            field=agir.lib.models.EmojiField(
                blank=True,
                default="",
                help_text="Un emoji à utiliser à la place de l'icône dans certaines situations",
                max_length=1,
                verbose_name="Emoji",
            ),
        ),
    ]
