# Generated by Django 3.2.23 on 2024-01-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0035_eventsubtype_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="online_url",
            field=models.URLField(
                blank=True,
                default="",
                max_length=2000,
                verbose_name="Url de visio-conférence",
            ),
        ),
    ]
