# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 13:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0041_auto_20180427_1525")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="payment_parameters",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, null=True, verbose_name="Paramètres de paiement"
            ),
        )
    ]
