# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0043_event_max_participants")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="allow_guests",
            field=models.BooleanField(
                default=False,
                verbose_name="Autoriser les participant⋅e⋅s à inscrire des invité⋅e⋅s",
            ),
        )
    ]
