# Generated by Django 2.0.5 on 2018-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20180523_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='guests_form_submissions',
            field=models.ManyToManyField(related_name='guest_rsvp', to='people.PersonFormSubmission'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='status',
            field=models.CharField(choices=[('AP', 'En attente du paiement'), ('CO', 'Confirmé'), ('CA', 'Annulé')], default='CO', max_length=2, verbose_name='Statut'),
        ),
    ]
