# Generated by Django 2.0.5 on 2018-06-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_auto_20180523_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimage',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='event_images', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guests_form_submissions',
            field=models.ManyToManyField(related_name='guest_rsvp', to='people.PersonFormSubmission'),
        ),
    ]
