# Generated by Django 2.0.5 on 2018-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_populate_status_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='canceled',
        ),
    ]
