# Generated by Django 2.0.9 on 2018-10-09 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_privileged_only_becoms_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'verbose_name': 'Agenda'},
        ),
        migrations.AddField(
            model_name='calendar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', related_query_name='child', to='events.Calendar'),
        ),
    ]
