# Generated by Django 2.0.9 on 2018-10-24 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0055_eventsubtype_config"),
        ("events", "0055_eventsubtype_allow_external"),
    ]

    operations = []
