# Generated by Django 2.0.9 on 2018-10-24 15:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_merge_20181024_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubtype',
            name='external_help_text',
            field=models.TextField(blank=True, verbose_name="Phrase d'explication pour rejoindre le groupe"),
        ),
        migrations.AlterField(
            model_name='eventsubtype',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Configuration'),
        ),
    ]
