# Generated by Django 2.1.3 on 2018-12-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0057_auto_20181024_1757")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="scanner_category",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="La catégorie que doivent avoir les tickets sur scanner",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="scanner_event",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="L'ID de l'évènement sur le logiciel de tickets",
            ),
        ),
    ]
