# Generated by Django 2.1.4 on 2018-12-19 16:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0059_auto_20181212_1529")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="legal",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                null=True,
                verbose_name="Informations juridiques",
            ),
        )
    ]
