# Generated by Django 2.1.4 on 2018-12-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0059_auto_20181212_1529")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("A", "Caché"),
                    ("O", "Visible par les organisateurs"),
                    ("P", "Public"),
                ],
                default="P",
                max_length=1,
                verbose_name="Visibilité",
            ),
        )
    ]
