# Generated by Django 2.1.4 on 2018-12-20 17:47

from django.db import migrations

from agir.events.models import Event as EventClass


def published_to_visibility(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for e in Event.objects.filter(published=False):
        e.visibility = EventClass.VISIBILITY_ADMIN
        e.save()


def visibility_to_published(apps, schema_editor):
    Event = apps.get_model("events", "Event")
    for e in Event.objects.filter(
        visibility__in=[EventClass.VISIBILITY_ADMIN, EventClass.VISIBILITY_ORGANIZER]
    ):
        e.published = False
        e.save()


class Migration(migrations.Migration):

    dependencies = [("events", "0060_event_visibility")]
    operations = [
        migrations.RunPython(published_to_visibility, visibility_to_published)
    ]
