# Generated by Django 2.1.4 on 2018-12-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0061_visibility_from_published")]

    operations = [migrations.RemoveField(model_name="event", name="published")]
