# Generated by Django 2.1.4 on 2018-12-21 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0060_event_legal"),
        ("events", "0062_remove_event_published"),
    ]

    operations = []
