# Generated by Django 2.1.5 on 2019-01-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0065_auto_20190114_1551")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="report_summary_sent",
            field=models.BooleanField(
                default=False, verbose_name="Le mail de compte-rendu a été envoyé"
            ),
        )
    ]
