# Generated by Django 2.1.5 on 2019-02-05 17:07

import agir.lib.form_fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0067_auto_20190128_1550")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="legal",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                encoder=agir.lib.form_fields.CustomJSONEncoder,
                null=True,
                verbose_name="Informations juridiques",
            ),
        )
    ]
