# Generated by Django 2.1.7 on 2019-03-12 12:57

import agir.lib.models
from django.db import migrations
import dynamic_filenames
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [("events", "0068_auto_20190205_1807")]

    operations = [
        migrations.AddField(
            model_name="eventsubtype",
            name="default_description",
            field=agir.lib.models.DescriptionField(
                blank=True,
                help_text="La description par défaut pour les évènements de ce sous-type.",
                verbose_name="description par défaut",
            ),
        ),
        migrations.AddField(
            model_name="eventsubtype",
            name="default_image",
            field=stdimage.models.StdImageField(
                blank=True,
                help_text="L'image associée par défaut à un évènement de ce sous-type.",
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="{app_label}/{model_name}/{instance.id}/banner{ext}"
                ),
                verbose_name="image par défaut",
            ),
        ),
    ]
