# Generated by Django 2.1.7 on 2019-03-13 17:42

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [("events", "0069_auto_20190312_1357")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="location_country",
            field=django_countries.fields.CountryField(
                blank=True, default="FR", max_length=2, verbose_name="pays"
            ),
        )
    ]
