# Generated by Django 2.2 on 2019-05-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0072_auto_20190510_1718")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participation_template",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Template pour la page de participation",
            ),
        )
    ]
