# Generated by Django 2.2.3 on 2019-08-04 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("events", "0075_recherche_evenement_plein_texte")]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="subscription_form",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="people.PersonForm",
            ),
        ),
        migrations.AlterField(
            model_name="identifiedguest",
            name="submission",
            field=models.OneToOneField(
                db_column="personformsubmission_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rsvp_guest",
                to="people.PersonFormSubmission",
            ),
        ),
    ]
