# Generated by Django 2.2.3 on 2019-08-20 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("events", "0076_auto_20190804_1831")]

    operations = [
        migrations.AlterField(
            model_name="identifiedguest",
            name="rsvp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identified_guests",
                to="events.RSVP",
            ),
        )
    ]
