# Generated by Django 2.2.6 on 2019-10-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("events", "0077_auto_20190820_1233")]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="Calendrier archivé"),
        )
    ]
