# Generated by Django 2.2.8 on 2019-12-16 15:25

import agir.lib.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("events", "0078_calendar_archived")]

    operations = [
        migrations.AddField(
            model_name="event",
            name="facebook",
            field=agir.lib.model_fields.FacebookEventField(
                blank=True,
                max_length=20,
                verbose_name="Événement correspondant sur Facebook",
            ),
        )
    ]
