# Generated by Django 2.2.14 on 2020-07-01 14:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0082_auto_20200205_1215"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendaritem",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AlterField(
            model_name="calendaritem",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AlterField(
            model_name="eventimage",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AlterField(
            model_name="eventsubtype",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AlterField(
            model_name="eventsubtype",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AlterField(
            model_name="identifiedguest",
            name="rsvp",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identified_guests",
                to="events.RSVP",
            ),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AlterField(
            model_name="rsvp",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
    ]
