# Generated by Django 3.1.3 on 2020-12-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0088_auto_20201208_1807"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventsubtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("G", "Réunion de groupe"),
                    ("M", "Événement public"),
                    ("A", "Action publique"),
                    ("O", "Autre"),
                ],
                max_length=1,
                verbose_name="Type d'événement",
            ),
        ),
    ]
