# Generated by Django 3.1.3 on 2021-01-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0089_auto_20201210_1211"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="event", name="events_nb_path_index",),
        migrations.RemoveField(model_name="calendar", name="nb_id",),
        migrations.RemoveField(model_name="event", name="location_address",),
        migrations.RemoveField(model_name="event", name="nb_id",),
        migrations.RemoveField(model_name="event", name="nb_path",),
    ]
