export default {
  search: "/recherche",
  personalInformation: "/profil/identite/",
  contactConfiguration: "/profil/contact/",
  createGroup: "/groupes/creer/",
  groupsMap: "/carte/groupes/",
  eventsMap: "/carte/evenements/",
  donations: "/dons/",
  lafranceinsoumise: {
    home: "https://lafranceinsoumise.fr",
    groupMapPage: "https://lafranceinsoumise.fr/groupes-action/carte-groupes/",
    eventMapPage:
      "https://lafranceinsoumise.fr/groupes-action/les-evenements-locaux/",
    thematicTeams: "/equipes-thematiques/",
  },
  programme: "https://melenchon2022.fr/programme/",
  agenda: "https://melenchon2022.fr/agenda/",
  noussommespour: { home: "https://noussommespour.fr" },
  jlmBlog: "https://melenchon.fr",
  linsoumission: "https://linsoumission.fr",
  feedbackForm: "https://actionpopulaire.fr/formulaires/votre-avis/",
  help: "https://infos.actionpopulaire.fr",
  contact: "https://infos.actionpopulaire.fr/contact/",
  legal: "https://infos.actionpopulaire.fr/mentions-legales/",
  nspReferral: "/nsp/referral/",
  newGroupHelp: "https://infos.actionpopulaire.fr/groupes/nouvelle-equipe/",
  groupTransferHelp: "https://infos.actionpopulaire.fr/nombre-ideal-division/",
  charteEquipes:
    "https://lafranceinsoumise.fr/groupes-appui/charte-groupes-dappui-de-france-insoumise/",
  facebookLogin: "/connexion/social/login/facebook/",
};
