# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_id', models.IntegerField(null=True, unique=True, verbose_name='identifiant sur NationBuilder')),
                ('label', models.CharField(max_length=30, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'agenda',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nb_id', models.IntegerField(null=True, unique=True, verbose_name='identifiant sur NationBuilder')),
                ('coordinates_lat', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='latitude géographique')),
                ('coordinates_lon', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='longitude géographique')),
                ('location_name', models.CharField(blank=True, max_length=255, verbose_name='nom du lieu')),
                ('location_address', models.CharField(blank=True, max_length=255, verbose_name='adresse complète')),
                ('location_address1', models.CharField(blank=True, max_length=100, verbose_name='adresse (1ère ligne)')),
                ('location_address2', models.CharField(blank=True, max_length=100, verbose_name='adresse (2ème ligne)')),
                ('location_city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('location_zip', models.CharField(blank=True, max_length=20, verbose_name='code postal')),
                ('location_state', models.CharField(blank=True, max_length=40, verbose_name='état')),
                ('location_country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='pays')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='nom du contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='adresse email du contact')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='numéro de téléphone du contact')),
                ('name', models.CharField(help_text="Le nom du groupe de l'événement", max_length=255, verbose_name='nom')),
                ('description', models.TextField(blank=True, help_text="Une description de l'événement, en MarkDown", verbose_name='description')),
                ('nb_path', models.CharField(blank=True, max_length=255, verbose_name='NationBuilder path')),
                ('start_time', models.DateTimeField(verbose_name='date et heure de début')),
                ('end_time', models.DateTimeField(verbose_name='date et heure de fin')),
            ],
            options={
                'verbose_name': 'événement',
                'verbose_name_plural': 'événements',
            },
        ),
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, unique=True, verbose_name='nom')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tag',
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests', models.PositiveIntegerField(default=0, verbose_name="nombre d'invités supplémentaires")),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.Event')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVP',
            },
        ),
    ]
