# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20170413_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together=set([('person', 'event')]),
        ),
    ]
