# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20170414_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_time', 'end_time'), 'verbose_name': 'événement', 'verbose_name_plural': 'événements'},
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(related_name='events', through='events.RSVP', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='nb_id',
            field=models.IntegerField(help_text="L'identifiant de la ressource correspondante sur NationBuilder, si importé.", null=True, unique=True, verbose_name='ID sur NationBuilder'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text="UUID interne à l'API pour identifier la ressource", primary_key=True, serialize=False, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nb_id',
            field=models.IntegerField(help_text="L'identifiant de la ressource correspondante sur NationBuilder, si importé.", null=True, unique=True, verbose_name='ID sur NationBuilder'),
        ),
    ]
