# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170503_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='nb_id',
            field=models.IntegerField(blank=True, help_text="L'identifiant de la ressource correspondante sur NationBuilder, si importé.", null=True, unique=True, verbose_name='ID sur NationBuilder'),
        ),
        migrations.AlterField(
            model_name='event',
            name='coordinates_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude géographique'),
        ),
        migrations.AlterField(
            model_name='event',
            name='coordinates_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude géographique'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nb_id',
            field=models.IntegerField(blank=True, help_text="L'identifiant de la ressource correspondante sur NationBuilder, si importé.", null=True, unique=True, verbose_name='ID sur NationBuilder'),
        ),
    ]
