# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20170419_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_time', 'end_time'), 'permissions': (('every_event', 'Peut éditer tous les événements'),), 'verbose_name': 'événement', 'verbose_name_plural': 'événements'},
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
