# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20170510_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-start_time', '-end_time'), 'permissions': (('every_event', 'Peut éditer tous les événements'),), 'verbose_name': 'événement', 'verbose_name_plural': 'événements'},
        ),
        migrations.AlterModelOptions(
            name='rsvp',
            options={'permissions': (('view_rsvp', 'Peut afficher les RSVPs'),), 'verbose_name': 'RSVP', 'verbose_name_plural': 'RSVP'},
        ),
        migrations.RemoveIndex(
            model_name='rsvp',
            name='events_rsvp_event_i_4e1eef_idx',
        ),
    ]
