# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20170518_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
    ]
