# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_rsvp_canceled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='event',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='people.Person'),
        ),
    ]
