# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20170529_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='eventtag',
            name='label',
            field=models.CharField(max_length=50, unique=True, verbose_name='nom'),
        ),
    ]
