# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:11
from __future__ import unicode_literals

from django.db import migrations
import events.models
import lib.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_change_image_attrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=lib.models.DescriptionField(blank=True, help_text='Une description, en MarkDown', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=events.models.CustomDateTimeField(verbose_name='date et heure de fin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=events.models.CustomDateTimeField(verbose_name='date et heure de début'),
        ),
    ]
