# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_calendars_many_to_many'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendaritem',
            options={'verbose_name': 'Élément de calendrier'},
        ),
        migrations.AlterField(
            model_name='event',
            name='subtype',
            field=models.ForeignKey(default=events.models.get_default_subtype, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.EventSubtype', verbose_name='Sous-type'),
        ),
    ]
