# Generated by Django 2.2.11 on 2020-03-27 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0061_personform_campaign_template"),
        ("elus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandatmunicipal",
            name="email_officiel",
            field=models.ForeignKey(
                help_text="L'adresse avec laquelle contacter l'élu pour des questions officielles",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.PersonEmail",
                verbose_name="Adresse email officielle",
            ),
        ),
    ]
