# Generated by Django 2.2.11 on 2020-04-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandatmunicipal",
            name="reseau",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INS", "Membre du réseau des élus"),
                    ("DEM", "Souhaite faire partie du réseau des élus"),
                    ("NON", "Ne souhaite pas faire parti du réseau des élus"),
                ],
                max_length=3,
                verbose_name="Réseau des élus",
            ),
        ),
    ]
