# Generated by Django 2.2.12 on 2020-04-07 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_france", "0006_search"),
        ("elus", "0003_auto_20200406_1222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Person",
                verbose_name="Élu",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="reseau",
            field=models.CharField(
                choices=[
                    ("INC", "Statut à vérifier"),
                    ("INS", "Membre du réseau des élus"),
                    ("DEM", "Souhaite faire partie du réseau des élus"),
                    ("NON", "Ne souhaite pas faire parti du réseau des élus"),
                ],
                default="INC",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mandatmunicipal",
            unique_together={("commune", "person")},
        ),
    ]
