# Generated by Django 2.2.12 on 2020-04-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0004_auto_20200407_1716"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="communautaire",
            field=models.CharField(
                choices=[
                    ("NON", "Pas de mandat communautaire"),
                    ("MAJ", "Délégué⋅e majoritaire"),
                    ("OPP", "Délégué⋅e minoritaire"),
                    ("PRE", "Président"),
                    ("VPR", "Vice-Président"),
                ],
                default="NON",
                max_length=3,
                verbose_name="Élu EPCI",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="mandat",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MAJ", "Conseiller⋅e municipal majoritaire"),
                    ("OPP", "Conseiller⋅e municipal minoritaire"),
                    ("MAI", "Maire"),
                    ("ADJ", "Adjoint⋅e au maire"),
                    ("DEL", "Conseiller⋅e municipal délégué"),
                    ("MDA", "Maire d'une commune déléguée ou associée"),
                ],
                max_length=3,
                verbose_name="Type de mandat",
            ),
        ),
    ]
