# Generated by Django 2.2.14 on 2020-07-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0006_departements_regions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mandatdepartemental",
            old_name="delegations_municipales",
            new_name="delegations",
        ),
        migrations.RenameField(
            model_name="mandatmunicipal",
            old_name="delegations_municipales",
            new_name="delegations",
        ),
        migrations.RenameField(
            model_name="mandatregional",
            old_name="delegations_municipales",
            new_name="delegations",
        ),
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="debut",
            field=models.DateField(verbose_name="Date de début du mandat"),
        ),
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="fin",
            field=models.DateField(
                help_text="Date légale si dans le futur, date effective si dans le passé.",
                verbose_name="Date de fin du mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="debut",
            field=models.DateField(verbose_name="Date de début du mandat"),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="fin",
            field=models.DateField(
                help_text="Date légale si dans le futur, date effective si dans le passé.",
                verbose_name="Date de fin du mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatregional",
            name="debut",
            field=models.DateField(verbose_name="Date de début du mandat"),
        ),
        migrations.AlterField(
            model_name="mandatregional",
            name="fin",
            field=models.DateField(
                help_text="Date légale si dans le futur, date effective si dans le passé.",
                verbose_name="Date de fin du mandat",
            ),
        ),
    ]
