# Generated by Django 2.2.14 on 2020-07-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0009_auto_20200708_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="mandat",
            field=models.CharField(
                choices=[
                    ("INC", "Situation au conseil inconnue"),
                    ("MAJ", "Conseiller⋅e majoritaire"),
                    ("OPP", "Conseiller⋅e minoritaire"),
                    ("PRE", "Président du conseil"),
                    ("VPR", "Vice-Président"),
                ],
                default="INC",
                max_length=3,
                verbose_name="Type de mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="statut",
            field=models.CharField(
                choices=[
                    ("INC", "Mandat à vérifier (ajouté côté admin)"),
                    ("DEM", "Mandat à vérifier (ajouté par la personne elle-même)"),
                    ("IMP", "Importé par une opération automatique"),
                    ("INS", "Mandat vérifié"),
                ],
                default="INC",
                help_text="Indique la qualité de l'information sur cet⋅te élu⋅e, indépendamment des questions politiques et de son appartenance au réseau des élus. Une valeur « Vérifié » signifie que : 1) il a été vérifié que le mandat existe réellement et 2) le compte éventuellement associé appartient bien à la personne élue.",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="mandat",
            field=models.CharField(
                choices=[
                    ("INC", "Situation au conseil inconnue"),
                    ("MAJ", "Conseiller⋅e municipal majoritaire"),
                    ("OPP", "Conseiller⋅e municipal minoritaire"),
                    ("MAI", "Maire"),
                    ("ADJ", "Adjoint⋅e au maire"),
                    ("DEL", "Conseiller⋅e municipal délégué"),
                    ("MDA", "Maire d'une commune déléguée ou associée"),
                ],
                default="INC",
                max_length=3,
                verbose_name="Type de mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="statut",
            field=models.CharField(
                choices=[
                    ("INC", "Mandat à vérifier (ajouté côté admin)"),
                    ("DEM", "Mandat à vérifier (ajouté par la personne elle-même)"),
                    ("IMP", "Importé par une opération automatique"),
                    ("INS", "Mandat vérifié"),
                ],
                default="INC",
                help_text="Indique la qualité de l'information sur cet⋅te élu⋅e, indépendamment des questions politiques et de son appartenance au réseau des élus. Une valeur « Vérifié » signifie que : 1) il a été vérifié que le mandat existe réellement et 2) le compte éventuellement associé appartient bien à la personne élue.",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="mandatregional",
            name="mandat",
            field=models.CharField(
                choices=[
                    ("INC", "Situation au conseil inconnue"),
                    ("MAJ", "Conseiller⋅e majoritaire"),
                    ("OPP", "Conseiller⋅e minoritaire"),
                    ("PRE", "Président du conseil"),
                    ("VPR", "Vice-Président"),
                ],
                default="INC",
                max_length=3,
                verbose_name="Type de mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatregional",
            name="statut",
            field=models.CharField(
                choices=[
                    ("INC", "Mandat à vérifier (ajouté côté admin)"),
                    ("DEM", "Mandat à vérifier (ajouté par la personne elle-même)"),
                    ("IMP", "Importé par une opération automatique"),
                    ("INS", "Mandat vérifié"),
                ],
                default="INC",
                help_text="Indique la qualité de l'information sur cet⋅te élu⋅e, indépendamment des questions politiques et de son appartenance au réseau des élus. Une valeur « Vérifié » signifie que : 1) il a été vérifié que le mandat existe réellement et 2) le compte éventuellement associé appartient bien à la personne élue.",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
    ]
