# Generated by Django 2.2.14 on 2020-07-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0010_auto_20200710_1132"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="mandat",
            field=models.CharField(
                choices=[
                    ("INC", "Situation au conseil inconnue"),
                    ("MAJ", "Conseiller⋅e municipal⋅e majoritaire"),
                    ("OPP", "Conseiller⋅e municipal⋅e minoritaire"),
                    ("MAI", "Maire"),
                    ("ADJ", "Adjoint⋅e au maire"),
                    ("MDA", "Maire d'une commune déléguée ou associée"),
                ],
                default="INC",
                max_length=3,
                verbose_name="Type de mandat",
            ),
        ),
    ]
