# Generated by Django 2.2.16 on 2020-10-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0013_auto_20200814_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandats_departementaux",
                related_query_name="mandat_departemental",
                to="people.Person",
                verbose_name="Élu",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandats_municipaux",
                related_query_name="mandat_municipal",
                to="people.Person",
                verbose_name="Élu",
            ),
        ),
        migrations.AlterField(
            model_name="mandatregional",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mandats_regionaux",
                related_query_name="mandat_regional",
                to="people.Person",
                verbose_name="Élu",
            ),
        ),
    ]
