# Generated by Django 3.1.2 on 2020-11-16 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_france", "0013_cantons"),
        ("elus", "0014_auto_20201005_1552"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="conseil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_france.collectivitedepartementale",
                verbose_name="Conseil départemental (ou de métropole)",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="conseil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_france.commune",
                verbose_name="Commune",
            ),
        ),
        migrations.AlterField(
            model_name="mandatregional",
            name="conseil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data_france.collectiviteregionale",
                verbose_name="Conseil régional (ou de collectivité unique)",
            ),
        ),
    ]
