# Generated by Django 3.1.6 on 2021-02-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0017_auto_20210121_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="mandat",
            field=models.CharField(
                choices=[
                    ("INC", "Situation au conseil inconnue"),
                    ("MAJ", "Conseiller⋅e majoritaire"),
                    ("OPP", "Conseiller⋅e minoritaire"),
                    ("PRE", "Président⋅e"),
                    ("VPR", "Vice-Président⋅e"),
                ],
                default="INC",
                max_length=3,
                verbose_name="Type de mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="statut",
            field=models.CharField(
                choices=[
                    ("INC", "Personne à contacter"),
                    ("DEM", "Mandat ajouté par la personne via son profil"),
                    ("IMP", "Importé par une opération automatique"),
                    ("FXP", "Faux-positif ou fausse déclaration"),
                    ("INS", "Mandat vérifié et confirmé"),
                ],
                default="INC",
                help_text="Indique la qualité de l'information sur cet⋅te élu⋅e, indépendamment des questions politiques et de son appartenance au réseau des élus. Une valeur « Vérifié » signifie que : 1) il a été vérifié que le mandat existe réellement et 2) le compte éventuellement associé appartient bien à la personne élue.",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="statut",
            field=models.CharField(
                choices=[
                    ("INC", "Personne à contacter"),
                    ("DEM", "Mandat ajouté par la personne via son profil"),
                    ("IMP", "Importé par une opération automatique"),
                    ("FXP", "Faux-positif ou fausse déclaration"),
                    ("INS", "Mandat vérifié et confirmé"),
                ],
                default="INC",
                help_text="Indique la qualité de l'information sur cet⋅te élu⋅e, indépendamment des questions politiques et de son appartenance au réseau des élus. Une valeur « Vérifié » signifie que : 1) il a été vérifié que le mandat existe réellement et 2) le compte éventuellement associé appartient bien à la personne élue.",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="mandatregional",
            name="statut",
            field=models.CharField(
                choices=[
                    ("INC", "Personne à contacter"),
                    ("DEM", "Mandat ajouté par la personne via son profil"),
                    ("IMP", "Importé par une opération automatique"),
                    ("FXP", "Faux-positif ou fausse déclaration"),
                    ("INS", "Mandat vérifié et confirmé"),
                ],
                default="INC",
                help_text="Indique la qualité de l'information sur cet⋅te élu⋅e, indépendamment des questions politiques et de son appartenance au réseau des élus. Une valeur « Vérifié » signifie que : 1) il a été vérifié que le mandat existe réellement et 2) le compte éventuellement associé appartient bien à la personne élue.",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
    ]
