# Generated by Django 3.1.7 on 2021-03-23 16:12

from django.db import migrations, models
import django.db.models.deletion
import dynamic_filenames


class Migration(migrations.Migration):
    dependencies = [
        ("data_france", "0020_elumunicipal_parrainage2017"),
        ("elus", "0019_auto_20210316_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rechercheparrainagemaire",
            name="elu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recherches_parrainages",
                related_query_name="rechercher_parrainage",
                to="data_france.elumunicipal",
            ),
        ),
        migrations.AlterField(
            model_name="rechercheparrainagemaire",
            name="formulaire",
            field=models.FileField(
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="elus/parrainages/{uuid:.30base32}{ext}"
                ),
                verbose_name="Formulaire de promesse signé",
            ),
        ),
        migrations.AlterField(
            model_name="rechercheparrainagemaire",
            name="statut",
            field=models.IntegerField(
                choices=[
                    (1, "En cours"),
                    (5, "Recherche annulée"),
                    (2, "S'engage à parrainer"),
                    (4, "Refuse de parrainer"),
                    (6, "Pas encore décidé"),
                    (7, "S'est engagé envers un autre candidat"),
                    (3, "Promesse reçue et validée"),
                ],
                default=1,
            ),
        ),
    ]
