# Generated by Django 3.1.11 on 2021-05-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_france", "0020_elumunicipal_parrainage2017"),
        ("people", "0004_display_name_and_image"),
        ("elus", "0020_auto_20210323_1712"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rechercheparrainagemaire",
            name="elu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recherches_parrainages",
                related_query_name="rechercher_parrainage",
                to="data_france.elumunicipal",
                verbose_name="Élu⋅e parrain",
            ),
        ),
        migrations.AlterField(
            model_name="rechercheparrainagemaire",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.person",
                verbose_name="Démarcheur⋅se",
            ),
        ),
    ]
