# Generated by Django 3.1.12 on 2021-06-11 08:38
import datetime

import django.contrib.postgres.fields.ranges
from django.db import migrations
import psycopg2.extras


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0022_mandatconsulaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatconsulaire",
            name="dates",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                default=psycopg2.extras.DateRange(
                    datetime.date(2021, 6, 1), datetime.date(2027, 5, 31), "[)"
                ),
                help_text="La date de fin correspond à la date théorique de fin du mandat si elle est dans le futur et à la date effective sinon.",
                verbose_name="Début et fin du mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatdepartemental",
            name="dates",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                default=psycopg2.extras.DateRange(
                    datetime.date(2015, 3, 29), datetime.date(2021, 3, 31), "[)"
                ),
                help_text="La date de fin correspond à la date théorique de fin du mandat si elle est dans le futur et à la date effective sinon.",
                verbose_name="Début et fin du mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatmunicipal",
            name="dates",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                default=psycopg2.extras.DateRange(
                    datetime.date(2020, 6, 28), datetime.date(2026, 3, 31), "[)"
                ),
                help_text="La date de fin correspond à la date théorique de fin du mandat si elle est dans le futur et à la date effective sinon.",
                verbose_name="Début et fin du mandat",
            ),
        ),
        migrations.AlterField(
            model_name="mandatregional",
            name="dates",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                default=psycopg2.extras.DateRange(
                    datetime.date(2015, 12, 13), datetime.date(2021, 3, 31), "[)"
                ),
                help_text="La date de fin correspond à la date théorique de fin du mandat si elle est dans le futur et à la date effective sinon.",
                verbose_name="Début et fin du mandat",
            ),
        ),
    ]
