# Generated by Django 3.1.13 on 2021-07-26 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("data_france", "0029_deputes_europeens"),
        ("elus", "0027_auto_20210721_1851"),
    ]

    operations = [
        migrations.AddField(
            model_name="mandatregional",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                help_text="La fiche correspondant à cet élu dans le Répertoire National des Élus",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="elus",
                related_query_name="elu",
                to="data_france.eluregional",
                verbose_name="Référence dans le RNE",
            ),
        ),
    ]
