# Generated by Django 3.1.13 on 2021-07-26 13:52

import datetime

import psycopg2.extras
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
from django.db import migrations, models

import agir.elus.models


class Migration(migrations.Migration):
    dependencies = [
        ("data_france", "0029_deputes_europeens"),
        ("people", "0005_add_subscriptions"),
        ("elus", "0028_mandatregional_reference"),
    ]

    operations = [
        migrations.CreateModel(
            name="MandatDeputeEuropeen",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dates",
                    django.contrib.postgres.fields.ranges.DateRangeField(
                        default=psycopg2.extras.DateRange(
                            datetime.date(2019, 6, 1), datetime.date(2024, 5, 31), "[)"
                        ),
                        help_text="La date de fin correspond à la date théorique de fin du mandat si elle est dans le futur et à la date effective sinon.",
                        verbose_name="Début et fin du mandat",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("INC", "Personne à contacter"),
                            ("DEM", "Mandat ajouté par la personne via son profil"),
                            ("IMP", "Importé par une opération automatique"),
                            ("FXP", "Faux-positif ou fausse déclaration"),
                            ("INS", "Mandat vérifié et confirmé"),
                        ],
                        default="INC",
                        help_text="Indique la qualité de l'information sur cet⋅te élu⋅e, indépendamment des questions politiques et de son appartenance au réseau des élus. Une valeur « Vérifié » signifie que : 1) il a été vérifié que le mandat existe réellement et 2) le compte éventuellement associé appartient bien à la personne élue.",
                        max_length=3,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "email_officiel",
                    models.ForeignKey(
                        help_text="L'adresse avec laquelle contacter l'élu pour des questions officielles",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people.personemail",
                        verbose_name="Adresse email officielle",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mandats_deputes_europeens",
                        related_query_name="mandat_depute_depute_europeen",
                        to="people.person",
                        verbose_name="Élu",
                    ),
                ),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        help_text="La fiche correspondant à cet élu dans le répertoire national des élus",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elus",
                        related_query_name="elu",
                        to="data_france.deputeeuropeen",
                        verbose_name="Référence dans les données du RNE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mandat de député⋅e européen⋅ne",
                "verbose_name_plural": "Mandats de député⋅e européen⋅ne",
                "ordering": ("person",),
            },
            bases=(
                agir.elus.models.mandats.UniqueWithinDates,
                agir.elus.models.mandats.MandatHistoryMixin,
                models.Model,
            ),
        ),
    ]
