# Generated by Django 3.1.14 on 2022-01-27 13:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0033_autorisation_candidature_scrutin"),
    ]

    operations = [
        migrations.AddField(
            model_name="rechercheparrainage",
            name="adresse_postale",
            field=models.TextField(
                blank=True,
                help_text="Indiquez l'adresse postale complète (à l'exception du nom de la personne), exactement comme vous l'indiqueriez sur une enveloppe.",
                verbose_name="Adresse postale complète",
            ),
        ),
        migrations.AddField(
            model_name="rechercheparrainage",
            name="commentaires_admin",
            field=models.TextField(
                blank=True,
                help_text="Tout commentaire additionnel sur le parrainage. Ces  commentaires ne sont pas visibles par la personne qui a effectué la démarche.",
                verbose_name="Commentaires supplémentaires",
            ),
        ),
        migrations.AddField(
            model_name="rechercheparrainage",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Adresse email à utiliser pour contacter cet élu en lien avec ce parrainage.",
                max_length=254,
                verbose_name="Adresse email",
            ),
        ),
        migrations.AddField(
            model_name="rechercheparrainage",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Numéro à utiliser pour contacter cet élu en lien avec ce parrainage.",
                max_length=128,
                region=None,
                verbose_name="Numéro de téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="rechercheparrainage",
            name="commentaires",
            field=models.TextField(
                blank=True,
                help_text="Commentaires saisis par la personne à l'origine de la démarche. Si vous les modifiez, ils seront visibles par la personne qui a effectué la démarche.",
                verbose_name="Commentaires",
            ),
        ),
    ]
