# Generated by Django 3.1.14 on 2022-02-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0034_nouveaux_champs_recherche_parrainage"),
    ]

    operations = [
        migrations.AddField(
            model_name="rechercheparrainage",
            name="parrainage",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Si l'élu a déjà envoyé son parrainage au Conseil Constitutionnel, pour qui l'a-t-il fait ?",
                max_length=250,
                verbose_name="Parrainage effectif en 2022",
            ),
        ),
    ]
