# Generated by Django 3.1.14 on 2022-02-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0035_rechercheparrainage_parrainage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rechercheparrainage",
            name="statut",
            field=models.IntegerField(
                choices=[
                    (1, "En cours"),
                    (5, "Recherche annulée"),
                    (2, "S'engage à parrainer"),
                    (4, "Refuse de parrainer"),
                    (6, "Pas encore décidé"),
                    (7, "S'est engagé envers un autre candidat"),
                    (3, "Promesse reçue et validée"),
                    (8, "Parrainage confirmé par le CC"),
                    (9, "A parrainé un autre candidat"),
                ],
                default=1,
            ),
        ),
    ]
