# Generated by Django 3.2.12 on 2022-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elus", "0036_parrainage_statut_cc"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidature",
            name="ailleurs",
            field=models.CharField(
                blank=True,
                choices=[
                    ("non", "Non"),
                    ("département", "Dans le même département"),
                    ("région", "Dans la même région"),
                ],
                max_length=15,
                verbose_name="Accepte de candidater ailleurs",
            ),
        ),
        migrations.AlterField(
            model_name="rechercheparrainage",
            name="statut",
            field=models.IntegerField(
                choices=[
                    (1, "En cours"),
                    (5, "Recherche annulée"),
                    (2, "S'engage à parrainer"),
                    (4, "Refuse de parrainer"),
                    (6, "Pas encore décidé"),
                    (7, "S'est engagé envers un autre candidat"),
                    (3, "Promesse reçue et validée"),
                    (8, "Parrainage confirmé par le CC"),
                    (9, "A parrainé un autre candidat"),
                    (10, "Revenu sur son engagement"),
                ],
                default=1,
            ),
        ),
    ]
