# Generated by Django 3.2.14 on 2022-10-16 00:30

import datetime
import django.contrib.postgres.fields.ranges
from django.db import migrations
import psycopg2.extras


class Migration(migrations.Migration):

    dependencies = [
        ("elus", "0037_auto_20220407_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mandatdepute",
            name="dates",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                default=psycopg2.extras.DateRange(
                    datetime.date(2022, 6, 22), datetime.date(2027, 6, 21), "[)"
                ),
                help_text="La date de fin correspond à la date théorique de fin du mandat si elle est dans le futur et à la date effective sinon.",
                verbose_name="Début et fin du mandat",
            ),
        ),
    ]
