# Generated by Django 2.1.3 on 2018-11-14 14:59

from django.db import migrations, models
import django.db.models.deletion


add_allocations_triggers = """
CREATE FUNCTION check_allocations_when_allocations_modified() RETURNS TRIGGER AS $process_allocation$
    DECLARE
       payment_amount INTEGER;
    BEGIN
        SELECT price INTO payment_amount FROM payments_payment WHERE id = NEW.payment_id;
        IF payment_amount < NEW.amount THEN
            RAISE EXCEPTION integrity_constraint_violation;
        END IF;
        RETURN NEW;
    END
$process_allocation$ LANGUAGE plpgsql;
    
CREATE FUNCTION check_allocations_when_donations_modified() RETURNS TRIGGER AS $process_donation$
    DECLARE 
        allocation INTEGER;
    BEGIN
        SELECT amount INTO allocation FROM donations_donationallocation WHERE payment_id = OLD.id;
        IF allocation IS NOT NULL AND (allocation > NEW.price OR  OLD.id <> NEW.id) THEN
            RAISE EXCEPTION integrity_constraint_violation;
        END IF;
        RETURN NEW;
    END
$process_donation$ LANGUAGE plpgsql;

CREATE TRIGGER check_allocations_when_allocations_modified BEFORE INSERT OR UPDATE ON donations_donationallocation
    FOR EACH ROW EXECUTE PROCEDURE check_allocations_when_allocations_modified();

CREATE TRIGGER check_allocations_when_donations_modified BEFORE UPDATE ON payments_payment
    FOR EACH ROW EXECUTE PROCEDURE check_allocations_when_donations_modified();
"""

remove_allocations_triggers = """
DROP TRIGGER check_allocations_when_donations_modified ON payments_payment;
DROP TRIGGER check_allocations_when_allocations_modified ON donations_donationallocation;
DROP FUNCTION check_allocations_when_donations_modified();
DROP FUNCTION check_allocations_when_allocations_modified();
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0028_auto_20181024_1757'),
        ('payments', '0007_auto_20180724_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(editable=False, verbose_name="allocation en centimes d'euros")),
                ('group', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='groups.SupportGroup')),
                ('payment', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='payments.Payment')),
            ],
        ),
        migrations.RunSQL(
            sql=add_allocations_triggers,
            reverse_sql=remove_allocations_triggers,
        )
    ]
