# Generated by Django 2.1.3 on 2018-12-03 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [("donations", "0002_spendings")]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="operation",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
