# Generated by Django 2.1.4 on 2018-12-04 20:35

import agir.donations.model_fields
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import dynamic_filenames
import uuid

import agir.payments.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_creer_modeles"),
        ("donations", "0003_auto_20181203_1538"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Titre du document"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("I", "Facture"),
                            (
                                "P",
                                "Photo ou illustration de l'événement, de la salle, du matériel",
                            ),
                            ("O", "Autre type de justificatif"),
                        ],
                        max_length=1,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="financement/request/{instance.request_id:s}/{uuid:s}{ext}"
                        ),
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "doc",
                                    "docx",
                                    "odt",
                                    "xls",
                                    "xlsx",
                                    "ods",
                                    "pdf",
                                    "png",
                                    "jpeg",
                                    "jpg",
                                    "gif",
                                ]
                            )
                        ],
                        verbose_name="Fichier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpendingRequest",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("D", "Brouillon à compléter"),
                            ("G", "En attente de validation par un autre animateur"),
                            (
                                "R",
                                "En attente de vérification par l'équipe de suivi des questions financières",
                            ),
                            ("I", "Informations supplémentaires requises"),
                            ("V", "Validée, en attente du paiement"),
                            ("P", "Payée"),
                        ],
                        default="D",
                        max_length=1,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("H", "Matériel militant"),
                            ("V", "Location d'une salle"),
                            ("S", "Prestation de service"),
                            ("S", "Autres"),
                        ],
                        max_length=1,
                        verbose_name="Catégorie de demande",
                    ),
                ),
                (
                    "category_precisions",
                    models.CharField(
                        max_length=260, verbose_name="Précisions sur le type de demande"
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        help_text="Merci de justifier votre demande. Longueur conseillée : 500 signes.",
                        max_length=1500,
                        verbose_name="Justification de la demande",
                    ),
                ),
                (
                    "amount",
                    agir.payments.model_fields.AmountField(
                        verbose_name="Montant de la dépense"
                    ),
                ),
                (
                    "spending_date",
                    models.DateField(
                        help_text="Si la dépense n'a pas encore été effectuée, merci d'indiquer la date probable à laquelle elle surviendra.",
                        verbose_name="Date de la dépense",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        max_length=200, verbose_name="Raison sociale du prestataire"
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        help_text="Indiquez le RIB du prestataire s'il s'agit d'un réglement, ou le RIB de la personne concernée s'il s'agit d'un remboursement.",
                        max_length=100,
                        verbose_name="RIB (format IBAN)",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        help_text="Si c'est pertinent, l'événement concerné par la dépense. Il doit être organisé par le groupe pour pouvoir être sélectionné.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="spending_requests",
                        related_query_name="spending_request",
                        to="events.Event",
                        verbose_name="Événement lié à la dépense",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="spending_requests",
                        related_query_name="spending_request",
                        to="groups.SupportGroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                related_query_name="document",
                to="donations.SpendingRequest",
            ),
        ),
    ]
