# Generated by Django 2.1.4 on 2018-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("donations", "0005_auto_20181211_1826")]

    operations = [
        migrations.AddField(
            model_name="document",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Supprimé"),
        )
    ]
