# Generated by Django 2.1.5 on 2019-01-25 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("donations", "0008_auto_20190114_1551")]

    operations = [
        migrations.AlterModelOptions(
            name="spendingrequest",
            options={
                "permissions": (
                    ("review_spendingrequest", "Peut traiter les demandes de dépenses"),
                )
            },
        )
    ]
