# Generated by Django 2.1.7 on 2019-02-15 18:02

import agir.donations.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("donations", "0011_auto_20190208_1743")]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="amount",
            field=agir.donations.model_fields.BalanceField(
                help_text="La valeur doit être positive pour une augmentation d'allocation et négative pour une diminution.",
                verbose_name="montant net",
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                related_query_name="operation",
                to="groups.SupportGroup",
            ),
        ),
    ]
