# Generated by Django 2.2.14 on 2020-07-01 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0020_auto_20200603_1554"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spendingrequest",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AlterField(
            model_name="spendingrequest",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
    ]
