# Generated by Django 2.2.14 on 2020-08-04 15:52

import agir.lib.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("donations", "0021_auto_20200701_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="spendingrequest",
            name="payer_name",
            field=models.CharField(
                blank=True,
                help_text="S'il s'agit du remboursement d'une dépense déjà faite, indiquez le nom de la personne qui a payé et à qui l'IBAN correspond. Sinon, laissez vide.",
                max_length=200,
                verbose_name="Nom de la personne qui a payé",
            ),
        ),
        migrations.AlterField(
            model_name="spendingrequest",
            name="iban",
            field=agir.lib.model_fields.IBANField(
                allowed_countries=["FR"],
                help_text="Indiquez le RIB du prestataire s'il s'agit d'un réglement, ou le RIB de la personne qui a payé s'il s'agit d'un remboursement.",
                max_length=34,
                verbose_name="RIB (format IBAN)",
            ),
        ),
    ]
