# Generated by Django 3.2.20 on 2023-11-02 17:01

import agir.donations.model_fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


SQL = """
-- On crée une table temporaire pour mémoriser les associations ancienne opération --> nouvelle opération
CREATE TEMPORARY TABLE operation_reference (operation_id integer, accountoperation_id integer);

INSERT INTO operation_reference (operation_id, accountoperation_id)
(
  SELECT o.id, nextval(pg_get_serial_sequence('donations_accountoperation', 'id'))
  FROM donations_operation AS o
);

-- on crée les nouvelles opérations
INSERT INTO public.donations_accountoperation (id, created, modified, amount, comment, source, destination, payment_id) 
(
  SELECT
  r.accountoperation_id AS id,
  o.created AS created,
  o.modified AS modified,
  ABS(o.amount) AS amount,
  o.comment AS comment,
  CASE 
    WHEN o.amount > 0 THEN 'revenu:dons'
    ELSE 'actif:groupe:' || o.group_id::text
  END as source,
  CASE
    WHEN o.amount > 0 THEN 'actif:groupe:' || o.group_id::text
    ELSE 'depenses'
  END AS destination,
  o.payment_id AS payment_id
  FROM public.donations_operation AS o
  JOIN operation_reference AS r
  ON o.id = r.operation_id
);

INSERT INTO donations_accountoperation (created, modified, amount, payment_id, comment, source, destination)
(
  SELECT
  created,
  modified,
  amount,
  payment_id,
  comment,
  'revenu:dons' AS source,
  'actif:cns' AS destination
  FROM donations_cnsoperation
);

INSERT INTO donations_accountoperation (created, modified, amount, payment_id, comment, source, destination)
(
  SELECT
  created,
  modified,
  amount,
  payment_id,
  comment,
  'revenu:dons' AS source,
  'actif:departement:' || departement AS destination
  FROM donations_departementoperation
);
"""

REVERSE_SQL = "TRUNCATE donations_accountoperation;"


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0018_membership_has_finance_managing_privilege"),
        ("payments", "0004_subscription_month_of_year"),
        ("donations", "0025_auto_20230712_1510"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "amount",
                    agir.donations.model_fields.PositiveBalanceField(
                        verbose_name="montant"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Le compte crédité, celui d'où vient la ressource",
                        max_length=200,
                        verbose_name="Source",
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        help_text="Le compte débité, celui où va la ressource",
                        max_length=200,
                        verbose_name="Destination",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Commentaire")),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="payments.payment",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="spendingrequest",
            name="account_operation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spending_request",
                to="donations.accountoperation",
            ),
        ),
        migrations.RunSQL(sql=SQL, reverse_sql=REVERSE_SQL),
        migrations.AddIndex(
            model_name="accountoperation",
            index=models.Index(
                fields=["source", "destination", "amount"],
                name="donations_accountop_source",
            ),
        ),
        migrations.AddIndex(
            model_name="accountoperation",
            index=models.Index(
                fields=["destination", "amount"], name="donations_accountop_dest"
            ),
        ),
    ]
