# Generated by Django 3.1.12 on 2021-06-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordrevirement",
            name="statut",
            field=models.CharField(
                choices=[("E", "Émis"), ("T", "Transmis à la banque")],
                default="E",
                max_length=1,
                verbose_name="Statut",
            ),
        ),
    ]
