# Generated by Django 3.1.6 on 2021-02-17 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_objets_initiaux_et_recherche"),
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="documents",
            field=models.ManyToManyField(
                related_name="projets",
                related_query_name="projet",
                to="gestion.Document",
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="documents",
            field=models.ManyToManyField(
                related_name="depenses",
                related_query_name="depense",
                to="gestion.Document",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.event",
                verbose_name="Événement sur la plateforme",
            ),
        ),
    ]
