# Generated by Django 3.1.7 on 2021-03-30 15:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_auto_20210217_1205"),
    ]

    operations = [
        migrations.RemoveField(model_name="depense", name="paiement",),
        migrations.AddField(
            model_name="compte",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AddField(
            model_name="compte",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="date_depense",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle la dépense a été engagée (généralement l'acceptation du contrat)",
                null=True,
                verbose_name="Date d'engagement de la dépense",
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="date_paiement",
            field=models.DateField(
                blank=True,
                help_text="Date à laquelle le paiement a été effecté.",
                null=True,
                verbose_name="Date du paiement",
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="fournisseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gestion.fournisseur",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="fichier",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=dynamic_filenames.FilePattern(
                    filename_pattern="gestion/documents/{uuid:.2base32}/{uuid}{ext}"
                ),
                verbose_name="Fichier du document",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="identifiant",
            field=models.CharField(
                blank=True,
                help_text="Indiquez ici si ce document a un identifiant ou un numéro (numéro de facture ou de devis, identifiant de transaction, etc.)",
                max_length=100,
                verbose_name="Identifiant ou numéro externe",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("FAC", "Facture"),
                    ("JUS", "Justificatif de dépense"),
                    ("DEV", "Devis"),
                    ("PAY", "Preuve de paiement"),
                    ("GRA", "Attestation de gratuité"),
                    ("AUT", "Autre (à détailler dans les commentaires)"),
                ],
                max_length=10,
                verbose_name="Type de document",
            ),
        ),
    ]
