# Generated by Django 3.1.8 on 2021-04-21 13:04

import agir.lib.model_fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_display_name_and_image"),
        ("gestion", "0004_depense_type"),
    ]

    operations = [
        migrations.RemoveField(model_name="depense", name="contact_email_fournisseur",),
        migrations.RemoveField(model_name="depense", name="contact_phone_fournisseur",),
        migrations.RemoveField(model_name="depense", name="date_paiement",),
        migrations.RemoveField(model_name="depense", name="iban_fournisseur",),
        migrations.RemoveField(model_name="depense", name="nom_fournisseur",),
        migrations.RemoveField(model_name="document", name="statut",),
        migrations.RemoveField(model_name="fournisseur", name="commentaires",),
        migrations.AddField(
            model_name="depense",
            name="personnes",
            field=models.ManyToManyField(
                blank=True,
                related_name="depenses",
                related_query_name="depense",
                to="people.Person",
                verbose_name="Personnes concernées",
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="depense",
            name="type",
            field=models.CharField(
                choices=[
                    ("AFM", "Achats de fournitures et marchandises"),
                    ("AFM-B", "- Achats de fourniture de bureau"),
                    ("AFM-G", "- Achats de goodies"),
                    ("FBC", "Frais bancaires"),
                    ("FDV", "Frais divers"),
                    ("FRH", "Frais de réception et d'hébergement"),
                    ("FRH-H", "- Frais d'hébergement"),
                    ("FRH-A", "- Frais de restauration"),
                    ("HEC", "Honoraires de l'expert comptable"),
                    ("HCC", "Honoraires et conseils en communication"),
                    ("HCC-G", "- Graphisme et maquettage"),
                    ("HCC-C", "- Conseil en communication"),
                    ("IMM", "Location ou mise à disposition immobilière"),
                    ("IMM-S", "- Mise à disposition d'une salle"),
                    ("IMM-L", "- Loyers de location"),
                    ("PAU", "Production audiovisuelle"),
                    ("PIM", "Publication et impression (hors R39)"),
                    ("REU", "Frais divers liées aux réunions publiques"),
                    ("TRA", "Transports et déplacement"),
                    ("TRA-T", "- Billets de train"),
                    ("TRA-A", "- Billets d'avion"),
                    ("TRA-L", "- Location d'un véhicule"),
                    ("TRA-K", "- Frais kilométriques"),
                ],
                max_length=5,
                verbose_name="Type de dépense",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEV", "Devis"),
                    ("FAC", "Facture"),
                    ("JUS", "Justificatif de dépense"),
                    ("PAY", "Preuve de paiement"),
                    ("GRA", "Attestation de gratuité"),
                    ("AUT", "Autre (à détailler dans les commentaires)"),
                ],
                max_length=10,
                verbose_name="Type de document",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="type",
            field=models.CharField(
                choices=[
                    ("CON", "Conférence de presse"),
                    ("REU", "Réunion publique"),
                    ("REU-loc", "Réunion publique organisée localement"),
                    ("REU-ora", "Réunion publique avec un orateur national"),
                    ("REU-can", "Réunion publique avec un candidat"),
                    ("DEB", "Débats et conférences"),
                    ("DEB-aso", "Débat organisé par une association"),
                    ("DEB-con", "Conférence"),
                    ("DEB-caf", "Café-débat"),
                    ("MAN", "Manifestation publique"),
                    ("MAN-loc", "Manifestation ou marche organisée localement"),
                    ("MAN-nat", "Manifestation ou marche nationale"),
                    ("ACT", "Actions"),
                    ("RH", "Dépenses RH mensuelles"),
                ],
                max_length=10,
                verbose_name="Type de projet",
            ),
        ),
        migrations.CreateModel(
            name="Versement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Montant du versement",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Date du versement",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("C", "En cours"), ("R", "Réglé"), ("P", "Rapproché")],
                        default="C",
                        max_length=1,
                    ),
                ),
                (
                    "nom_fournisseur",
                    models.CharField(max_length=100, verbose_name="Nom du fournisseur"),
                ),
                (
                    "iban_fournisseur",
                    agir.lib.model_fields.IBANField(
                        allowed_countries=None,
                        blank=True,
                        max_length=34,
                        verbose_name="IBAN du fournisseur",
                    ),
                ),
                (
                    "contact_phone_fournisseur",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="Numéro de téléphone",
                    ),
                ),
                (
                    "contact_email_fournisseur",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Adresse email"
                    ),
                ),
                (
                    "location_address1_fournisseur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="adresse (1ère ligne)"
                    ),
                ),
                (
                    "location_address2_fournisseur",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="adresse (1ère ligne)"
                    ),
                ),
                (
                    "location_city_fournisseur",
                    models.CharField(max_length=100, verbose_name="ville"),
                ),
                (
                    "location_zip_fournisseur",
                    models.CharField(max_length=20, verbose_name="code postal"),
                ),
                (
                    "location_country_fournisseur",
                    django_countries.fields.CountryField(
                        default="FR", max_length=2, verbose_name="pays"
                    ),
                ),
                (
                    "depense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versements",
                        related_query_name="versement",
                        to="gestion.depense",
                        verbose_name="Dépense concernée",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gestion.fournisseur",
                    ),
                ),
                (
                    "preuve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gestion.document",
                        verbose_name="Preuve de paiement",
                    ),
                ),
            ],
            options={"verbose_name": "versement", "ordering": ("date",),},
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CAN", "Candidat"),
                            ("ORA", "Orateur"),
                            ("ORG", "Organisation"),
                            ("GES", "Gestion de projet"),
                        ],
                        max_length=3,
                        verbose_name="Rôle sur ce projet",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                        verbose_name="Personne",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation à un projet",
                "verbose_name_plural": "participations à des projets",
                "unique_together": {("projet", "person", "role")},
            },
        ),
    ]
