# Generated by Django 3.1.8 on 2021-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_auto_20210423_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="precisions",
            field=models.TextField(blank=True, verbose_name="Précisions"),
        ),
    ]
