# Generated by Django 3.1.8 on 2021-04-22 13:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_auto_20210421_1504"),
    ]

    operations = [
        migrations.AddField(
            model_name="versement",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="date de création",
            ),
        ),
        migrations.AddField(
            model_name="versement",
            name="mode",
            field=models.CharField(
                choices=[
                    ("V", "Par virement"),
                    ("P", "Par prélèvement"),
                    ("C", "Par chèque"),
                    ("A", "Par carte bancaire"),
                    ("S", "En espèces"),
                ],
                default="C",
                max_length=1,
                verbose_name="Mode de réglement",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="versement",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, verbose_name="dernière modification"
            ),
        ),
    ]
