# Generated by Django 3.1.13 on 2021-10-19 16:29

from django.db import migrations, models


def origine_depuis_statut(apps, schema):
    Projet = apps.get_model("gestion", "Projet")
    Projet.objects.filter(etat="DFI").update(origine="U")


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0005_document_versions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjetMilitant",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gestion.projet",),
        ),
        migrations.AddField(
            model_name="projet",
            name="origine",
            field=models.CharField(
                choices=[
                    ("A", "Créé sur l'admin"),
                    ("U", "Créé par un·e militant·e sur Action Populaire"),
                ],
                default="A",
                editable=False,
                max_length=1,
                verbose_name="Origine du projet",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEV", "Devis"),
                    ("CON", "Contrat"),
                    ("FAC", "Facture"),
                    ("JUS", "Justificatif de dépense"),
                    ("JUS-BIL", "Billet de train"),
                    ("JUS-TRAIN", "Justificatif de train"),
                    ("JUS-CEM", "Carte d'embarquement"),
                    ("PAY", "Preuve de paiement"),
                    ("PAY-CHK", "Scan du chèque"),
                    ("PAY-TKT", "Ticket de caisse"),
                    ("EXA", "Exemplaire fourni"),
                    ("PHO", "Photographie de l'objet ou de l'événement"),
                    ("AUT", "Autre (à détailler dans les commentaires)"),
                    ("ATT", "Attestation"),
                    ("ATT-GRA", "Attestation de gratuité"),
                    ("ATT-CON", "Attestation de concours en nature"),
                    ("ATT-REG", "Attestation de règlement des consommations"),
                    (
                        "ATT-ESP",
                        "Demande d'autorisation d'occupation de l'espace public",
                    ),
                ],
                max_length=10,
                verbose_name="Type de document",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="etat",
            field=models.CharField(
                choices=[
                    ("DFI", "Créé par un·e militant·e"),
                    ("REF", "Refusé"),
                    ("ECO", "En cours de constitution"),
                    ("FIN", "Finalisé par le secrétariat"),
                    ("REN", "Renvoyé par l'équipe financière"),
                    ("CLO", "Clôturé"),
                ],
                default="DFI",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
        migrations.RunPython(
            code=origine_depuis_statut, reverse_code=migrations.RunPython.noop
        ),
    ]
