# Generated by Django 3.1.13 on 2021-10-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0006_origine_projet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="titre",
            field=models.CharField(max_length=200, verbose_name="Titre du projet"),
        ),
    ]
