# Generated by Django 3.1.8 on 2021-05-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_display_name_and_image"),
        ("gestion", "0007_auto_20210430_1654"),
    ]

    operations = [
        migrations.RemoveField(model_name="depense", name="personnes",),
        migrations.AddField(
            model_name="depense",
            name="beneficiaires",
            field=models.ManyToManyField(
                blank=True,
                related_name="depenses",
                related_query_name="depense",
                to="people.Person",
                verbose_name="Bénéficiaires de la dépense",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEV", "Devis"),
                    ("FAC", "Facture"),
                    ("JUS", "Justificatif de dépense"),
                    ("JUS-BIL", "Billet de train"),
                    ("JUS-TRAIN", "Justificatif de train"),
                    ("JUS-CEM", "Carte d'embarquement"),
                    ("PAY", "Preuve de paiement"),
                    ("PAY-CHK", "Scan du chèque"),
                    ("PAY-TKT", "Ticket de caisse"),
                    ("GRA", "Attestation de gratuité"),
                    ("EXA", "Exemplaire fourni"),
                    ("PHO", "Photographie de l'objet ou de l'événement"),
                    ("AUT", "Autre (à détailler dans les commentaires)"),
                ],
                max_length=10,
                verbose_name="Type de document",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="participation",
                to="people.person",
                verbose_name="Personne",
            ),
        ),
        migrations.AlterField(
            model_name="participation",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                related_query_name="participation",
                to="gestion.projet",
                verbose_name="Projet",
            ),
        ),
    ]
