# Generated by Django 3.1.14 on 2021-12-23 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0008_auto_20211116_1639"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compte",
            options={
                "permissions": [
                    (
                        "acces_contenu_restreint",
                        "Voir les projets, dépenses et documents dont l'accès est indiqué comme restreint.",
                    ),
                    (
                        "acces_contenu_secret",
                        "Voir les projets, dépenses et documents dont l'accès est indiqué commme secret.",
                    ),
                    ("engager_depense", "Engager une dépense pour ce compte"),
                    ("gerer_depense", "Gérer les dépenses"),
                    ("voir_montant_depense", "Voir le montant des dépenses finalisées"),
                    ("controler_depense", "Contrôler les dépenses"),
                    ("gerer_projet", "Gérer les projets"),
                    ("controler_projet", "Contrôler les projets"),
                ],
                "verbose_name": "Compte",
                "verbose_name_plural": "Comptes",
            },
        ),
    ]
