# Generated by Django 3.1.11 on 2021-05-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0008_auto_20210505_1449"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compte",
            options={
                "permissions": [
                    (
                        "acces_contenu_restreint",
                        "Voir les projets, dépenses et documents dont l'accès est indiqué comme restreint.",
                    ),
                    (
                        "acces_contenu_secret",
                        "Voir les projets, dépenses et documents dont l'accès est indiqué commme secret.",
                    ),
                    ("engager_depense", "Engager une dépense pour ce compte"),
                    ("gerer_depense", "Gérer les dépenses"),
                ],
                "verbose_name": "Compte",
                "verbose_name_plural": "Comptes",
            },
        ),
        migrations.RemoveField(model_name="depense", name="validation",),
        migrations.AddField(
            model_name="compte",
            name="configuration",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Configuration"
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="etat",
            field=models.CharField(
                choices=[
                    ("R", "Dossier refusé"),
                    ("V", "En attente de validation d'opportunité"),
                    ("A", "En attente de l'engagement de la dépense"),
                    ("C", "Constitution du dossier"),
                    ("O", "Dossier complété"),
                    ("L", "Dossier clôturé"),
                ],
                default="V",
                max_length=1,
                verbose_name="État de ce dossier de dépense",
            ),
        ),
        migrations.AlterField(
            model_name="commentaire",
            name="type",
            field=models.CharField(
                choices=[("R", "Remarque"), ("T", "À faire")],
                max_length=1,
                verbose_name="Type de commentaire",
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="type",
            field=models.CharField(
                choices=[
                    ("AFM", "Achats de fournitures et marchandises"),
                    ("AFM-B", "Achats de fourniture de bureau"),
                    ("AFM-G", "Achats de goodies"),
                    ("FBC", "Frais bancaires"),
                    ("FDV", "Frais divers"),
                    ("FRH", "Frais de réception et d'hébergement"),
                    ("FRH-H", "Frais d'hébergement"),
                    ("FRH-A", "Frais de restauration"),
                    ("HEC", "Honoraires de l'expert comptable"),
                    ("HCC", "Honoraires et conseils en communication"),
                    ("HCC-G", "Graphisme et maquettage"),
                    ("HCC-C", "Conseil en communication"),
                    ("IMM", "Location ou mise à disposition immobilière"),
                    ("IMM-S", "Mise à disposition d'une salle"),
                    ("IMM-L", "Loyers de location"),
                    ("PAU", "Production audiovisuelle"),
                    ("PIM", "Publication et impression (hors R39)"),
                    ("REU", "Frais divers liées aux réunions publiques"),
                    ("TRA", "Transports et déplacement"),
                    ("TRA-T", "Billets de train"),
                    ("TRA-A", "Billets d'avion"),
                    ("TRA-L", "Location d'un véhicule"),
                    ("TRA-K", "Frais kilométriques"),
                ],
                max_length=5,
                verbose_name="Type de dépense",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="requis",
            field=models.CharField(
                choices=[
                    ("NEC", "Strictement nécessaire"),
                    ("PRE", "Préférable"),
                    ("IGN", "Peut être ignoré"),
                ],
                default="NEC",
                max_length=3,
                verbose_name="Obligatoire ?",
            ),
        ),
    ]
