# Generated by Django 3.1.14 on 2021-12-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0009_auto_20211223_1800"),
    ]

    operations = [
        migrations.AddField(
            model_name="depense",
            name="nature",
            field=models.CharField(
                blank=True,
                help_text="La nature du bien acheté, à remplir simultanément avec le champ quantité si applicable.",
                max_length=200,
                verbose_name="Nature",
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="quantite",
            field=models.IntegerField(
                blank=True,
                help_text="Lorsque la dépense correspond à l'achat de matériel, indiquez ici la quantité achetée.",
                null=True,
                verbose_name="Quantité",
            ),
        ),
    ]
