# Generated by Django 3.1.12 on 2021-06-07 14:05

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("gestion", "0010_renommer_statut_etat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="projet",
            field=models.ForeignKey(
                blank=True,
                help_text="Le projet éventuel auquel est rattaché cette dépense.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="depenses",
                related_query_name="depense",
                to="gestion.projet",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="etat",
            field=models.CharField(
                choices=[
                    ("DFI", "Demande de financement"),
                    ("REF", "Refusé"),
                    ("ECO", "En cours de constitution"),
                    ("FIN", "Finalisé par le secrétariat"),
                    ("REN", "Renvoyé par l'équipe financière"),
                    ("CLO", "Clôturé"),
                ],
                default="DFI",
                max_length=3,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="type",
            field=models.CharField(
                choices=[
                    ("CON", "Conférence de presse"),
                    ("REU", "Réunion publique"),
                    ("REU-loc", "Réunion publique organisée localement"),
                    ("REU-ora", "Réunion publique avec un orateur national"),
                    ("REU-can", "Réunion publique avec un candidat"),
                    ("DEB", "Débats et conférences"),
                    ("DEB-aso", "Débat organisé par une association"),
                    ("DEB-con", "Conférence"),
                    ("DEB-caf", "Café-débat"),
                    ("MAN", "Manifestation publique"),
                    ("MAN-loc", "Manifestation ou marche organisée localement"),
                    ("MAN-nat", "Manifestation ou marche nationale"),
                    ("ACT", "Actions"),
                    ("EVE", "Événements spécifiques"),
                    ("EVE-AMF", "AMFiS d'été"),
                    ("EVE-CON", "Convention"),
                    ("RH", "Dépenses RH mensuelles"),
                ],
                max_length=10,
                verbose_name="Type de projet",
            ),
        ),
        migrations.CreateModel(
            name="Autorisation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "autorisations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autorisations",
                        related_query_name="autorisation",
                        to="gestion.compte",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
