# Generated by Django 3.1.14 on 2022-01-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0010_auto_20211223_1845"),
    ]

    operations = [
        migrations.AddField(
            model_name="depense",
            name="date_debut",
            field=models.DateField(
                blank=True,
                help_text="Premier jour d'utilisation du matériel, premier jour de l'opération correspondante.",
                null=True,
                verbose_name="Date de début",
            ),
        ),
        migrations.AddField(
            model_name="depense",
            name="date_fin",
            field=models.DateField(
                blank=True,
                help_text="Dernier jour d'utilisation du matériel, dernier jour de l'opération correspondante.",
                null=True,
                verbose_name="Date de fin",
            ),
        ),
    ]
