# Generated by Django 3.1.12 on 2021-06-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0011_auto_20210607_1605"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compte",
            options={
                "permissions": [
                    (
                        "acces_contenu_restreint",
                        "Voir les projets, dépenses et documents dont l'accès est indiqué comme restreint.",
                    ),
                    (
                        "acces_contenu_secret",
                        "Voir les projets, dépenses et documents dont l'accès est indiqué commme secret.",
                    ),
                    ("engager_depense", "Engager une dépense pour ce compte"),
                    ("gerer_depense", "Gérer les dépenses"),
                    ("controler_depense", "Contrôler les dépenses"),
                    ("gerer_projet", "Gérer les projets"),
                    ("controler_projet", "Contrôler les projets"),
                ],
                "verbose_name": "Compte",
                "verbose_name_plural": "Comptes",
            },
        ),
        migrations.AddField(
            model_name="depense",
            name="depenses_refacturees",
            field=models.ManyToManyField(
                blank=True,
                related_name="refacturations",
                related_query_name="refacturation",
                to="gestion.Depense",
                verbose_name="Dépenses à refacturer",
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="type",
            field=models.CharField(
                choices=[
                    ("AFM", "Achats de fournitures et marchandises"),
                    ("AFM-B", "Achats de fourniture de bureau"),
                    ("AFM-G", "Achats de goodies"),
                    ("FBC", "Frais bancaires"),
                    ("FDV", "Frais divers"),
                    ("FRH", "Frais de réception et d'hébergement"),
                    ("FRH-H", "Frais d'hébergement"),
                    ("FRH-A", "Frais de restauration"),
                    ("HEC", "Honoraires de l'expert comptable"),
                    ("HCC", "Honoraires et conseils en communication"),
                    ("HCC-G", "Graphisme et maquettage"),
                    ("HCC-C", "Conseil en communication"),
                    ("IMM", "Location ou mise à disposition immobilière"),
                    ("IMM-S", "Mise à disposition d'une salle"),
                    ("IMM-L", "Loyers de location"),
                    ("PAU", "Production audiovisuelle"),
                    ("PIM", "Publication et impression (hors R39)"),
                    ("REU", "Frais divers liées aux réunions publiques"),
                    ("TRA", "Transports et déplacement"),
                    ("TRA-T", "Billets de train"),
                    ("TRA-A", "Billets d'avion"),
                    ("TRA-L", "Location d'un véhicule"),
                    ("TRA-K", "Frais kilométriques"),
                    ("REF", "Refacturation"),
                ],
                max_length=5,
                verbose_name="Type de dépense",
            ),
        ),
    ]
