# Generated by Django 3.1.12 on 2021-06-11 13:53

import agir.gestion.models.common
from django.db import migrations, models
import django.utils.timezone
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_auto_20210608_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='type',
            field=models.CharField(choices=[('R', 'Remarque'), ('T', 'Todo')], max_length=1, verbose_name='Type de commentaire'),
        ),
        migrations.AlterField(
            model_name='depense',
            name='depenses_refacturees',
            field=models.ManyToManyField(blank=True, help_text='Toutes les dépenses concernées par cette refacturation.', related_name='refacturations', related_query_name='refacturation', to='gestion.Depense', verbose_name='Dépenses à refacturer'),
        ),
        migrations.AlterField(
            model_name='reglement',
            name='location_address2_fournisseur',
            field=models.CharField(blank=True, max_length=100, verbose_name='adresse (2ère ligne)'),
        ),
        migrations.CreateModel(
            name='OrdreVirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('numero', models.CharField(default=agir.gestion.models.common.numero_unique, editable=False, help_text='Numéro unique pour identifier chaque objet sur la plateforme.', max_length=7, unique=True, verbose_name='Numéro unique')),
                ('statut', models.CharField(choices=[('E', 'Émis'), ('T', 'Transmis à la banque'), ('R', 'Rapproché')], default='E', max_length=1, verbose_name='Statut')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'exécution de l'ordre")),
                ('fichier', models.FileField(upload_to=dynamic_filenames.FilePattern(filename_pattern='gestion/ordres/{uuid:.2base32}/{uuid}{ext}'), verbose_name="Fichier SEPA de l'ordre de virement")),
                ('commentaires', models.ManyToManyField(help_text="Ces commentaires permettent d'ajouter de garder la trace des opérations de traitement des différentes pièces.", to='gestion.Commentaire', verbose_name='Commentaires')),
                ('reglements', models.ManyToManyField(related_name='ordre', related_query_name='ordres', to='gestion.Reglement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
