# Generated by Django 3.1.12 on 2021-06-11 15:13

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0014_instancecherchable"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="instancecherchable",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["recherche"], name="gestion_ins_recherc_d4e6ff_gin"
            ),
        ),
    ]
