# Generated by Django 3.2.12 on 2022-02-24 16:16

from django.db import migrations
import agir.lib.model_fields


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0016_auto_20220221_1602"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reglement",
            old_name="bic_founisseur",
            new_name="bic_fournisseur",
        ),
        migrations.AlterField(
            model_name="reglement",
            name="bic_fournisseur",
            field=agir.lib.model_fields.BICField(
                blank=True, verbose_name="BIC du fournisseur"
            ),
        ),
    ]
