# Generated by Django 3.2.12 on 2022-03-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0018_fournisseur_bic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="etat",
            field=models.CharField(
                choices=[
                    ("R", "Dossier refusé"),
                    ("V", "En attente de validation d'opportunité"),
                    ("A", "En attente de l'engagement de la dépense"),
                    ("C", "Constitution du dossier"),
                    ("O", "Dossier complété"),
                    ("L", "Dossier clôturé"),
                    ("E", "En attente d'intégration au FEC"),
                    ("F", "Intégré au FEC"),
                ],
                default="V",
                max_length=1,
                verbose_name="État de ce dossier de dépense",
            ),
        ),
        migrations.AlterField(
            model_name="depense",
            name="type",
            field=models.CharField(
                choices=[
                    ("REU", "Frais divers liées aux réunions publiques"),
                    (
                        "REU-IMP",
                        "Impression et envoi de cartons d'invitation pour une réunion publique",
                    ),
                    (
                        "REU-LOC",
                        "Utilisation d'un local pour les besoins d'une réunion publique",
                    ),
                    ("REU-AME", "Aménagements apportés au local "),
                    ("REU-EC", "Éclairage et sonorisation"),
                    ("REU-ORD", "Service d'ordre et sécurité"),
                    ("REU-AUT", "Autres frais liés à une réunion publique"),
                    ("PIM", "Publication et impression (hors R39)"),
                    ("PIM-CON", "Frais de conception et d'impression"),
                    ("PIM-POS", "Frais de distribution et postaux"),
                    ("PIM-PRO", "Frais de promotion"),
                    ("PIM-AUT", "Autres frais d'impression et de publication"),
                    ("AFM", "Achats de fournitures et marchandises"),
                    ("AFM-B", "Achats de fourniture de bureau"),
                    ("AFM-G", "Achats de goodies"),
                    ("AFM-M", "Dépenses de matériel"),
                    ("FBC", "Frais bancaires"),
                    ("FDV", "Frais divers"),
                    ("FRH", "Frais de réception et d'hébergement"),
                    ("FRH-H", "Frais d'hébergement"),
                    ("FRH-A", "Frais de restauration"),
                    ("HEC", "Honoraires de l'expert comptable"),
                    ("HCC", "Honoraires et conseils en communication"),
                    ("IMM", "Location ou mise à disposition immobilière"),
                    ("IMM-L", "Loyers de location"),
                    ("IMM-T", "Travaux au local"),
                    ("IMM-AUT", "Autres frais immobiliers"),
                    ("PAU", "Propagande audiovisuelle"),
                    ("PAU-CON", "Frais de conception et de réalisation audiovisuelle"),
                    (
                        "PAU-DIS",
                        "Frais de reproduction, diffusion et de distribution audiovisuelle",
                    ),
                    ("PAU-PRO", "Frais de promotion audiovisuelle"),
                    ("PAU-AUT", "Autres frais audiovisuels"),
                    ("TRA", "Transports et déplacement"),
                    ("TRA-T", "Billets de train"),
                    ("TRA-A", "Billets d'avion"),
                    ("TRA-L", "Location d'un véhicule"),
                    ("TRA-K", "Frais kilométriques"),
                    ("SAL", "Salaires"),
                    ("REF", "Refacturation"),
                ],
                max_length=7,
                verbose_name="Type de dépense",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="intitule",
            field=models.CharField(
                help_text="Ce champ est utilisé comme intitulé dans le FEC, et comme intitulé dans le relevé bancaire pour les virements générés.",
                max_length=200,
                verbose_name="Libellé dans le FEC",
            ),
        ),
    ]
