# Generated by Django 3.2.12 on 2022-03-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0019_auto_20220303_1718"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fournisseur",
            options={"ordering": ("nom", "location_city")},
        ),
        migrations.RenameField(
            model_name="document",
            old_name="titre",
            new_name="precision",
        ),
        migrations.AlterField(
            model_name="document",
            name="precision",
            field=models.CharField(
                blank=True,
                help_text="Titre permettant d'identifier le document",
                max_length=200,
                verbose_name="Précision sur la nature du document",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="identifiant",
            field=models.CharField(
                blank=True,
                help_text="Indiquez ici si ce document a un identifiant ou un numéro (numéro de facture ou de devis, identifiant de transaction, etc.)",
                max_length=100,
                verbose_name="Numéro ou identifiant",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="origine",
            field=models.CharField(
                choices=[
                    ("A", "Créé par les équipes de campagne"),
                    ("U", "Créé par un·e militant·e sur Action Populaire"),
                    ("R", "Réunion publique suite à demande"),
                ],
                default="A",
                editable=False,
                max_length=1,
                verbose_name="Origine du projet",
            ),
        ),
    ]
