# Generated by Django 3.2.12 on 2022-03-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0020_auto_20220310_1835"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fournisseur",
            old_name="location_state",
            new_name="location_country_name",
        ),
    ]
