# Generated by Django 3.2.12 on 2022-03-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0021_alter_compte_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reglement",
            options={"ordering": ("-date",), "verbose_name": "règlement"},
        ),
        migrations.AddField(
            model_name="reglement",
            name="commentaires",
            field=models.ManyToManyField(
                help_text="Ces commentaires permettent d'ajouter de garder la trace des opérations de traitement des différentes pièces.",
                to="gestion.Commentaire",
                verbose_name="Commentaires",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("C", "En cours"),
                    ("R", "Réglé"),
                    ("P", "Rapproché"),
                    ("E", "Attente de validation pour l'expertise comptable"),
                    ("F", "Intégré au FEC"),
                ],
                default="C",
                max_length=1,
            ),
        ),
    ]
