# Generated by Django 3.2.12 on 2022-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0022_auto_20220316_1704"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="date",
            field=models.DateField(
                blank=True,
                help_text="Si le document a une date, indiquez-la ici.",
                null=True,
                verbose_name="Date du document",
            ),
        ),
    ]
