# Generated by Django 3.2.12 on 2022-03-24 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0024_facture_reglement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reglement",
            name="facture",
            field=models.ForeignKey(
                blank=True,
                help_text="Indiquez laquelle des factures de la dépense est lié ce paiement.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="comme_facture",
                to="gestion.document",
                verbose_name="Facture associée",
            ),
        ),
    ]
