# Generated by Django 3.2.12 on 2022-03-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0025_alter_reglement_facture"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reglement",
            old_name="statut",
            new_name="etat",
        ),
        migrations.AlterField(
            model_name="reglement",
            name="etat",
            field=models.CharField(
                choices=[
                    ("C", "En cours"),
                    ("R", "Réglé"),
                    ("P", "Rapproché"),
                    ("E", "Attente de validation pour l'expertise comptable"),
                    ("F", "Intégré au FEC"),
                ],
                default="C",
                max_length=1,
                verbose_name="état",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="etat",
            field=models.CharField(
                choices=[
                    ("DFI", "Créé par un·e militant·e"),
                    ("REF", "Refusé"),
                    ("ECO", "En cours de constitution"),
                    ("FIN", "Finalisé par le secrétariat"),
                    ("REN", "Renvoyé par l'équipe financière"),
                    ("CLO", "Clôturé"),
                ],
                default="DFI",
                max_length=3,
                verbose_name="État",
            ),
        ),
        migrations.AlterField(
            model_name="reglement",
            name="ordre_virement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reglements",
                related_query_name="reglement",
                to="gestion.ordrevirement",
                verbose_name="Ordre de virement",
            ),
        ),
    ]
