# Generated by Django 3.2.12 on 2022-04-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0027_reglement_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="type",
            field=models.CharField(
                choices=[
                    ("REU", "Frais divers liées aux réunions publiques"),
                    (
                        "REU-IMP",
                        "Impression et envoi de cartons d'invitation pour une réunion publique",
                    ),
                    (
                        "REU-LOC",
                        "Utilisation d'un local pour les besoins d'une réunion publique",
                    ),
                    ("REU-AME", "Aménagements apportés au local "),
                    ("REU-EC", "Éclairage et sonorisation"),
                    ("REU-ORD", "Service d'ordre et sécurité"),
                    ("REU-AUT", "Autres frais liés à une réunion publique"),
                    ("PIM", "Publication et impression (hors R39)"),
                    ("PIM-CON", "Frais de conception et d'impression"),
                    ("PIM-POS", "Frais de distribution et postaux"),
                    ("PIM-PRO", "Frais de promotion"),
                    ("PIM-AUT", "Autres frais d'impression et de publication"),
                    ("AFM", "Achats de fournitures et marchandises"),
                    ("AFM-B", "Achats de fourniture de bureau"),
                    ("AFM-G", "Achats de goodies"),
                    ("AFM-M", "Dépenses de matériel"),
                    ("FBC", "Frais bancaires"),
                    ("FDV", "Frais divers"),
                    ("FRH", "Frais de réception et d'hébergement"),
                    ("FRH-H", "Frais d'hébergement"),
                    ("FRH-A", "Frais de restauration"),
                    ("HEC", "Honoraires de l'expert comptable"),
                    ("HCC", "Honoraires et conseils en communication"),
                    ("IMM", "Location ou mise à disposition immobilière"),
                    ("IMM-L", "Loyers de location"),
                    ("IMM-T", "Travaux au local"),
                    ("IMM-AUT", "Autres frais immobiliers"),
                    ("PAU", "Propagande audiovisuelle"),
                    ("PAU-CON", "Frais de conception et de réalisation audiovisuelle"),
                    (
                        "PAU-DIS",
                        "Frais de reproduction, diffusion et de distribution audiovisuelle",
                    ),
                    ("PAU-PRO", "Frais de promotion audiovisuelle"),
                    ("PAU-AUT", "Autres frais audiovisuels"),
                    ("TRA", "Transports et déplacement"),
                    ("TRA-T", "Billets de train"),
                    ("TRA-A", "Billets d'avion"),
                    ("TRA-L", "Location d'un véhicule"),
                    ("TRA-K", "Frais kilométriques"),
                    ("SAL", "Salaires"),
                    ("VER", "Versements personnels du candidat"),
                    (
                        "VER-PRO",
                        "Versements personnels du candidat sur ses propres deniers",
                    ),
                    ("VER-EBQ", "Versements personnels suite à emprunt bancaire"),
                    (
                        "VER-EFP",
                        "Versements personnels suite à emprunt à une formation politique",
                    ),
                    ("DON", "Dons de personnes physiques"),
                    ("VFP", "Versement définitif d'une formation politique"),
                    ("DFP", "Dépense payée par une formation politique"),
                    ("CCN", "Concours en nature"),
                    ("CCN-CND", "Concours en nature fourni par un candidat"),
                    ("CCN-FP", "Concours en nature par une formation politique"),
                    ("CCN-PP", "Concours en nature par une personne physique"),
                    ("RCC", "Recettes d'opérations commerciales"),
                    ("COL", "Collectes et participations aux manifestations"),
                    ("FIN", "Produit financier"),
                    ("ARC", "Autres recettes"),
                    ("REF", "Refacturation"),
                ],
                max_length=7,
                verbose_name="Type de dépense",
            ),
        ),
    ]
