# Generated by Django 3.2.12 on 2022-05-09 14:14

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0029_alter_depense_quantite"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="numero_piece",
            field=models.CharField(
                blank=True,
                help_text="Le numéro de pièce justificative à utiliser pour l'export vers FinPol.",
                max_length=12,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex=re.compile(
                            "^(?P<compte>\\d{5})(?P<departement>\\d\\d[\\dAB])(?P<ordre>\\d{4})$"
                        )
                    )
                ],
                verbose_name="Numéro de pièce justificative",
            ),
        ),
        migrations.AddField(
            model_name="reglement",
            name="date_validation",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de validation de l'écriture"
            ),
        ),
    ]
