# Generated by Django 3.2.13 on 2022-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0031_auto_20220520_1345"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglement",
            name="numero_complement",
            field=models.CharField(
                blank=True,
                max_length=5,
                verbose_name="Complément pour différencier plusieurs transactions avec le même numéro",
            ),
        ),
    ]
