# Generated by Django 3.2.13 on 2022-05-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0032_reglement_numero_complement"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglement",
            name="libre",
            field=models.TextField(blank=True, verbose_name="Commentaire libre"),
        ),
    ]
