# Generated by Django 3.2.13 on 2022-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0034_auto_20220531_1215"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglement",
            name="date_evenement",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de l'événement"
            ),
        ),
    ]
