# Generated by Django 3.2.13 on 2022-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0035_reglement_date_evenement"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="date_evenement",
            field=models.DateField(
                blank=True,
                help_text="À utiliser s'il n'y a pas d'événement associé, ou si il faut utiliser une autre date que celle de l'événement",
                null=True,
                verbose_name="date de l'événement",
            ),
        ),
    ]
