# Generated by Django 3.2.13 on 2022-06-17 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0037_alter_projet_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="code_insee",
            field=models.CharField(
                blank=True,
                help_text="À utiliser s'il n'y a pas d'événement associé, ou si il faut utiliser un autre lieu que celui de l'événement",
                max_length=5,
                validators=[django.core.validators.RegexValidator(regex="^\\d{5}$")],
                verbose_name="code INSEE commune",
            ),
        ),
    ]
