# Generated by Django 3.2.13 on 2022-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0041_versiondocument_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="titre",
            field=models.CharField(
                help_text="Une description sommaire de la nature de la dépense",
                max_length=250,
                verbose_name="Titre de la dépense",
            ),
        ),
    ]
