# Generated by Django 3.2.13 on 2022-06-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gestion", "0042_alter_depense_titre"),
    ]

    operations = [
        migrations.AddField(
            model_name="reglement",
            name="journal",
            field=models.CharField(
                default="CCO", max_length=5, verbose_name="Code du journal"
            ),
        ),
    ]
