# Generated by Django 3.2.25 on 2024-10-04 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dynamic_filenames


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0044_fournisseur_location_departement_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="FichierOrdreDeVirement",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nom", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("C", "Créé"),
                            ("T", "Transmis à la banque"),
                            ("V", "Virement validé"),
                        ],
                        default="C",
                        max_length=1,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "iban_copy",
                    models.TextField(
                        verbose_name="IBAN enregistré lors de la création de l'ordre de virement"
                    ),
                ),
                (
                    "bic_copy",
                    models.TextField(
                        verbose_name="BIC enregistré lors de la création de l'ordre de virement"
                    ),
                ),
                (
                    "nombre_transaction",
                    models.IntegerField(
                        verbose_name="Nombre de transaction pour l'ordre de virement"
                    ),
                ),
                (
                    "montant_total",
                    models.IntegerField(verbose_name="Montant total des transactions"),
                ),
                (
                    "tableau_virement_file",
                    models.FileField(
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="gestion/documents/ordre_de_virement/{instance.compte_emetteur}/{uuid:.2base32}-{uuid}{ext}"
                        ),
                        verbose_name="Tableau des virements",
                    ),
                ),
                (
                    "tableau_virement_gsheet",
                    models.URLField(
                        blank=True, null=True, verbose_name="Tableau GSheet"
                    ),
                ),
                (
                    "ordre_de_virement_out",
                    models.FileField(
                        null=True,
                        upload_to=dynamic_filenames.FilePattern(
                            filename_pattern="gestion/documents/ordre_de_virement/{instance.compte_emetteur}/{uuid:.2base32}-{uuid}{ext}"
                        ),
                        verbose_name="Ordre de virement",
                    ),
                ),
                (
                    "compte_emetteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion.compte",
                        verbose_name="Compte émetteur associé",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
