# Generated by Django 3.2.25 on 2024-06-11 12:47

import agir.lib.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0034_alter_document_type"),
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pollingstationofficer",
            name="polling_station_officer_unique_for_email",
        ),
        migrations.AlterField(
            model_name="pollingstationofficer",
            name="available_voting_dates",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("2022-06-12", "12 juin 2022 — 1er tour des législatives"),
                        ("2022-06-19", "19 juin 2022 — 2nd tour des législatives"),
                        (
                            "2024-06-09",
                            "Dimanche 9 juin 2024 (samedi 8 juin pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — Élections européennes 2024",
                        ),
                        (
                            "2024-06-30",
                            "Dimanche 30 juin 2024 (samedi 29 juin pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — 1er tour des législatives",
                        ),
                        (
                            "2024-07-07",
                            "Dimanche 7 juillet 2024 (samedi 6 juillet pour la Guadeloupe, la Martinique, la Guyane, la Polynésie française et les Français·es de l'étranger résidant sur le continent américain) — 2nd tour des législatives",
                        ),
                    ],
                    max_length=255,
                    verbose_name="date du scrutin",
                ),
                default=list,
                size=None,
                verbose_name="dates de disponibilité",
            ),
        ),
        migrations.AlterField(
            model_name="pollingstationofficer",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="polling_station_officer",
                related_query_name="polling_station_officer",
                to="people.person",
                verbose_name="personne",
            ),
        ),
        migrations.AddConstraint(
            model_name="pollingstationofficer",
            constraint=models.UniqueConstraint(
                fields=("contact_email", "available_voting_dates"),
                name="polling_station_officer_unique_for_email_and_dates",
            ),
        ),
    ]
