# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20170615_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='supportgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.SupportGroup'),
        ),
    ]
