# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_add_initial_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='supportgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='support_groups', through='groups.Membership', to='people.Person'),
        ),
    ]
