# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-15 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_supportgroup_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportgroup',
            options={'ordering': ('-created',), 'permissions': (('view_hidden_supportgroup', 'Peut afficher les groupes non publiés'),), 'verbose_name': "groupe d'appui", 'verbose_name_plural': "groupes d'appui"},
        ),
    ]
