# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-20 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170915_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroup',
            name='contact_hide_phone',
            field=models.BooleanField(default=False, verbose_name='Cacher mon numéro de téléphone'),
        )
    ]
