# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20170509_0938'),
        ('groups', '0005_auto_20170509_0938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportgroup',
            options={'ordering': ('-modified',), 'verbose_name': "groupe d'appui", 'verbose_name_plural': "groupes d'appui"},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('support_group', 'person')]),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(fields=['support_group', 'person'], name='groups_memb_support_d45f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='supportgroup',
            index=models.Index(fields=['nb_path'], name='groups_supp_nb_path_0a4cde_idx'),
        ),
    ]
