# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20170510_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportgroup',
            options={'ordering': ('-created',), 'verbose_name': "groupe d'appui", 'verbose_name_plural': "groupes d'appui"},
        ),
        migrations.RemoveIndex(
            model_name='membership',
            name='groups_memb_support_d45f7e_idx',
        ),
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='people.Person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='support_group',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.SupportGroup'),
        ),
    ]
