# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_supportgroup_coordinates_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='autre gestionnaire du groupe'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='is_referent',
            field=models.BooleanField(default=False, verbose_name='animateur du groupe'),
        ),
    ]
