# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170518_1509'),
        ('groups', '0008_auto_20170529_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='support_group',
            new_name='supportgroup',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('supportgroup', 'person')]),
        ),
    ]
