# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_auto_20170529_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='supportgroups', through='groups.Membership', to='people.Person'),
        ),
    ]
