# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 17:55
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_auto_20180125_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroupsubtype',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='supportgroupsubtype',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
