# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-14 11:49
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_supportgroupsubtype_icon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportgroupsubtype',
            name='color',
            field=models.CharField(blank=True, help_text='La couleur associée aux marqueurs sur la carte.', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')], verbose_name='couleur'),
        ),
    ]
