# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-14 17:26
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uris',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=4, verbose_name='URIs de redirection OAuth'),
        ),
    ]
