# Generated by Django 3.1.13 on 2021-11-10 10:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_contact'),
        ('groups', '0007_add_fields_to_membership'),
        ('msgs', '0003_create_supportgroupmessagerecipient_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportgroupmessage',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Objet'),
        ),
        migrations.CreateModel(
            name='SupportGroupOrganizationMessage',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date de création')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUID interne à l'API pour identifier la ressource", primary_key=True, serialize=False, verbose_name='UUID')),
                ('text', models.TextField(max_length=2000, verbose_name='Contenu')),
                ('image', stdimage.models.StdImageField(upload_to='')),
                ('deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.person', verbose_name='Auteur')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_organisation', to='people.person', verbose_name='Personne')),
                ('supportgroup', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='message_organisation', to='groups.supportgroup', verbose_name='Groupe / équipe')),
            ],
            options={
                'verbose_name': 'Message privé avec les animateur·ices de groupe',
            },
        ),
        migrations.AddConstraint(
            model_name='supportgrouporganizationmessage',
            constraint=models.UniqueConstraint(fields=('supportgroup', 'person'), name='unique_message_for_group_and_person'),
        ),
    ]
