# Generated by Django 3.1.11 on 2021-06-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0003_create_supportgroupmessagerecipient_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroupmessage",
            name="subject",
            field=models.TextField(
                blank=True, default="", max_length=2000, verbose_name="Objet"
            ),
        ),
    ]
