# Generated by Django 3.1.13 on 2021-11-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0004_supportgroupmessage_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroupmessage",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Supprimé"),
        ),
        migrations.AlterField(
            model_name="supportgroupmessagecomment",
            name="deleted",
            field=models.BooleanField(default=False, verbose_name="Supprimé"),
        ),
    ]
