# Generated by Django 3.1.13 on 2021-12-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0005_auto_20211116_1659"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroupmessage",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("Public", "Message de groupe"),
                    ("Private", "Message privé à certains rôles"),
                ],
                default="Public",
                max_length=64,
                verbose_name="message_type",
            ),
        ),
        migrations.AddField(
            model_name="supportgroupmessage",
            name="required_membership_type",
            field=models.CharField(
                choices=[
                    (5, "Abonné⋅e du groupe"),
                    (10, "Membre actif du groupe"),
                    (50, "Membre gestionnaire"),
                    (100, "Animateur⋅rice"),
                ],
                default=5,
                max_length=64,
                verbose_name="required_membershiptype",
            ),
        ),
    ]
