# Generated by Django 3.1.14 on 2022-02-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0007_supportgroupmessage_mutedlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroupmessage",
            name="is_locked",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Message verrouillé"
            ),
        ),
    ]
