# Generated by Django 3.2.12 on 2022-02-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0008_supportgroupmessage_is_locked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroupmessage",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="Message verrouillé"),
        ),
    ]
