# Generated by Django 3.2.17 on 2023-02-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("msgs", "0009_alter_supportgroupmessage_is_locked"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroupmessage",
            name="readonly",
            field=models.BooleanField(
                default=False,
                help_text="Le message s'affichera mais il ne sera pas possible d'y répondre",
                verbose_name="Message en lecture seule",
            ),
        ),
    ]
