# Generated by Django 3.2.23 on 2023-11-09 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0031_remove_unused_options_for_newsletters"),
        ("groups", "0018_membership_has_finance_managing_privilege"),
        ("msgs", "0010_supportgroupmessage_readonly"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportgroupmessage",
            options={
                "default_permissions": ("add", "change", "delete", "view"),
                "permissions": [
                    (
                        "send_supportgroupmessage",
                        "Peut créer et envoyer des messages aux groupes d'action",
                    )
                ],
                "verbose_name": "Message de groupe",
                "verbose_name_plural": "Messages de groupe",
            },
        ),
        migrations.AlterField(
            model_name="supportgroupmessage",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.person",
                verbose_name="Auteur",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroupmessage",
            name="required_membership_type",
            field=models.IntegerField(
                choices=[
                    (5, "Abonné⋅e du groupe"),
                    (10, "Membre actif du groupe"),
                    (50, "Membre gestionnaire"),
                    (100, "Animateur⋅rice"),
                ],
                default=5,
                verbose_name="Statut dans le groupe requis",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroupmessage",
            name="supportgroup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="messages",
                to="groups.supportgroup",
                verbose_name="Groupe / équipe",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroupmessagecomment",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.person",
                verbose_name="Auteur",
            ),
        ),
    ]
