# Generated by Django 3.2.23 on 2024-01-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("msgs", "0011_auto_20231109_1643"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroupmessage",
            name="text",
            field=models.TextField(max_length=3000, verbose_name="Contenu"),
        ),
        migrations.AlterField(
            model_name="supportgroupmessagecomment",
            name="text",
            field=models.TextField(max_length=3000, verbose_name="Contenu"),
        ),
    ]
