# Generated by Django 3.2.17 on 2023-02-15 11:21

import django.db.models.deletion
from django.db import migrations, models

import agir.lib.models
from agir.event_requests.actions import create_calendar_for_object


def create_calendars_for_existing_objects(apps, schema_editor):
    EventThemeType = apps.get_model("event_requests", "EventThemeType")
    EventTheme = apps.get_model("event_requests", "EventTheme")

    for obj in EventThemeType.objects.all():
        create_calendar_for_object(obj)
    for obj in EventTheme.objects.all():
        create_calendar_for_object(obj)


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0023_event_location_departement_id"),
        ("event_requests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventthemetype",
            name="calendar",
            field=models.OneToOneField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.calendar",
                verbose_name="Agenda",
            ),
        ),
        migrations.AddField(
            model_name="eventtheme",
            name="calendar",
            field=models.OneToOneField(
                default=None,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="events.calendar",
                verbose_name="Agenda",
            ),
        ),
        migrations.RunPython(
            create_calendars_for_existing_objects, migrations.RunPython.noop
        ),
        migrations.AddField(
            model_name="eventthemetype",
            name="event_speaker_request_email_body",
            field=agir.lib.models.DescriptionField(
                default="<p>Des nouvelles demandes d'événement où vous pouvez intervenir ont été faites.</p>",
                help_text="Ce texte sera utilisé comme corps de l'e-mail envoyé aux intervenant·es pour demander de renseigner leur disponibilité.",
                verbose_name="texte de l'e-mail aux intervenant·es",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventthemetype",
            name="event_speaker_request_email_subject",
            field=models.CharField(
                default="Demandes de formations locales sur vos thèmes",
                help_text="Ce texte sera utilisé comme objet de l'e-mail envoyé aux intervenant·es pour demander de renseigner leur disponibilité.",
                max_length=255,
                verbose_name="objet de l'e-mail aux intervenant·es",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventthemetype",
            name="event_speaker_request_email_from",
            field=models.EmailField(
                default="support@actionpopulaire.fr",
                help_text="Cette adresse sera utilisé comme expéditeur de l'e-mail envoyé aux intervenant·es pour demander de renseigner leur disponibilité.",
                max_length=255,
                verbose_name="expéditeur de l'e-mail aux intervenant·es",
            ),
        ),
    ]
