# Generated by Django 3.2.18 on 2023-03-30 13:29

import agir.lib.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_requests", "0005_auto_20230303_1653"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventtheme",
            name="unretained_speaker_event_creation_email_body",
            field=agir.lib.models.DescriptionField(
                blank=True,
                default="",
                help_text="Ce texte sera utilisé comme corps de l'e-mail envoyé aux intervenant·es disponibles mais non retenu·es lors de la création d'un événement. Le lien vers la page de l'événement sera automatiquement ajouté à la fin du message.",
                verbose_name="texte de l'e-mail aux intervenant·es non retenu·es",
            ),
        ),
        migrations.AddField(
            model_name="eventtheme",
            name="unretained_speaker_event_creation_email_subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ce texte sera utilisé comme objet de l'e-mail envoyé aux intervenant·es disponibles mais non retenu·es lors de la création d'un événement. Si vide, l'e-mail ne sera pas envoyé.",
                max_length=255,
                verbose_name="objet de l'e-mail aux intervenant·es non retenu·es",
            ),
        ),
    ]
