# Generated by Django 3.2.18 on 2023-04-18 08:34

import agir.lib.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_requests", "0006_eventtheme_unretained_speaker_email_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventthemetype",
            name="has_event_speaker_request_emails",
            field=models.BooleanField(
                default=True,
                help_text="Cocher la case pour qu'un e-mail de demande de disponibilité soit envoyé automatiquement aux intervenant·es lorsqu'une demande est créé pour l'un de leurs thèmes. Ne pas cocher pour pouvoir renseigner leurs disponibilités directement via l'admin",
                verbose_name="demander leur disponibilité aux intervenant·es",
            ),
        ),
        migrations.AlterField(
            model_name="eventthemetype",
            name="event_speaker_request_email_body",
            field=agir.lib.models.DescriptionField(
                blank=True,
                default="",
                help_text="Ce texte sera utilisé comme corps de l'e-mail envoyé aux intervenant·es pour demander de renseigner leur disponibilité.",
                verbose_name="texte de l'e-mail aux intervenant·es",
            ),
        ),
        migrations.AlterField(
            model_name="eventthemetype",
            name="event_speaker_request_email_subject",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Ce texte sera utilisé comme objet de l'e-mail envoyé aux intervenant·es pour demander de renseigner leur disponibilité.",
                max_length=255,
                verbose_name="objet de l'e-mail aux intervenant·es",
            ),
        ),
    ]
