# Generated by Django 3.2.18 on 2023-05-22 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0017_supportgroup_certification_date"),
        ("event_requests", "0009_event_image_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventthemetype",
            name="organizer_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Si un groupe est selectionné, il sera automatiquement indiqué comme organisateur de tous les événements de ce type",
                limit_choices_to={"published": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="groups.supportgroup",
                verbose_name="Groupe organisateur",
            ),
        ),
    ]
