# Generated by Django 3.1.13 on 2021-09-03 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0004_add_follower_membership_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportGroupExternalLink",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255, verbose_name="URL")),
                (
                    "label",
                    models.CharField(
                        help_text="Titre à afficher",
                        max_length=255,
                        verbose_name="titre",
                    ),
                ),
                (
                    "supportgroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        related_query_name="link",
                        to="groups.supportgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien ou réseau social de l’équipe",
                "verbose_name_plural": "Liens et réseaux sociaux de l’équipe",
            },
        ),
    ]
