# Generated by Django 3.1.14 on 2022-02-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0007_add_fields_to_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroup",
            name="is_messaging_enabled",
            field=models.BooleanField(
                default=True,
                help_text="La messagerie est activée ou non pour ce groupe.",
                verbose_name="Messagerie activée",
            ),
        ),
    ]
