# Generated by Django 3.1.14 on 2022-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0008_supportgroup_has_messages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportgroup",
            name="is_messaging_enabled",
        ),
        migrations.AddField(
            model_name="supportgroup",
            name="is_private_messaging_enabled",
            field=models.BooleanField(
                default=True,
                help_text="La messagerie privée est activée ou non pour ce groupe.",
                verbose_name="Messagerie privée activée",
            ),
        ),
    ]
