# Generated by Django 3.1.14 on 2022-02-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0008_supportgroup_has_messages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroup",
            name="is_private_messaging_enabled",
            field=models.BooleanField(
                default=True,
                help_text="La messagerie privée est activée ou non pour ce groupe.",
                verbose_name="Messagerie privée activée",
            ),
        ),
    ]
