# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("groups", "0008_change_vocabulary")]

    operations = [
        migrations.RemoveIndex(
            model_name="supportgroup", name="groups_supp_nb_path_0a4cde_idx"
        ),
        migrations.AddIndex(
            model_name="supportgroup",
            index=models.Index(fields=["nb_path"], name="groups_nb_path_index"),
        ),
    ]
