# Generated by Django 3.2.12 on 2022-04-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0009_auto_20220218_1043"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroup",
            name="open",
            field=models.BooleanField(
                default=True,
                help_text="Ce groupe peut-il ou pas accueilir des nouveaux membres ou abonné·es",
                verbose_name="ouvert",
            ),
        ),
    ]
