# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 11:11
from __future__ import unicode_literals

from django.db import migrations
from agir.lib import models as lib_models


class Migration(migrations.Migration):

    dependencies = [("groups", "0011_auto_20171106_1833")]

    operations = [
        migrations.AlterField(
            model_name="supportgroup",
            name="description",
            field=lib_models.DescriptionField(
                blank=True,
                help_text="Une description, en MarkDown",
                verbose_name="description",
            ),
        )
    ]
