# Generated by Django 3.2.16 on 2023-01-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0012_supportgroup_location_departement_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroup",
            name="editable",
            field=models.BooleanField(
                default=True,
                help_text="Les informations du groupe peuvent être éditées par ses animateur·ices et gestionnaires",
                verbose_name="éditable",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroup",
            name="is_private_messaging_enabled",
            field=models.BooleanField(
                default=True,
                help_text="La messagerie privée est activée pour le groupe",
                verbose_name="messagerie privée activée",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroup",
            name="open",
            field=models.BooleanField(
                default=True,
                help_text="Le groupe accueilir de nouveaux membres ou abonné·es",
                verbose_name="ouvert",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroup",
            name="published",
            field=models.BooleanField(
                default=True,
                help_text="Le groupe est visible publiquement",
                verbose_name="publié",
            ),
        ),
    ]
