# Generated by Django 3.2.18 on 2023-03-30 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0016_uncertifiablegroup"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="SupportGroupSupportGroupSubtype",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "supportgroup",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="groups.supportgroup",
                            ),
                        ),
                        (
                            "supportgroupsubtype",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                to="groups.supportgroupsubtype",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "groups_supportgroup_subtypes",
                    },
                ),
                migrations.AddConstraint(
                    model_name="supportgroupsupportgroupsubtype",
                    constraint=models.UniqueConstraint(
                        fields=("supportgroup_id", "supportgroupsubtype_id"),
                        name="groups_supportgroup_subt_supportgroup_id_supportg_f27eecfd_uniq",
                    ),
                ),
                migrations.AlterField(
                    model_name="supportgroup",
                    name="subtypes",
                    field=models.ManyToManyField(
                        blank=True,
                        related_name="supportgroups",
                        through="groups.SupportGroupSupportGroupSubtype",
                        to="groups.SupportGroupSubtype",
                    ),
                ),
            ]
        ),
        migrations.AddField(
            model_name="supportgroupsupportgroupsubtype",
            name="created",
            field=models.DateTimeField(
                blank=True,
                default=None,
                editable=False,
                null=True,
                verbose_name="date de création",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroup",
            name="subtypes",
            field=models.ManyToManyField(
                blank=True,
                related_name="supportgroups",
                to="groups.SupportGroupSubtype",
            ),
        ),
    ]
