# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 11:31
from __future__ import unicode_literals
from django.db import migrations
from agir.groups.models import SupportGroup as SupportGroupClass


def create_basic_subtypes(apps, schema_editor):
    SupportGroupSubtype = apps.get_model("groups", "SupportGroupSubtype")
    SupportGroup = apps.get_model("groups", "SupportGroup")
    subtypes = [
        {
            "label": "groupe local",
            "description": "Sous-groupe par défaut de tous les groupes locaux",
            "hide_text_label": True,
            "privileged_only": False,
            "color": "#0098b6",
            "type": SupportGroupClass.TYPE_LOCAL_GROUP,
        },
        {
            "label": "rédaction du livret",
            "description": "Groupe de rédaction du livret.",
            "privileged_only": True,
            "type": SupportGroupClass.TYPE_THEMATIC,
        },
    ]
    for subtype in subtypes:
        SupportGroupSubtype.objects.create(**subtype)

    local_groups = SupportGroup.objects.filter(type=SupportGroupClass.TYPE_LOCAL_GROUP)
    local_groups_subtype = SupportGroupSubtype.objects.get(label="groupe local")
    local_groups_subtype.supportgroups.set(local_groups)

    booklets = SupportGroup.objects.filter(type=SupportGroupClass.TYPE_THEMATIC)
    booklet_groups_subtype = SupportGroupSubtype.objects.get(
        label="rédaction du livret"
    )
    booklet_groups_subtype.supportgroups.set(booklets)


def remove_basic_subtypes(apps, schema_editor):
    SupportGroupSubtype = apps.get_model("groups", "SupportGroupSubtype")
    SupportGroupSubtype.objects.get(label="groupe local").delete()
    SupportGroupSubtype.objects.get(label="rédaction du livret").delete()


class Migration(migrations.Migration):
    dependencies = [("groups", "0017_auto_20171214_1306")]

    operations = [
        migrations.RunPython(create_basic_subtypes, reverse_code=remove_basic_subtypes)
    ]
