# Generated by Django 3.2.19 on 2023-06-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("groups", "0017_supportgroup_certification_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="has_finance_managing_privilege",
            field=models.BooleanField(
                default=True,
                editable=False,
                help_text="La valeur de ce champ indique si la personne aura le droit de gérer les finances du groupe et de créer/suivre/valider des demandes de dépense. N.B. Cette propriété est valable uniquement pour les gestionnaires et animateur·ices du groupe",
                verbose_name="Accès à la gestion des finances du groupe",
            ),
        ),
    ]
