# Generated by Django 3.2.23 on 2023-11-29 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.NUNTIUS_SEGMENT_MODEL),
        ("groups", "0018_membership_has_finance_managing_privilege"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportgroup",
            name="membership_segment",
            field=models.ForeignKey(
                blank=True,
                help_text="Segment qui sera utilisé pour déterminer les membres du groupe. Les membres existants ne faisant pas partie du segment seront automatiquement supprimés.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.NUNTIUS_SEGMENT_MODEL,
                verbose_name="Segment d'adhésion",
            ),
        ),
    ]
