# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-21 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_auto_20171220_1737'),
        ('groups', '0018_create_groupsubtypes'),
    ]

    operations = [
    ]
