# Generated by Django 2.0.9 on 2018-10-24 15:57

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_supportgroupsubtype_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportgroupsubtype',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Configuration'),
        ),
    ]
