# Generated by Django 2.1.4 on 2018-12-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("groups", "0028_auto_20181024_1757")]

    operations = [
        migrations.AddField(
            model_name="supportgroupsubtype",
            name="allow_external",
            field=models.BooleanField(
                default=False, verbose_name="Les non-insoumis⋅es peuvent rejoindre"
            ),
        ),
        migrations.AddField(
            model_name="supportgroupsubtype",
            name="external_help_text",
            field=models.TextField(
                blank=True,
                verbose_name="Phrase d'explication pour rejoindre le groupe ou l'évènement",
            ),
        ),
    ]
