# Generated by Django 2.2 on 2019-04-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("groups", "0033_auto_20190313_1842")]

    operations = [
        migrations.AlterField(
            model_name="supportgroup",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="groups", to="groups.SupportGroupTag"
            ),
        )
    ]
