# Generated by Django 2.2.4 on 2019-09-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("groups", "0034_auto_20190419_1153")]

    operations = [
        migrations.CreateModel(
            name="ThematicGroup",
            fields=[],
            options={
                "verbose_name": "Groupe thématique",
                "verbose_name_plural": "Groupes thématiques",
                "proxy": True,
                "default_permissions": ("view", "change"),
                "indexes": [],
                "constraints": [],
            },
            bases=("groups.supportgroup",),
        )
    ]
