# Generated by Django 2.2.4 on 2019-09-02 10:43

from django.db import migrations


ADD_FRENCH_UNACCENTED = """
CREATE TEXT SEARCH CONFIGURATION french_unaccented (COPY = french);
ALTER TEXT SEARCH CONFIGURATION french_unaccented
    ALTER MAPPING FOR
        asciiword, asciihword, hword_asciipart,
         word, hword, hword_part
    WITH unaccent, french_stem;  
"""

DROP_FRENCH_UNACCENTED = """
DROP TEXT SEARCH CONFIGURATION french_unaccented;
"""

SEARCH_COLUMN = """
setweight(to_tsvector('french_unaccented', COALESCE("name", '')), 'A')
|| setweight(to_tsvector('french_unaccented', COALESCE("location_city", '')), 'B')
|| setweight(to_tsvector('french_unaccented', COALESCE("location_zip", '')), 'B')
|| setweight(to_tsvector('french_unaccented', COALESCE("description", '')), 'C')
"""


ADD_GROUP_TEXT_SEARCH_INDEX = f"""
-- noinspection SqlResolve
CREATE INDEX groups_supportgroup_search ON groups_supportgroup USING GIN (({SEARCH_COLUMN}));
"""

DROP_GROUP_TEXT_SEARCH_INDEX = """
DROP INDEX groups_supportgroup_search;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0035_thematicgroup"),
        ("people", "0060_personform_segment"),
    ]

    operations = [
        migrations.RunSQL(
            sql=ADD_FRENCH_UNACCENTED, reverse_sql=DROP_FRENCH_UNACCENTED
        ),
        migrations.RunSQL(
            sql=ADD_GROUP_TEXT_SEARCH_INDEX, reverse_sql=DROP_GROUP_TEXT_SEARCH_INDEX
        ),
    ]
