# Generated by Django 3.1.2 on 2020-10-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0040_auto_20200702_1627"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroupsubtype",
            name="config",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Configuration"
            ),
        ),
    ]
