# Generated by Django 3.1.3 on 2020-11-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0041_auto_20201021_1525"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("L", "Groupe local"),
                    ("B", "Groupe thématique"),
                    ("F", "Groupe fonctionnel"),
                    ("P", "Groupe professionel"),
                    ("2", "Groupe de soutien « Nous Sommes Pour ! »"),
                ],
                default="L",
                max_length=1,
                verbose_name="type de groupe",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroupsubtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("L", "Groupe local"),
                    ("B", "Groupe thématique"),
                    ("F", "Groupe fonctionnel"),
                    ("P", "Groupe professionel"),
                    ("2", "Groupe de soutien « Nous Sommes Pour ! »"),
                ],
                max_length=1,
                verbose_name="type de groupe",
            ),
        ),
    ]
