# Generated by Django 3.1.3 on 2020-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0042_auto_20201126_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroup",
            name="name",
            field=models.CharField(
                help_text="Le nom du groupe", max_length=255, verbose_name="nom"
            ),
        ),
    ]
