# Generated by Django 3.1.3 on 2020-12-10 10:01

from django.db import migrations, models


def add_default_2022_subtype(apps, schema):
    SupportGroupSubtype = apps.get_model("groups", "SupportGroupSubtype")
    SupportGroupSubtype.objects.create(
        label="équipe de soutien",
        description="Sous-type par défaut des équipes de soutien",
        hide_text_label=True,
        visibility="A",  # all
        color="#571aff",
        type="2",  # campagne 2022
    )


def remove_default_2022_subtype(apps, schema):
    SupportGroupSubtype = apps.get_model("groups", "SupportGroupSubtype")
    SupportGroupSubtype.objects.filter(label="équipe de soutien").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0043_auto_20201207_1450"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("L", "Groupe local"),
                    ("B", "Groupe thématique"),
                    ("F", "Groupe fonctionnel"),
                    ("P", "Groupe professionel"),
                    ("2", "Équipe de soutien « Nous Sommes Pour ! »"),
                ],
                default="L",
                max_length=1,
                verbose_name="type de groupe",
            ),
        ),
        migrations.AlterField(
            model_name="supportgroupsubtype",
            name="type",
            field=models.CharField(
                choices=[
                    ("L", "Groupe local"),
                    ("B", "Groupe thématique"),
                    ("F", "Groupe fonctionnel"),
                    ("P", "Groupe professionel"),
                    ("2", "Équipe de soutien « Nous Sommes Pour ! »"),
                ],
                max_length=1,
                verbose_name="type de groupe",
            ),
        ),
        migrations.RunPython(
            code=add_default_2022_subtype, reverse_code=remove_default_2022_subtype
        ),
    ]
