# Generated by Django 3.1.3 on 2020-12-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0074_person_referrer_id"),
        ("groups", "0044_auto_20201210_1101"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferOperation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Heure de l'opération"
                    ),
                ),
                (
                    "former_group",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="groups.supportgroup",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="people.person",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        editable=False,
                        related_name="_tranferoperation_members_+",
                        to="people.Person",
                    ),
                ),
                (
                    "new_group",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="groups.supportgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfert de membres",
                "verbose_name_plural": "Transferts de membres",
                "ordering": ("timestamp", "former_group"),
            },
        ),
    ]
