# Generated by Django 3.2.12 on 2022-03-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20211027_1611"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="location_state",
            new_name="location_country_name",
        ),
    ]
