# Generated by Django 2.0.5 on 2018-06-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20180418_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='people.Person'),
        ),
    ]
