# Generated by Django 2.0.6 on 2018-06-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("payments", "0004_auto_20180531_1251")]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="mode",
            field=models.CharField(max_length=70, verbose_name="Mode de paiement"),
        )
    ]
