# Generated by Django 3.2.20 on 2023-10-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_subscription_month_of_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="effect_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Début de l'abonnement"
            ),
        ),
    ]
