# Generated by Django 2.0.6 on 2018-07-24 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("payments", "0006_auto_20180628_1503")]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="people.Person",
            ),
        )
    ]
