# Generated by Django 2.2.3 on 2019-07-24 14:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0057_auto_20190704_1203"),
        ("payments", "0012_change_europeennes_dons"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(auto_now=True, verbose_name="modified"),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="Jour du mois",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        editable=False, verbose_name="prix en centimes d'euros"
                    ),
                ),
                ("type", models.CharField(max_length=255, verbose_name="Type")),
                (
                    "mode",
                    models.CharField(max_length=70, verbose_name="Mode de paiement"),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Souscription en attente"),
                            (1, "Souscription active"),
                            (2, "Souscription abandonnée"),
                            (3, "Souscription annulée"),
                            (4, "Souscription refusée"),
                            (5, "Souscription désactivée"),
                        ],
                        default=0,
                        verbose_name="status",
                    ),
                ),
                (
                    "meta",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fin de l'abonnement"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="people.Person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement récurrent",
                "verbose_name_plural": "Paiements récurrents",
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="payments.Subscription",
            ),
        ),
    ]
