# Generated by Django 2.2.3 on 2019-07-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("payments", "0013_auto_20190724_1628")]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"get_latest_by": "created", "ordering": ("-created",)},
        )
    ]
