# Generated by Django 2.2.3 on 2019-08-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("payments", "0014_auto_20190726_1503")]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "get_latest_by": "created",
                "ordering": ("-created",),
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
            },
        )
    ]
