# Generated by Django 2.2.3 on 2019-08-21 09:32

import agir.payments.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("payments", "0015_auto_20190820_1859")]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="price",
            field=agir.payments.model_fields.AmountField(verbose_name="Prix"),
        )
    ]
