# Generated by Django 2.2.14 on 2020-07-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0018_auto_20200701_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Souscription en attente de confirmation par SystemPay"),
                    (1, "Souscription active"),
                    (2, "Souscription abandonnée avant complétion par la personne"),
                    (3, "Souscription refusée côté FI"),
                    (4, "Souscription refusée côté banque"),
                    (5, "Souscription terminée"),
                ],
                default=0,
                verbose_name="status",
            ),
        ),
    ]
