# Generated by Django 2.2.14 on 2020-08-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0019_auto_20200730_1744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Paiement en attente"),
                    (1, "Paiement terminé"),
                    (2, "Paiement abandonné en cours"),
                    (3, "Paiement annulé avant encaissement"),
                    (4, "Paiement refusé par votre banque"),
                    (-1, "Paiement remboursé"),
                ],
                default=0,
                verbose_name="status",
            ),
        ),
    ]
