# Generated by Django 3.1.2 on 2020-10-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0020_auto_20200817_1841"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="events",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Événements de paiement"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="payment",
            name="type",
            field=models.CharField(choices=[], max_length=255, verbose_name="type"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="meta",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
