# Generated by Django 3.1.3 on 2021-01-06 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0021_auto_20201021_1525"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="location_address",),
    ]
