# Generated by Django 2.1.5 on 2019-02-08 13:49

import nuntius.models
from django.contrib.gis.db.models.fields import PolygonField
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("people", "0050_auto_20190128_1550")]

    operations = [
        migrations.CreateModel(
            name="Segment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                (
                    "support_group_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("m", "Membres de GA"),
                            ("M", "Animateurices et gestionnaires de GA"),
                            ("R", "Animateurices de GA"),
                        ],
                        max_length=1,
                        verbose_name="Statut GA",
                    ),
                ),
                (
                    "area",
                    PolygonField(
                        blank=True, null=True, srid=4326, verbose_name="Territoire"
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="people.PersonTag")),
            ],
            bases=(nuntius.models.BaseSegment, models.Model),
        )
    ]
