# Generated by Django 2.2.4 on 2019-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_creer_modeles"),
        ("mailing", "0002_auto_20190308_1859"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="events",
            field=models.ManyToManyField(
                blank=True,
                to="events.Event",
                verbose_name="Limiter aux participant⋅e⋅s à un des événements",
            ),
        )
    ]
