# Generated by Django 2.2.5 on 2019-10-01 14:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("mailing", "0004_auto_20190918_1530")]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="area",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True, null=True, srid=4326, verbose_name="Territoire"
            ),
        )
    ]
