# Generated by Django 2.2.5 on 2019-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0077_auto_20190820_1233"),
        ("mailing", "0005_auto_20191001_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="events_end_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Limiter aux participant⋅e⋅s à des évènements terminant avant cette date",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="events_start_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Limiter aux participant⋅e⋅s à des évènements commençant après cette date",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="events_subtypes",
            field=models.ManyToManyField(
                blank=True,
                to="events.EventSubtype",
                verbose_name="Limiter aux participant⋅e⋅s à un évènements de ce type",
            ),
        ),
    ]
