# Generated by Django 2.2.5 on 2019-10-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0005_auto_20191001_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="events_end_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Limiter aux participant⋅e⋅s à des événements terminant avant cette date",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="events_start_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Limiter aux participant⋅e⋅s à des événements commençant après cette date",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="events_subtypes",
            field=models.ManyToManyField(
                blank=True,
                to="events.EventSubtype",
                verbose_name="Limiter aux participant⋅e⋅s à un événements de ce type",
            ),
        ),
    ]
