# Generated by Django 2.2.5 on 2019-10-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mailing", "0006_auto_20191002_1752")]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="events_organizer",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Limiter aux organisateurices (sans effet si pas d'autres filtres événements)",
            ),
        )
    ]
