# Generated by Django 2.2.6 on 2019-11-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nuntius", "0016_indices_and_ordering"),
        ("mailing", "0007_segment_events_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="sent_to_segments",
                to="nuntius.Campaign",
                verbose_name="Limiter aux participants ayant reçu une des campagnes",
            ),
        )
    ]
