# Generated by Django 2.2.7 on 2019-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mailing", "0008_segment_campaigns")]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="sent_to_segments",
                to="nuntius.Campaign",
                verbose_name="Limiter aux personnes ayant reçu une des campagnes",
            ),
        )
    ]
