# Generated by Django 2.2.8 on 2019-12-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mailing", "0009_auto_20191119_1418")]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="supportgroup_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N", "Non membres de GA"),
                    ("m", "Membres de GA"),
                    ("M", "Animateur·ices et gestionnaires de GA"),
                    ("R", "Animateur·ices de GA"),
                ],
                max_length=1,
                verbose_name="Limiter aux membres de groupes ayant ce statut",
            ),
        )
    ]
