# Generated by Django 2.2.8 on 2019-12-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mailing", "0010_auto_20191206_1714")]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("F", "Femme"), ("M", "Homme"), ("O", "Autre/Non défini")],
                max_length=1,
                verbose_name="Genre",
            ),
        )
    ]
