# Generated by Django 2.2.8 on 2019-12-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mailing", "0012_segment_exclude_segments")]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="_segment_campaigns_+",
                to="nuntius.Campaign",
                verbose_name="Limiter aux personnes ayant reçu une des campagnes",
            ),
        )
    ]
