# Generated by Django 2.2.8 on 2019-12-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mailing", "0015_auto_20191209_1229")]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="subscription",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="A une souscription mensuelle active",
            ),
        )
    ]
