# Generated by Django 2.2.8 on 2020-01-17 14:20

import agir.payments.model_fields
import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mailing", "0020_auto_20191213_1608")]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="donation_not_after",
            field=models.DateField(
                blank=True,
                help_text="Écrivez en toute lettre JJ/MM/AAAA plutôt qu'avec le widget, ça ira plus vite.",
                null=True,
                verbose_name="N'a pas fait de don (don mensuel inclus) depuis le",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="donation_total_max",
            field=agir.payments.model_fields.AmountField(
                blank=True,
                null=True,
                verbose_name="Montant total des dons inférieur ou égal à",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="donation_total_min",
            field=agir.payments.model_fields.AmountField(
                blank=True,
                null=True,
                verbose_name="Montant total des dons supérieur ou égal à",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="donation_total_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True,
                help_text="Écrire sous la forme JJ/MM/AAAA. La date de début est incluse, pas la date de fin.",
                null=True,
                verbose_name="Pour le filtre de montant total, prendre uniquement en compte les dons entre ces deux dates",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="donation_after",
            field=models.DateField(
                blank=True,
                help_text="Écrivez en toute lettre JJ/MM/AAAA plutôt qu'avec le widget, ça ira plus vite.",
                null=True,
                verbose_name="A fait au moins un don (don mensuel inclus) après le",
            ),
        ),
    ]
