# Generated by Django 2.2.8 on 2020-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("mailing", "0022_segment_force_non_insoumis")]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="campaigns_feedback",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "Personnes ayant ouvert"),
                    (2, "Personnes ayant cliqué"),
                    (3, "Personnes n'ayant pas ouvert"),
                    (4, "Personnes n'ayant pas cliqué"),
                    (5, "Personnes ayant ouvert mais pas cliqué"),
                ],
                help_text="Aucun effet si aucune campagne n'est sélectionnée dans le champ précédent",
                null=True,
                verbose_name="Limiter en fonction de la réaction à ces campagnes",
            ),
        )
    ]
