# Generated by Django 2.2.10 on 2020-02-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0023_segment_campaigns_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="forms",
            field=models.ManyToManyField(
                blank=True,
                related_name="_segment_forms_+",
                to="people.PersonForm",
                verbose_name="A répondu à au moins un de ces formulaires",
            ),
        )
    ]
