# Generated by Django 2.2.16 on 2020-09-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0027_segment_polls"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="last_click",
            field=models.DurationField(
                blank=True,
                null=True,
                verbose_name="Limiter aux personnes ayant cliqué dans un email envoyé au court de la durée indiquée",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="last_open",
            field=models.DurationField(
                blank=True,
                null=True,
                verbose_name="Limiter aux personnes ayant ouvert un email envoyé au court de la durée indiquée",
            ),
        ),
    ]
