# Generated by Django 2.2.16 on 2020-10-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0029_last_click_to_integer"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="draw_status",
            field=models.NullBooleanField(
                default=None,
                verbose_name="Limiter aux gens dont l'inscription au tirage au sort est",
            ),
        ),
    ]
