# Generated by Django 3.1.2 on 2020-11-06 18:08

import agir.lib.model_fields
import agir.mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0033_segment_newsletters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LFI", "Lettre d'information de la France insoumise"),
                        ("2022", "Lettre d'information de"),
                        ("NSP_en_ligne", "NSP en ligne"),
                        ("NSP_chez_moi", "NSP près de chez moi"),
                        ("NSP_programme", "NSP programme"),
                    ],
                    max_length=255,
                ),
                default=agir.mailing.models.default_newsletters,
                help_text="Inclure les personnes abonnées aux newsletters suivantes",
                size=None,
            ),
        ),
    ]
