# Generated by Django 3.1.2 on 2020-11-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0034_auto_20201107_1115"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="segment",
            name="force_non_insoumis",
        ),
        migrations.AddField(
            model_name="segment",
            name="is_2022",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Inscrits NSP"
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="is_insoumise",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="Inscrits LFI"
            ),
        ),
    ]
