# Generated by Django 3.1.3 on 2020-11-21 12:20

import agir.lib.model_fields
import agir.mailing.models
from django.db import migrations, models


def ntoblank(apps, schema_editor):
    Segment = apps.get_model("mailing", "Segment")
    Segment.objects.filter(elu="N").update(elu="")


def blankton(apps, schema_editor):
    Segment = apps.get_model("mailing", "Segment")
    Segment.objects.filter(elu="").update(elu="N")


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0035_auto_20201112_1156"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="elu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Peu importe"),
                    ("M", "Uniquement les membres du réseau des élus"),
                    (
                        "R",
                        "Tous les élus, membres ou non du réseau, sauf les exclus du réseau",
                    ),
                ],
                max_length=1,
                verbose_name="Est un élu",
            ),
        ),
        migrations.RunPython(ntoblank, blankton),
        migrations.AlterField(
            model_name="segment",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LFI", "Lettre d'information de la France insoumise"),
                        ("2022", "Lettre d'information NSP"),
                        ("2022_exceptionnel", "NSP : informations exceptionnelles"),
                        ("2022_en_ligne", "NSP actions en ligne"),
                        ("2022_chez_moi", "NSP agir près de chez moi"),
                        ("2022_programme", "NSP processus programme"),
                    ],
                    max_length=255,
                ),
                default=agir.mailing.models.default_newsletters,
                help_text="Inclure les personnes abonnées aux newsletters suivantes",
                size=None,
            ),
        ),
    ]
