# Generated by Django 3.1.3 on 2020-12-08 17:07

import agir.lib.model_fields
import agir.mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0036_auto_20201121_1320"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LFI", "Lettre d'information de la France insoumise"),
                        ("2022", "Lettre d'information NSP"),
                        ("2022_exceptionnel", "NSP : informations exceptionnelles"),
                        ("2022_en_ligne", "NSP actions en ligne"),
                        ("2022_chez_moi", "NSP agir près de chez moi"),
                        ("2022_programme", "NSP processus programme"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=agir.mailing.models.default_newsletters,
                help_text="Inclure les personnes abonnées aux newsletters suivantes.",
                size=None,
            ),
        ),
    ]
