# Generated by Django 3.1.7 on 2021-03-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0037_empty_newsletters"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="registration_duration",
            field=models.IntegerField(
                blank=True,
                help_text="Indiquer le nombre d'heures",
                null=True,
                verbose_name="Limiter aux membres inscrit⋅e⋅s depuis au moins un certain nombre d'heures",
            ),
        ),
    ]
