# Generated by Django 3.1.12 on 2021-06-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0038_segment_registration_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="elu_consulaire",
            field=models.BooleanField(
                default=True, verbose_name="Avec un mandat consulaire"
            ),
        ),
    ]
