# Generated by Django 3.1.13 on 2021-09-28 14:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0039_segment_elu_consulaire"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="countries",
            field=django_countries.fields.CountryField(
                blank=True,
                max_length=754,
                multiple=True,
                verbose_name="Limiter aux pays",
            ),
        ),
    ]
