# Generated by Django 3.2.12 on 2022-04-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0040_update_segment_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="registration_date_before",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Limiter aux membres inscrit⋅e⋅s avant cette date",
            ),
        ),
    ]
