# Generated by Django 3.2.16 on 2022-12-19 13:51

import agir.lib.model_fields
import agir.mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0043_alter_segment_elu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LFI", "Lettre d'information de la France insoumise"),
                        ("LJI", "Informations jeunes insoumis"),
                        ("2022", "Lettre d'information NSP"),
                        ("2022_exceptionnel", "NSP : informations exceptionnelles"),
                        ("2022_en_ligne", "NSP actions en ligne"),
                        ("2022_chez_moi", "NSP agir près de chez moi"),
                        ("2022_programme", "NSP processus programme"),
                        ("2022_liaison", "NSP Correspondant·e d'immeuble ou de rue"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=agir.mailing.models.default_newsletters,
                help_text="Inclure les personnes abonnées aux newsletters suivantes.",
                size=None,
            ),
        ),
    ]
