# Generated by Django 3.2.16 on 2023-01-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0011_alter_supportgroup_image"),
        ("mailing", "0044_alter_segment_newsletters"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="supportgroups",
            field=models.ManyToManyField(
                blank=True,
                to="groups.SupportGroup",
                verbose_name="Limiter aux membres d'un de ces groupes",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="supportgroup_subtypes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Ce filtre ne sera pas appliqué lorsque le filtre 'Limiter aux membres d'un de ces groupes' est actif",
                to="groups.SupportGroupSubtype",
                verbose_name="Limiter aux membres de groupes d'un de ces sous-types",
            ),
        ),
    ]
