# Generated by Django 3.2.16 on 2023-01-12 11:11

import agir.lib.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0020_person_location_departement_id"),
        ("mailing", "0045_add_segment_supportgroups_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="person_qualification_status",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("E", "Statut effectif"),
                        ("P", "Statut passé"),
                        ("F", "Statut futur"),
                    ],
                    max_length=1,
                ),
                blank=True,
                default=list,
                help_text="Si un type de statut est indiqué, limiter aux personnes dont les statuts de ce type sont dans l'un des états choisis",
                size=None,
                verbose_name="État du statut",
            ),
        ),
        migrations.AddField(
            model_name="segment",
            name="qualifications",
            field=models.ManyToManyField(
                blank=True, to="people.Qualification", verbose_name="Type de statut"
            ),
        ),
    ]
