# Generated by Django 3.2.16 on 2023-01-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0020_person_location_departement_id"),
        ("mailing", "0046_add_segment_person_qualifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="excluded_tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Limite le segment aux personnes n'ayant pas les tags sélectionnés (l'exclusion d'un tag aura la précédence sur son inclusion)",
                related_name="_mailing_segment_excluded_tags_+",
                to="people.PersonTag",
                verbose_name="Tags à exclure",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Limiter le segment aux personnes ayant les tags sélectionnés",
                to="people.PersonTag",
            ),
        ),
    ]
