# Generated by Django 3.2.18 on 2023-03-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0025_eventsubtype_is_acceptable_for_group_certification"),
        ("mailing", "0047_segment_excluded_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="excluded_events",
            field=models.ManyToManyField(
                blank=True,
                related_name="_mailing_segment_excluded_events_+",
                related_query_name="+",
                to="events.Event",
                verbose_name="Exclure les participant⋅e⋅s à un des événements",
            ),
        ),
    ]
