# Generated by Django 3.2.18 on 2023-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0049_auto_20230405_1359"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="elu_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INC", "Personne à contacter"),
                    ("DEM", "Mandat ajouté par la personne via son profil"),
                    ("IMP", "Importé par une opération automatique"),
                    ("FXP", "Faux-positif ou fausse déclaration"),
                    ("INS", "Mandat vérifié et confirmé"),
                ],
                default=None,
                help_text="Indique la qualité de l'information d'un·e élu⋅e, indépendamment des questions politiques et de son appartenance au réseau des élus. Une valeur « Vérifié » signifie que : 1) il a été vérifié que le mandat existe réellement et 2) le compte éventuellement associé appartient bien à la personne élue.",
                max_length=3,
                null=True,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="elu",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Peu importe"),
                    ("M", "Uniquement les membres du réseau des élu·es"),
                    ("E", "Tous les élu·es, sauf les exclus du réseau"),
                    (
                        "R",
                        "Les membres du réseau plus tout ceux à qui on a pas encore demandé",
                    ),
                ],
                max_length=1,
                verbose_name="Est un·e élu·e",
            ),
        ),
    ]
