# Generated by Django 3.2.19 on 2023-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0050_auto_20230412_1431"),
    ]

    operations = [
        migrations.AddField(
            model_name="segment",
            name="is_political_support",
            field=models.BooleanField(
                blank=True, default=None, null=True, verbose_name="Soutiens politiques"
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="is_2022",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Soutiens Mélenchon 2022",
            ),
        ),
        migrations.AlterField(
            model_name="segment",
            name="is_insoumise",
            field=models.BooleanField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Anciens soutiens de la France insoumise",
            ),
        ),
    ]
