# Generated by Django 3.2.19 on 2023-06-29 10:37

import agir.lib.model_fields
import agir.mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0051_auto_20230607_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        ("LFI", "Lettre d'information de la France insoumise"),
                        ("LJI", "Informations jeunes insoumis"),
                        ("2022", "Lettre d'information NSP"),
                        ("2022_exceptionnel", "NSP : informations exceptionnelles"),
                        ("2022_en_ligne", "NSP actions en ligne"),
                        ("2022_chez_moi", "NSP agir près de chez moi"),
                        ("2022_programme", "NSP processus programme"),
                        ("2022_liaison", "NSP Correspondant·e d'immeuble ou de rue"),
                        (
                            "LFI_reguliere",
                            "Les informations régulières de la France insoumise",
                        ),
                        (
                            "LFI_exceptionnelle",
                            "Les informations exceptionnelles de la France insoumise",
                        ),
                        (
                            "LFI_jeunes_insoumises",
                            "Les informations destinées aux Jeunes insoumis·es",
                        ),
                        ("LFI_liaisons", "Correspondant·es d'immeuble ou de rue"),
                        ("ILB", "Les informations de l'Institut La Boétie"),
                        ("ELUES", "Les informations destinées aux élu·es"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=agir.mailing.models.default_newsletters,
                help_text="Inclure les personnes abonnées aux newsletters suivantes.",
                size=None,
            ),
        ),
    ]
