# Generated by Django 3.2.23 on 2024-01-26 16:15

import agir.lib.model_fields
import agir.mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0053_remove_unused_options_for_newsletters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="segment",
            name="newsletters",
            field=agir.lib.model_fields.ChoiceArrayField(
                base_field=models.CharField(
                    choices=[
                        (
                            "LFI_reguliere",
                            "Les informations régulières de la France insoumise",
                        ),
                        (
                            "LFI_exceptionnelle",
                            "Les informations exceptionnelles de la France insoumise",
                        ),
                        (
                            "LFI_jeunes_insoumises",
                            "Les informations destinées aux Jeunes insoumis·es",
                        ),
                        ("LFI_liaisons", "Relai insoumis"),
                        ("ILB", "Les informations de l'Institut La Boétie"),
                        ("ELUES", "Les informations destinées aux élu·es"),
                    ],
                    max_length=255,
                ),
                blank=True,
                default=agir.mailing.models.default_newsletters,
                help_text="Inclure les personnes abonnées aux newsletters suivantes.",
                size=None,
            ),
        ),
    ]
