# Generated by Django 2.0.6 on 2018-06-15 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20180615_1804')
    ]

    operations = [
    ]
