# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 15:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("polls", "0002_auto_20171107_1111")]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="rules",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default={},
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Les règles du vote",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pollchoice",
            name="selection",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
