# Generated by Django 2.0.5 on 2018-06-01 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("polls", "0006_auto_20171114_1128")]

    operations = [
        migrations.AlterField(
            model_name="pollchoice",
            name="person",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.Person",
            ),
        )
    ]
