# Generated by Django 2.1.3 on 2018-11-28 15:16

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("polls", "0009_auto_20180724_2040")]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="rules",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                help_text="Un object JSON décrivant les règles. Actuellement, sont reconnues `options`,`min_options`, `max_options` et `verified_user`",
                verbose_name="Les règles du vote",
            ),
        )
    ]
