# Generated by Django 2.2.14 on 2020-07-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0014_auto_20200701_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="polls",
                related_query_name="poll",
                to="people.PersonTag",
                verbose_name="Tag à ajouter aux participant⋅es",
            ),
        ),
    ]
