# Generated by Django 2.2.14 on 2020-07-02 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.NUNTIUS_SEGMENT_MODEL),
        ("polls", "0015_auto_20200702_1800"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="authorized_segment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="+",
                to=settings.NUNTIUS_SEGMENT_MODEL,
                verbose_name="Limiter l'accès à la consultation à ce segment",
            ),
        ),
    ]
