# Generated by Django 2.2 on 2019-04-23 15:48

import agir.lib.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0054_person_subscribed_sms"),
        ("mailing", "0002_auto_20190308_1859"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    agir.lib.models.DescriptionField(
                        verbose_name="Contenu de la notification"
                    ),
                ),
                ("link", models.URLField(verbose_name="Lien")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de début"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de fin"
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Segment des personnes auquel ce message sera montré (laisser vide pour montrer à tout le monde)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        related_query_name="notification",
                        to="mailing.Segment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ("start_date", "end_date"),
            },
        ),
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("S", "Vu"), ("C", "C")],
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        related_query_name="status",
                        to="notifications.Notification",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_statuses",
                        related_query_name="notification_status",
                        to="people.Person",
                    ),
                ),
            ],
            options={"unique_together": {("notification", "person")}},
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["start_date", "end_date"], name="notification_query_index"
            ),
        ),
    ]
