# Generated by Django 2.2.2 on 2019-06-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("notifications", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="icon",
            field=models.CharField(
                default="circle", max_length=200, verbose_name="icône"
            ),
        )
    ]
