# Generated by Django 2.2.2 on 2019-06-14 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("notifications", "0002_notification_icon")]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ("-start_date", "-end_date"),
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="icon",
            field=models.CharField(
                default="envelope",
                help_text='Indiquez le nom d\'une icône dans <a href="https://fontawesome.com/v4.7.0/icons/">cette liste</a>',
                max_length=200,
                verbose_name="icône",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.URLField(blank=True, verbose_name="Lien"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="start_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date de début"
            ),
        ),
    ]
