# Generated by Django 2.2.13 on 2020-06-12 15:50

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_auto_20191127_1638"),
    ]

    operations = [
        migrations.RemoveIndex(model_name="notification", name="internal_links",),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                condition=models.Q(link__startswith=settings.FRONT_DOMAIN),
                fields=["link"],
                name="internal_links",
            ),
        ),
    ]
