# Generated by Django 3.1.2 on 2020-10-23 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0006_auto_20200701_1622"),
    ]

    operations = [
        migrations.DeleteModel(name="Notification",),
    ]
