# Generated by Django 3.1.7 on 2021-03-30 20:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("push_notifications", "0007_uniquesetting"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebPushDevice",
            fields=[],
            options={"proxy": True, "indexes": [], "constraints": [],},
            bases=("push_notifications.webpushdevice",),
        ),
        migrations.CreateModel(
            name="PushSubscription",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="date de création",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="dernière modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="UUID interne à l'API pour identifier la ressource",
                        primary_key=True,
                        serialize=False,
                        verbose_name="UUID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("waiting-payment", "Paiement en attente"),
                            ("group-invitation", "Invitation à un groupe"),
                            ("new-member", "Nouveau membre dans le groupe"),
                            (
                                "group-membership-limit-reminder",
                                "Les membres du groupes sont de plus en plus nombreux",
                            ),
                            ("new-message", "Nouveau message dans un de vos groupes"),
                            (
                                "new-comment",
                                "Nouveau commentaire dans une de vos discussions",
                            ),
                            (
                                "waiting-location-group",
                                "Préciser la localisation du groupe",
                            ),
                            (
                                "group-coorganization-invite",
                                "Invitation à coorganiser un groupe reçue",
                            ),
                            (
                                "waiting-location-event",
                                "Préciser la localisation d'un événement",
                            ),
                            (
                                "group-coorganization-accepted",
                                "Invitation à coorganiser un groupe acceptée",
                            ),
                            (
                                "group-info-update",
                                "Mise à jour des informations du groupe",
                            ),
                            (
                                "accepted-invitation-member",
                                "Invitation à rejoindre un groupe acceptée",
                            ),
                            (
                                "new-attendee",
                                "Un nouveau participant à votre événement",
                            ),
                            ("event-update", "Mise à jour d'un événement"),
                            (
                                "new-event-mygroups",
                                "Votre groupe organise un événement",
                            ),
                            ("new-report", "Nouveau compte-rendu d'événement"),
                            ("new-event-aroundme", "Nouvel événement près de chez moi"),
                            ("cancelled-event", "Événement annulé"),
                            ("referral-accepted", "Personne parrainée"),
                            ("announcement", "Associée à une annonce"),
                            (
                                "transferred-group-member",
                                "Un membre d'un groupe a été transferé vers un autre groupe",
                            ),
                            (
                                "new-members-through-transfer",
                                "De nouveaux membres ont été transferés vers le groupe",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                ("related_object_id", models.UUIDField()),
                ("object_id", models.IntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Type de périphérique",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
