# Generated by Django 3.1.11 on 2021-05-21 09:41

from django.db import migrations


def forward(apps, schema_editor):
    Subscription = apps.get_model("notifications", "Subscription")
    Subscription.objects.filter(activity_type="new-event-aroundme").update(
        activity_type="event-suggestion"
    )


def backward(apps, schema_editor):
    Subscription = apps.get_model("notifications", "Subscription")
    Subscription.objects.filter(activity_type="event-suggestion").update(
        activity_type="new-event-aroundme"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0009_auto_20210517_1533"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
