# Generated by Django 3.1.13 on 2021-07-28 09:29

from django.db import migrations, models

SUBSCRIPTION_PUSH = "push"

TYPE_WAITING_LOCATION_EVENT = "waiting-location-event"
TYPE_REMINDER_DOCS_EVENT_EVE = "reminder-docs-event-eve"
TYPE_REMINDER_DOCS_EVENT_NEXTDAY = "reminder-docs-event-nextday"


def add_doc_reminder_subscriptions(apps, schema_editor):
    Subscription = apps.get_model("notifications", "Subscription")

    waiting_location_subscriptions = Subscription.objects.filter(
        type=SUBSCRIPTION_PUSH,
        activity_type=TYPE_WAITING_LOCATION_EVENT,
    ).values("membership_id", "person_id")

    subscriptions = [
        Subscription(
            type=SUBSCRIPTION_PUSH,
            activity_type=TYPE_REMINDER_DOCS_EVENT_EVE,
            membership_id=s["membership_id"],
            person_id=s["person_id"],
        )
        for s in waiting_location_subscriptions
    ] + [
        Subscription(
            type=SUBSCRIPTION_PUSH,
            activity_type=TYPE_REMINDER_DOCS_EVENT_NEXTDAY,
            membership_id=s["membership_id"],
            person_id=s["person_id"],
        )
        for s in waiting_location_subscriptions
    ]

    Subscription.objects.bulk_create(subscriptions, ignore_conflicts=True)


def remove_doc_reminder_subscriptions(apps, schema_editor):
    Subscription = apps.get_model("notifications", "Subscription")
    Subscription.objects.filter(
        type=SUBSCRIPTION_PUSH,
        activity_type__in=[
            TYPE_REMINDER_DOCS_EVENT_EVE,
            TYPE_REMINDER_DOCS_EVENT_NEXTDAY,
        ],
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0011_delete_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("waiting-payment", "Paiement en attente"),
                    ("group-invitation", "Invitation à un groupe"),
                    ("new-member", "Nouveau membre dans le groupe"),
                    (
                        "group-membership-limit-reminder",
                        "Les membres du groupes sont de plus en plus nombreux",
                    ),
                    ("new-message", "Nouveau message dans un de vos groupes"),
                    ("new-comment", "Nouveau commentaire dans une de vos discussions"),
                    ("waiting-location-group", "Préciser la localisation du groupe"),
                    (
                        "group-coorganization-invite",
                        "Invitation à coorganiser un groupe reçue",
                    ),
                    (
                        "waiting-location-event",
                        "Préciser la localisation d'un événement",
                    ),
                    (
                        "group-coorganization-accepted",
                        "Invitation à coorganiser un groupe acceptée",
                    ),
                    ("group-info-update", "Mise à jour des informations du groupe"),
                    (
                        "accepted-invitation-member",
                        "Invitation à rejoindre un groupe acceptée",
                    ),
                    ("new-attendee", "Un nouveau participant à votre événement"),
                    ("event-update", "Mise à jour d'un événement"),
                    ("new-event-mygroups", "Votre groupe organise un événement"),
                    ("new-report", "Nouveau compte-rendu d'événement"),
                    ("cancelled-event", "Événement annulé"),
                    ("referral-accepted", "Personne parrainée"),
                    ("announcement", "Associée à une annonce"),
                    (
                        "transferred-group-member",
                        "Un membre d'un groupe a été transferé vers un autre groupe",
                    ),
                    (
                        "new-members-through-transfer",
                        "De nouveaux membres ont été transferés vers le groupe",
                    ),
                    ("group-creation-confirmation", "Groupe créé"),
                    ("event-suggestion", "Événement suggéré"),
                    (
                        "reminder-docs-event-eve",
                        "Rappel à la veille d'un événement des documents à envoyer",
                    ),
                    (
                        "reminder-docs-event-nextday",
                        "Rappel au lendemain d'un événement des documents à envoyer",
                    ),
                ],
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(
            add_doc_reminder_subscriptions,
            remove_doc_reminder_subscriptions,
            atomic=True,
        ),
    ]
