# Generated by Django 3.1.13 on 2021-07-27 14:20

from django.db import migrations, models

SUBSCRIPTION_PUSH = "push"
TYPE_NEW_FOLLOWER = "new-follower"
TYPE_NEW_MEMBER = "new-member"


def add_new_follower_subscription(apps, schema_editor):
    Subscription = apps.get_model("notifications", "Subscription")
    subscriptions = [
        Subscription(
            type=SUBSCRIPTION_PUSH,
            activity_type=TYPE_NEW_FOLLOWER,
            membership_id=s["membership_id"],
            person_id=s["person_id"],
        )
        for s in Subscription.objects.filter(
            type=SUBSCRIPTION_PUSH,
            activity_type=TYPE_NEW_MEMBER,
        ).values("membership_id", "person_id")
    ]
    Subscription.objects.bulk_create(subscriptions, ignore_conflicts=True)


def remove_new_follower_subscriptions(apps, schema_editor):
    Subscription = apps.get_model("notifications", "Subscription")
    Subscription.objects.filter(
        type=SUBSCRIPTION_PUSH,
        activity_type=TYPE_NEW_FOLLOWER,
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0012_event_doc_reminder_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("waiting-payment", "Paiement en attente"),
                    ("group-invitation", "Invitation à un groupe"),
                    ("new-follower", "Nouveau·lle abonné·e dans le groupe"),
                    ("new-member", "Nouveau membre dans le groupe"),
                    (
                        "member-status-changed",
                        "Un membre actif du groupe a été passé au statut abonné·e",
                    ),
                    (
                        "group-membership-limit-reminder",
                        "Les membres du groupes sont de plus en plus nombreux",
                    ),
                    ("new-message", "Nouveau message dans un de vos groupes"),
                    ("new-comment", "Nouveau commentaire dans une de vos discussions"),
                    ("waiting-location-group", "Préciser la localisation du groupe"),
                    (
                        "group-coorganization-invite",
                        "Invitation à coorganiser un groupe reçue",
                    ),
                    (
                        "waiting-location-event",
                        "Préciser la localisation d'un événement",
                    ),
                    (
                        "group-coorganization-accepted",
                        "Invitation à coorganiser un groupe acceptée",
                    ),
                    ("group-info-update", "Mise à jour des informations du groupe"),
                    (
                        "accepted-invitation-member",
                        "Invitation à rejoindre un groupe acceptée",
                    ),
                    ("new-attendee", "Un nouveau participant à votre événement"),
                    ("event-update", "Mise à jour d'un événement"),
                    ("new-event-mygroups", "Votre groupe organise un événement"),
                    ("new-report", "Nouveau compte-rendu d'événement"),
                    ("cancelled-event", "Événement annulé"),
                    ("referral-accepted", "Personne parrainée"),
                    ("announcement", "Associée à une annonce"),
                    (
                        "transferred-group-member",
                        "Un membre d'un groupe a été transferé vers un autre groupe",
                    ),
                    (
                        "new-members-through-transfer",
                        "De nouveaux membres ont été transferés vers le groupe",
                    ),
                    ("group-creation-confirmation", "Groupe créé"),
                    ("event-suggestion", "Événement suggéré"),
                ],
                max_length=50,
                verbose_name="Type",
            ),
        ),
        migrations.RunPython(
            add_new_follower_subscription,
            remove_new_follower_subscriptions,
            atomic=True,
        ),
    ]
