name: Sync staging with production branch after update
on:
  push:
    branches:
      - production
jobs:
  staging-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Open pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "staging"
          pr_title: "Syncing staging with latest production update"
          pr_draft: false
          pr_allow_empty: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tell the team the workflow has succeeded
        if: ${{ !failure() && steps.pr.outputs.pr_number != '' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ✔️ Successfully created pull request to staging after production branch update!
            #${{ steps.pr.outputs.pr_number }}: ${{ steps.pr.outputs.pr_url }}

      - name: Tell the team the workflow has failed
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ❌ Creating pull request to staging after production branch update failed!

      - name: Enable Pull Request Automerge
        if: ${{ steps.pr.outputs.pr_number != '' }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-number: ${{ steps.pr.outputs.pr_number }}
