# Generated by Django 2.2.3 on 2019-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("system_pay", "0004_auto_20190724_1628")]

    operations = [
        migrations.AddField(
            model_name="systempaytransaction",
            name="uuid",
            field=models.UUIDField(
                blank=True,
                null=True,
                unique=True,
                verbose_name="UUID fourni par SystemPay",
            ),
        )
    ]
