# Generated by Django 2.2.8 on 2020-02-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("system_pay", "0008_systempaysubscription")]

    operations = [
        migrations.AlterField(
            model_name="systempaysubscription",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="system_pay_subscriptions",
                to="payments.Subscription",
            ),
        )
    ]
