# Generated by Django 2.2.14 on 2020-08-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system_pay", "0010_auto_20200701_1622"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systempaytransaction",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Paiement en attente"),
                    (1, "Paiement terminé"),
                    (2, "Paiement abandonné au milieu"),
                    (3, "Paiement annulé avant encaissement"),
                    (4, "Paiement refusé par la banque"),
                ],
                default=0,
                verbose_name="status",
            ),
        ),
    ]
